### ISSUE TITLE
There are many duplicate points in odrplot

### ISSUE THREAD

**Issue by cy-goh** [esmini/esmini#100]
When I used odrplot to generate the lane lines (default step size is used), there were many duplicate points.

```
lane, 7493883, 0, 0, no-driving
227775.326765, 2550291.324143, 13.900000, 1.830064
227775.051628, 2550292.365517, 13.903333, 1.828361
227774.503148, 2550294.448737, 13.910000, 1.829020
227773.661334, 2550297.568444, 13.920000, 1.844560
227772.508336, 2550301.719724, 13.933333, 1.838846
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
227771.947182, 2550303.799556, 13.940000, 1.828640
```
I couldn't figure out the problem from  odrplot's main.cpp, and is unable to provide the whole xodr file due to privacy concerns.

**Comment by eknabevcc** [comment]
Thank you so much for reporting this bug. It took some time before I found it myself, but it turned out to be a noob-bug of mine :)

The idea is to sample even steps along the lanes. However this (old) code line:
`s += k * step_length;`
is actually increasing the step length for each iteration - not good (and end of lane was reach too early, hence multiple iterations got stuck on end of lane).

It's now changed into: 
`s = s_start + k * step_length;`
And I think this will both avoid duplicates and also increase resolution, since step length is kept constant, not increasing.

The fix is [commited](https://github.com/esmini/esmini/commit/08868946e977e87c22d9e291e43c940e8b3d4b81). And will be part of next release. Meanwhile you can perhaps pull and compile yourself. 

I'm pretty sure this will resolve your issue, but I keep this open until you have tested and reported the result.

**Comment by cy-goh** [comment]
I have tested it and it worked. Thank you!
