### ISSUE TITLE
Driver model

### ISSUE THREAD

**Issue by ZhangZongshi-Catarc** [esmini/esmini#103]
Hi,
I have another question about 'driver model',
If I get the value of throttle, how does it work with function 'SE_SimpleVehicleControlAnalog'? 
The value of throttle(from -1 to 1) is not the actual acceleration of vehicle, can you show me the algorithm from throttle to acceleration?

Thank you in advance and waiting for your support.

**Comment by eknabevcc** [comment]
That's true, the throttle is not directly mapping to acceleration. First, this simplified vehicle model is not very realistic, it's just provided as an example and a way to move a vehicle interactively through scenarios.
The simple vehicle model is implemented in [Modules/Controllers/vehicle.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Modules/Controllers/vehicle.cpp).

Let's try explain:
The speed is calculated as: 
`speed_ += ACCELERATION_SCALE * throttle * dt; `
So there is a constant ACCELERATION_SCALE ([here](https://github.com/esmini/esmini/blob/c9bb28c6e741806670394c261009468c9e9ce69a/EnvironmentSimulator/Modules/Controllers/vehicle.cpp#L28)) that can be tweaked, e.g. if you want a higher performance car :)

Then the speed is clamed (limited): 
`speed_ = CLAMP(speed_, -1.2 * max_speed_, 1.2 * max_speed_);`
The max_speed_ is also a constant that you can tweak. It's set to 70 [here](https://github.com/esmini/esmini/blob/c9bb28c6e741806670394c261009468c9e9ce69a/EnvironmentSimulator/Modules/Controllers/vehicle.cpp#L205) , e.g. if you want a faster car (higher top speed). 

If you can compile esmini yourself you can experiment with these values.

I'm also thinking that perhaps we could provide an API for setting these properties of the vehicle...

**Comment by ZhangZongshi-Catarc** [comment]
It will be excellent to provide an API for setting properties of the vehicle! Now the vehicle runs without dynamical model, if we can add some specific properties on it  such as suspension, tire and so on, the effect of action will be greater. 
Is there any example for such API?

**Comment by eknabevcc** [comment]
That's correct. It is not a fully dynamic vehicle model. Actually it is based on a simplified "bicycle model" with only two wheels (one front and one rear). And no suspension at all. 

There has simply not been need for more. Yet. Typically the vehicle under test is modeled in an external simulator where you could have any vehicle dynamics of your choice (and report the state, like position and orientation, continuously to esmini).

But I agree that it would be a nice to have more realistic vehicle dynamics internally as well. But as an option, since sometimes you want the exact kinematics as described from the scenario - with no additional motion.

What I can do is to extend the API to cover throttle and acceleration scale settings. But when it comes to more refined vehicle dynamics we can't prioritize at the moment. However contributions from external users are always welcome. So if you or someone else have an idea and can provide a prototype implementation we could probably bring it in. 

For example I know about [bullet](https://pybullet.org/wordpress/). I have used it previously and it was very smooth to use and integrate.

**Comment by eknabevcc** [comment]
We've now added functions for setting vehicle max speed and acceleration scale factor, see here:
https://github.com/esmini/esmini/blob/ae9c317b6ecf8ffd15cfac6897d71e7248d5f696/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L809
We will not prioritize further vehicle dynamics features for internal esmini objects at the moment. But hopefully we can support if any external user want to implement/integrate that.
I close this issue for now. Please re-open if you have further questions.
