### ISSUE TITLE
Viewer not able to make the cars move

### ISSUE THREAD

**Issue by rachitban** [esmini/esmini#111]
Hii, I am trying to create an OpenScenario file in which i am placing the vehicles on the road and the trajectory of the vehicle is defined by using world positions using polyline shape. But in the viewer I am not able to see the cars moving. What could be the possible issues ?

**Comment by rachitban** [comment]
Ya sure I am attaching the files both xosc and xodr.
[my_files.zip](https://github.com/esmini/esmini/files/6465715/my_files.zip)

**Comment by eknabevcc** [comment]
Thanks for sharing files. I found the issue. Not obvious actually.

The act is started at first timestep t=0.01. The conditionEdge is rising since last value was 0 (hence the condition simulationTime > 0 evaluated to false at that time). Now its true, why we have a rising edge.
You could expect the FollowTrajectoryAction action to start now as well. However, the events in the just started act will not be evaluated until next timestep. By then (t=0.02 or similar) the condition (simulationTime > 0) is True, however it was the case previous frame as well (t=0.01) why the edge is not rising. 

esmini behavior in this case can be questioned. And it will probably be updated. But for now the simple solution that I suggest is to change all "rising" to "none". Which means that we don't care whether the simulationTime just became > 0, as long as it is > 0 when checked, please trig.

You can try attached file:
[my_xosc-modified.xosc.txt](https://github.com/esmini/esmini/files/6466198/my_xosc-modified.xosc.txt)

**Comment by rachitban** [comment]
Thanks for such a quick response and solution. That's great.
