### ISSUE TITLE
Inquiry for additional sample of parking car moving

### ISSUE THREAD

**Issue by kgussan** [esmini/esmini#117]
Thanks for providing such a great framework. The project gives me the impression that something new is starting, like when I saw Collada in 3DCG a long time ago.
I'm currently trying to write a sample of a car moving in a parking lot using OpenScenario. However, there are many examples of moving vehicles on lanes, and I have yet to understand how to describe moving a vehicle in a parking lot. 
(I have read and modified "parking_lot.xosc" and some lane change samples.)
If possible, I would be very happy if someone could consider adding a sample where a vehicle teleports and parks in a parking lot.
Regards,Yoroshiku-Onegaishimasu.

**Comment by eknabe** [comment]
Parking is a very interesting use case. However it has not yet been prioritized on our side yet. So unfortunately there is basically no explicit support for it in esmini (yet). 
I know that OpenDRIVE has support for [parking spaces](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4089&token=deea5d707e2d0edeeb4fccd544a973de4bc46a09#_objects) (subtype of object). 
Also there is some discussions within OpenSCENARIO 1.X regarding parking use cases. 

The parking log example is a bit misleading I realize. The purpose of that example is to show how you can use esmini with basically no scenario and without road network (OpenDRIVE description is not required). Potentially it can be a parking lot with painted spaces, for a camera-sensor in the loop. 

To conclude, you are in the frontline. esmini does not support explicit parking maneuvering, and no such near time plans. OpenDRIVE has some support. OpenSCENARIO hasn't yet, but might get in future releases. 

However sometimes things changes fast. So I'll let you know if we, or any external esmini user, start any development in this direction.

**Comment by kgussan** [comment]
Thank you for the information.
I understand that the parking function is not yet supported.

Supplement : 
Regarding parking spaces, in OpenDrive 1.0 it was only possible to set parking spaces as points, but I have just confirmed that in the current OpenDrive specification that parking spaces can be set as rectangles with angles.
- OpenDRIVE 1.6.1 Specification - 11.5. Access rules to parking spaces

Regarding the path generation, I think the path is more complicated in parking because of the turnaround and other elements.
For this reason, I think it would be easier to write a parking scenario if the path is calculated in advance and the position and angle are replayed for each frame (teleport method).

I'm trying to find a way to specify the car's position and angle chronologically using teleport, so if anyone knows of such an example I'd be grateful if you could let me know.

**Comment by eknabe** [comment]
Ah, maybe the solution to your use case is simply [trajectory](https://www.asam.net/static_downloads/modelDocumentation/index.html)? Trajectories can be of three basic shape types:
* Polyline (just a sequence of lines between points)
* Clothoid (spiral, unfortunately one one per trajectory)
* Nurbs (really flexible with any number of weighted control-points and knot vector with optional varying multiplicity/degree)

You can see the [trajectory-test.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/trajectory-test.xosc) example scenario. It's a bit silly, but shows how to specify the three types. If you have downloaded esmini (or compiled on your own) you can run the example from [run/esmini/run_trajectory-test.bat].(https://github.com/esmini/esmini/blob/master/run/esmini/run_trajectory-test.bat).

Control-points can optionally include timestamp to "hardcode" the speed profile within the trajectory. Otherwise the speed can be defined independently using SpeedAction(s). 
Also the PolyLine variant allows for explicit heading/yaw at each control point. 

But, of course. Trajectories is not very flexible and needs to be pre-calculated somewhere and somehow (and then stored in the scenario file or catalogs). In future there might be other more high level ways of stating parking maneuvers. But hopefully you can use trajectories for now.

**Comment by kgussan** [comment]
Thank you for letting me know.
Yes, my problem is the trajectory settings. My purpose is to use the parking situation, but the trajectory setting is the essence of the problem.
I'll try the sample trajectory-test.bat you gave me right away!
I still don't understand the example of putting timestamps in control points, but I'll try it with the sample.
Thanks a lot!

**Comment by eknabevcc** [comment]
You can see example of timestamp in control points in the [resources/xosc/trajectory-test.xosc]. 
(https://github.com/esmini/esmini/blob/master/resources/xosc/trajectory-test.xosc) example.
Both in the [polyline](https://github.com/esmini/esmini/blob/31d4ce67bb1b9c1a58002b31d6792e22954ce447/resources/xosc/trajectory-test.xosc#L120) and [nurbs](https://github.com/esmini/esmini/blob/31d4ce67bb1b9c1a58002b31d6792e22954ce447/resources/xosc/trajectory-test.xosc#L210) trajectories.
If you manipulate the time values you'll see how the speed will change.

But as said, maybe better to set TimingReference = None, like this:
```
<TimeReference>
    <None/>
</TimeReference>
```
and control longitudinal speed with SpeedAction.

**Comment by eknabevcc** [comment]
Closing issue. Please re-open for further questions on the topic.
