### ISSUE TITLE
Option to run in window mode (--window) is undocumented

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#119]
I found that the option to run in window mode is undocumented, i.e., it does not appear when calling esmini with `-h/--help`.

**Comment by eknabe** [comment]
Good point 👍. Added a few useful OpenSceneGraph options to the usage help info in commit ac337a4870b12ed15c7ad5b2c07f31ac33cc56e2.

**Comment by johschmitz** [comment]
Ah okay good, it seems you are forwarding certain options? Can't you
explain that in the help somehow such that one can understand it and look
up all possible additional options somewhere else (mention where)?

**Comment by eknabe** [comment]
True, since esmini is using the OsgViewer class, most of the osgviewer application options and environment variables should be applicable. There is no official documentation of the options, but I generated a list and put it under docs: 
https://github.com/esmini/esmini/blob/master/docs/osg_options_and_env_variables.txt
Also referring to that list from:
https://github.com/esmini/esmini/blob/master/docs/commands.txt
and
https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/odrviewer/readme.txt

I think the ones highlighted in these documents are the most useful/common ones. But there's a lot of additional features that can potentially be handy for specific use cases. So thanks for suggestion.

**Comment by eknabevcc** [comment]
part of release [v2.8.4](https://github.com/esmini/esmini/releases/tag/v2.8.4). 
Closing issue.
