### ISSUE TITLE
Change Lane with External Controller

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#120]
By using the python wrapper, I used external controller with SE_ReportObject... However I could not manage to get the target vehicle's position info. Also as I understand, to change lane I should write a controller that increases offset on the initial lane and then at a certain point, changes the laneId and offset of the vehicle at that exact position. Could you give me an example of getting the target's info so that I can use it as a triggering?

**Comment by eknabevcc** [comment]
1. Get object info: See this example code:
https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#fetch-state-of-scenario-objects
It shows how to get the state of any object (by id/index as they appear in scenario file). In the struct [SE_ScenarioObjectState](https://github.com/esmini/esmini/blob/21c7d76d9cc14684111f1bc7f87d0c7b1d575694/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L23) you find, among others, RoadID, laneID and lane offset.  
If you know the index of the target, you can of course skip the for-loop. 

2. Lane change controller. Well, the simplest would be to specify the lane change in the scenario file, since then esmini default controller will handle it all. But I understand you want to control it externally. Then you're on the right track. You can update the position using the [SE_ReportObjectRoadPos()](https://github.com/esmini/esmini/blob/21c7d76d9cc14684111f1bc7f87d0c7b1d575694/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L460) function, and there set laneOffset. The other values, e.g. roadId, LaneId and s, can be just copied from the call to SE_GetObjectState().

**Comment by aktasalifurkan** [comment]
def callback(state_ptr, b):
    state = state_ptr.contents
    for j in range(se.SE_GetNumberOfObjects()):
        se.SE_GetObjectState(c_int(j), state._fields_[15][0])
        print("callback for obj {}: speed={}".format(j, state.speed))

Isn't is it the thing to apply? In this way, I got only ego vehicle's speed. But I understood the concept of changing lanes though. After I try to implement it, I will let you know if I encounter any problems.

**Comment by aktasalifurkan** [comment]
Ooohh it was related to "SE_RegisterObjectCallback". I got it now thank you anyway :)

**Comment by aktasalifurkan** [comment]
As I understand it was related to "SE_RegisterObjectCallback". In this regard, how can I use info the that I got from the target vehicle's callback func. in ego vehicle's callback function?

**Comment by aktasalifurkan** [comment]
I understand the process now better now thank you :)

**Comment by eknabevcc** [comment]
Good to hear :)
Anyway, I added an example showing how you can retrieve (all) object states in Python:
https://github.com/esmini/esmini/tree/master/Hello-World_coding-example#example-get-object-states

**Comment by eknabevcc** [comment]
Close resolved issue.
