### ISSUE TITLE
esmini crashes when scenegraph file does not exist

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#123]
The esmini executable crashes with a segmentation fault when the scenegraph file does not exist.

Probably you are not checking for file existence before trying to open scenegraph model files specified in the OpenSCENARIO file. I guess the same might happen for vehicle models etc. as well.

**Comment by eknabevcc** [comment]
Can't reproduce. 
If scenegraph file is not found esmini creates a simple road model.
If vehicle model is not found esmini creates a simple model based on the bounding box.
This is the expected behavior, and what I get when setting filenames that does not exist (at least on Windows and Linux).

Please provide more info so we can re-produce the problem. E.g. What platform and what version of esmini? Also if you can share the scenario file would probably help us nailing the issue.

**Comment by johschmitz** [comment]
Sorry my fault. If I can reproduce it will supply a minimum example. Of course I do know better and should have done this immediately! If you don't hear anything within a week feel free to close.

**Comment by johschmitz** [comment]
@eknabe  I tried to reproduce the issue but can not find the condition anymore. Feeling really sorry about it. Should not have reported it like this but was a bit tired after many hours of coding and just wanted to make sure to report that there is a problem.  Missed opportunity to catch an ugly segmentation fault bug. I am shamefully closing this and promise to do a more thorough analysis in the future. One question if I see it again: I will have to compile esmini myself for a DEBUG build and creating a stack trace is that correct? Or do you have some hidden release archive page with debug builds?

**Comment by eknabevcc** [comment]
You should not be ashamed at all. I/we highly appreciate your (and everyone's) reports of ideas, bugs or other shortcomings. We do a lot of mistakes on our end as well. So it is not unexpected at all that reports get it wrong as well, now and then. 
So please keep bring it on :)  
On our end, we are a bit ashamed sometimes when we need to close issues that are correct/good, but we lack time so it can't be prioritized on our end. Like the recent catalog-discussion.

**Comment by eknabevcc** [comment]
Forgot to actually answer the question: Yes, you need to compile Debug versions on your own. They are built in the CI flow (to find potential compile issues), but not stored - mostly due to storage limitations.
But if you find a segmentation fault on a Release build, I'd be happy to debug it if you provide the input files.
