### ISSUE TITLE
Is the catalogName the catalog filename?

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#124]
I tried to create a vehicle catalog with the name VehicleCatalog and the filename vehicle_catalog.xosc but esmini was unable to load it. Shouldn't it check all files in the specified catalog directory and find the catalog but the name specified in `<Catalog name="VehicleCatalog">` or how does it work?

I would classify this as a bug. But maybe the standard says to interpret the name as a filename?

**Comment by johschmitz** [comment]
I can put `<CatalogReference catalogName="vehicle_catalog" entryName="car"/>` (without .xosc!) and then it works but that is weird that all other referenced files are specified with an ending except for the catalog.

**Comment by johschmitz** [comment]
Okay I checked it in the standard:
https://www.asam.net/static_downloads/modelDocumentation/content/VehicleCatalogLocation.html
It clearly says:
> All catalogs files in this directory must be evaluated.
So I would say the esmini implementation is wrong.

**Comment by eknabevcc** [comment]
esmini DO consider all catalog files in the directory. However the catalog name must correlate to the filename (minus extension).

This correlation is an esmini thing. We see no reason to have different names on catalog file and actual catalog (since there is only one catalog per file anyway).  So yes, this is a "limitation" of esmini. 

On the other hand this correlation is very useful since it eliminates the need to open all files in the directory and look for requested catalog name. (We want esmini to be lightweight that scales well into 100k of batch scenario runs. System calls should be avoided whenever possible.) So this design is an active choice. 

When we finally add documentation this should be mentioned to avoid confusion.

**Comment by johschmitz** [comment]
I think the standard is just bad towards this end. They should have just put in the filename. Maybe a new version of the standard can add this as an extension to allow for specifiying the filename instead of the directory.

I don't know if it is a good idea though that esmini should enforce the described behavior. It makes it incompatible with the output of tools that do not follow this convention. Frustrating. Reminds me of my Matlab times where they have a similar convention 😁 
Also usually catalogs are in sub-directories and hence there should not be thousands of catalogs files to parse. Did you ever really observe performance issues due to going through too many catalogs?

At least you should add the information that the catalog name and filename need to be identical to the error message that is thrown when you don't find anything. That would help a lot.

Also it seems the scenariogeneration lib only allows the name to be 'VehicleCatalog' (I need to investigate more) so with this combination of behavior it becomes difficult to have multiple catalog files. Maybe I will open another ticket in scenariogeneration to fix it there once I fully understand it.

**Comment by eknabevcc** [comment]
It could be the case that early ideas of the catalog concept supported multiple catalogs within one single catalog file. In that context it makes sense to refer to catalog name instead of filename. But as it is now, with only one catalog per file, I agree that referring filename would be preferred. esmini convention is the compromise choice of ours, by aligning names of file and catalog. 
I know there are a few open issues/discussions in the OpenSCENARIO 1.X project regarding this and related topics. Perhaps there will be some adjustments in upcoming releases. 
Since users normally can control the name of both catalog and file, at least by simple scripting, I still prefer esmini behavior (over scanning all files). 
Good or bad, we'll keep current behavior as for now (but maybe not forever, we may change or any user in need may do it).
