### ISSUE TITLE
limit OSI Ground Truth around ego vehicle

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#128]
Hi,

is there a way to limit the ground truth "objects" to a radius around the ego vehicle?

I'm trying to make esmini run with OSI Sensor Models () and sending the whole ground truth with the Sensor View leads to very poor performance because the serialization takes much CPU time. The Sensor View can be limited to the sensor range. 

I could implement this in my client, but then I would just "move" the bottleneck. I think a solution needs to be directly in esmini for optimal speed.
OSI standard uses a "SenserViewConfig" message to define the environment simulator the are of interest for a sensor model.

Do you have plans to implement this functionality? 

Or do you have an idea, how we could limit the ground truth with a radius around a vehicle as a first step with minimum effort?

Best regards
Simon

**Comment by eknabevcc** [comment]
Thanks for the question. 
I think esmini, so far, only supports complete ground-truth. Some time ago the OSI handling was updated separating static and dynamic part of the ground truth. This way only dynamic content needs to be updated for each timestep. But no, I don't think we have any other way of filtering/limiting the OSI content. 

And yes, I think the strategy is to provide complete ground-truth and do filtering and further processing outside esmini, e.g. filter and transforming to local sensor coordinate system. 

But I admit it sounds nice with some ways of limiting relevant OSI data. 

@mguldogu, do you have any ideas or comments? You see any way of implementing a "simple" filter with minimum effort?

**Comment by mguldogu** [comment]
Thanks for the question @sterres
We intended to keep the complete groundtruth OSI data in esmini as @eknabevcc mentioned.
All the groundtruth data which is limited to SensorView could as well be handled  using "radius" and "range" information; however, this is something we handle outside of esmini today since we consider esmini as the complete representation of the defined world as described in XOSC and XODR files.

But this is good question and we might consider adding this in esmini in the future. 
I think for now, there is no direct way of extracting that kind of data.

And, I know the problem you talk about here. Serialization takes a lot of time and therefore, we fetch the raw data from esmini to our external simulator instead today. And, unfortunately, I am aware that this is not possible for every application.

If this is super important for you to do it for now, you can work on esmini on your local and and only populate **gt_dynamic** data for target vehicles if it satisfy your radius/range condition.

**Comment by eknabevcc** [comment]
Good @mguldogu that you mentioned the serialization/raw aspect.
We should point out that esmini offer two variants of getting OSI data:
[SE_DLL_API const char *SE_GetOSIGroundTruth(int *size);](https://github.com/esmini/esmini/blob/627919d587abf1cd144d8ea33ff16b2921cfe44d/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L701)
[SE_DLL_API const char *SE_GetOSIGroundTruthRaw();](https://github.com/esmini/esmini/blob/627919d587abf1cd144d8ea33ff16b2921cfe44d/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L707)
The raw variant actually just hands over a reference/pointer to the actual struct containing the data, skipping serialization altogether. Here's a code example doing it that way: 
https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/osi-groundtruth/osi-groundtruth.cpp
It is also possible from other platforms, e.g. Python and Unity. You just need to be careful defining the struct on the receiving side in a perfectly matching way.

**Comment by eknabevcc** [comment]
Closing inactive issue. Please re-open for further questions on the topic.
