### ISSUE TITLE
RoadManager Junction GetNumberOfConnections() returns wrong number

### ISSUE THREAD

**Issue by dalishi** [esmini/esmini#130]
Hi,
I noticed the master version does not return correct number of connections in junction when using RoadManager junction's GetNumberOfConnections(). Simply add the following code in odrplot and test with a sample .xodr e.g. ../resources/xodr/multi_intersections.xodr. We will get

Junction 146 -> GetNumberOfConnections: 24

while the actual number of connections is 12. It seems the returned number of connections is always double the actual number. I also tested with old esmini version and no such problem spotted.

	for (int j = 0; j < od->GetNumOfJunctions(); j++)
	{
	    Junction* junction = od->GetJunctionByIdx(j);
	    printf("Junction %d -> GetNumberOfConnections: %d\n", junction->GetId(), junction->GetNumberOfConnections());
	}

**Comment by eknabevcc** [comment]
That's very true! I realize that it returns exactly 2 x initial number of connections. 

The reason is that for each connection we add another one in the opposite direction. This is to support a few corner use cases, e.g. 1. Left hand traffic (on a road network defined for right hand traffic) and 2. Reaching a connection while temporarily going in opposite direction, e.g. overtaking. If connections only exist in one direction, vehicles would get stuck in those cases.

And yes, this was added quite recently, in release [2.8.2](https://github.com/esmini/esmini/blob/master/release_notes.md#2021-05-17-version-282), May 17 2021.

It could probably be solved in other ways, but that's how it is implemented currently.

If the connections would be investigated you would find that for each road and lane the initial connections are still correct and matching the OpenDRIVE description. It's just that we added connections in opposite directions (if) that did not exist.

But I totally understand this could potentially be an issue, or at least confusing. I'm thinking about reporting only the number if initial connections. But then it's not really the truth, and could cause confusion the other way around...

What use case do you have, and does the current behavior cause trouble? What would your suggestion be?

**Comment by dalishi** [comment]
Hi @eknabevcc Thanks for sharing the rationale behind this. I have not encountered the two use cases you mentioned so I might not fully understand the reason. In my case, each OpenDrive map is either built for left-hand driving or right-hand driving, and there are no mixed use cases; for the opposite direction overtaking, I wonder whether the connection roads of two directions overlapped or adjacent? If overlapped, how to overtake in opposite direction is beyond my imagination. If not overlapped, does the newly added opposite road really exist in physical world? In my case, the connection road in junction is always one single direction according to the OpenDrive standard (I'm using old version 1.4).

In my case, I have an OpenDrive format map given by map provider, and I need to sample waypoints along each road from geometry. When I iterate through connections, I found I got more connections than the actual number given in the map and got confused duplicate sampling points probably in opposite direction as you described.

I cannot say I fully understand the reasons why it has to be solved in this way. The quick suggestion off the top of my head would be hierarchical design. Let the bottom layers APIs return the results stick to the fact what the map gives, and have a higher level of APIs add support for advanced use cases. I might be wrong.

If this is the case, can close this issue now. Thanks.

**Comment by eknabevcc** [comment]
By adding links in the opposite directions any road can be used for scenarios with right and left hand traffic. The attribute "rule", added in OpenDRIVE 1.5, dictates left or right hand traffic. And with our approach this can easily be changed between left and right, without the need to rework the connections. 
I don't think the added connections should cause any confusion. If you search a route from any location in the road network, you can easily find (only) those connections valid in relevant direction. 
A naïve suggestion: Think about the map as if it actually had all reverse connections defined from scratch (which I assume could be the case - but I might be wrong...). Then when you look for routes/waypoints, consider driving direction. That would filter out only relevant connections.
Regarding the overtaking. I don't really follow your reasoning. We don't add any roads, just lane connections on existing connecting roads. (by the way, I also seen OpenDRIVE files with only single direction connecting roads, but I don't think the standard prevents you to define connections from both ends, like any normal road lane). The issue we found was when a vehicle temporarily was driving in opposite lane entering a junction. That lane had a connection in the junction, however it was outgoing and hence was not found/accepted. By adding the reverse connection we solved such issues. And so far, we did not find any issues with the strategy. 
It could for sure be solved in other better ways, and anyone is welcome to propose implementations that extend functionality or improve existing one. We have limited resources and since we don't see a real issue (yet) it's hard to prioritize refactorization on this part right now (even though I would like to).

**Comment by dalishi** [comment]
This is not a real issue for me either but it is good to know the story. I have closed this issue for now. Thanks.

**Comment by eknabevcc** [comment]
Ok. Thanks for reporting it, and reminding me of this side effect. We'll keep it in mind for future works. 👍
