### ISSUE TITLE
No lane change?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#134]
Hi,

can you help me to understand why I see no lane change in the recorded data in the y-position of target vehicle?

[CutIn001.csv](https://github.com/esmini/esmini/files/6741001/CutIn001.csv)
[CutIn001.xodr.txt](https://github.com/esmini/esmini/files/6741002/CutIn001.xodr.txt)
[CutIn001.xosc.txt](https://github.com/esmini/esmini/files/6741003/CutIn001.xosc.txt)

At starting point there is a distance of 50 - 4.7 (ego wheelbase + ego front overhang + target rear overhang, x offset is always = rear overhang) = 45.3 between the two vehicles. If the distance is lower than 50, then the cutin shall be executed. Can it be, that if the lane change condition is already fulfilled with starting point, that no action is executed? Maybe here is always expected, that the distance is larger than 50 that the trigger could work, or do you see any other problems with the xosc?

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
Yes I can. The problem is that the rising edge of CutInActStart is missed, hence the CutInEvent is never triggered.

The root cause is not obvious. At time 0.00 the act is triggered. But it's child ManeuverGroups are not evaluated until next timestep, e.g. 0.01. At that point the condition simulationTime > 0 is true, but there is no previous value to compare to - hence the rising edge is not detected. 

My suggestion is to use conditionEdge="none" as default, and rise just when you really need it. conditionEdge "none" means that the condition is evaluated as is, regardless of history - which I think is what most often is what you need. And you avoid the risk of missing an edge which only last for one frame.
Please see attached slightly modified scenario.
[CutIn001-edit.xosc.txt](https://github.com/esmini/esmini/files/6761989/CutIn001-edit.xosc.txt)

See also this issue (same root cause): https://github.com/esmini/esmini/issues/111#issuecomment-839742633

**Comment by tmIdiada** [comment]
Thank you a lot Emil, this is very tricky and seems to occur not only once ;-). Maybe it would be a good idea to implement a warning for conditions with **simulation time larger than 0** in combination with **rising edges**, that such a combination makes no sense and here a none should be used. Maybe one can change this rising edge to a none automatically in such a combination and add this change to the warning message?

**Comment by eknabevcc** [comment]
Thanks Thaddäus. Good idea with such a warning (at least). 👍 We'll keep it in mind, and see what we can do.

**Comment by eknabevcc** [comment]
We just added a warning along idea of yours (commit 1d4988074137dffe39e51e755de2d41dc947d88b).

Then, when revisiting your scenario I suddenly realized that the simulationTime=0 situation was NOT the issue in your specific case.
Instead at start the distance (in CutInStartCondition) is ~45 at start. I.e. already less than 50 which. Hence the edge is never detected. 

So it's a similar problem to that of simulationTime = 0 (where there are no previous value to define an edge from).

Perhaps confusing, but anyway it's a good idea to put edge=none as default, and then use other edges when really needed.

Just wanted to correct my previous message.

**Comment by tmIdiada** [comment]
Hi,
thank you a lot for this message, especially regarding simulation time. This message would not really be helpful for my case, because in my case the distance was the problem, which was also fulfilled at starting point. In such a case also a warning would be helpful for non-experienced users, but such a message would maybe disturb all other users, who are using such edge conditions and where the "none" condition would do the false thing.

Here a message would only make sense at the end of simulation, by checking all conditions, which have been never fulfilled with rising edges and print such a warning for them, that they were fulfilled at starting point (after check) and maybe one wants to use "none" instead. But I expect esmini does not really record which conditions exist and have not been triggered during simulation. This would be a nice feature for the future, that is far far away ;-).

Thanks Emil,

Thaddäus
