### ISSUE TITLE
Crossing Road Scenarios

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#138]
For pedestrian crossing the road scenarios, is there a way to do it with specific acceleration? Somehow, any LateralAction feature did not work, and also for the FollowTrajectoryAction, the action started with constant speed but not with any acceleration. The LateralAction works if I have longitudinal speed but since it is a crossing road scenario, pedestrian can not have any longitudinal speed. Is this problem related to Esmini or OpenSCENARIO?

**Comment by eknabevcc** [comment]
You're right. Lateral actions, like [LaneChangeAction](https://www.asam.net/static_downloads/modelDocumentation/content/LaneChangeAction.html), assumes forward motion. At least when duration is specified in terms of (longitudinal) distance (i.e. after what traveled distance should the lane change be fulfilled) it makes sense. This might be a limitation of esmini. Perhaps the standard allows to move an entity perfectly in only lateral dimension using the LaneChangeAction with time or rate dynamic dimensions, I'm simply not sure unfortunately.

Anyway, as you also mention, I would use the [FollowTrajectoryAction](https://www.asam.net/static_downloads/modelDocumentation/content/FollowTrajectoryAction.html) which can describe pretty much any motion either in terms of world coordinates or road coordinates. For example it's perfect if you want a path across the road, since you can define trajectory points in terms of road coordinates. See [pedestrian.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/pedestrian.xosc) (and [run/esmini/run_pedestrian.bat](https://github.com/esmini/esmini/blob/master/run/esmini/run_pedestrian.bat)) for an example. 

And regarding speed when following trajectory: You have an option to hardcode time stamps (and hence speed) in the trajectory control points. Otherwise speed will be controlled by other actions. This is controlled by the [TimeReference element](https://www.asam.net/static_downloads/modelDocumentation/content/TimeReference.html). See also [this comment](https://github.com/esmini/esmini/issues/117#issuecomment-848624517). Please try set:
```
<TimeReference>
    <None/>
</TimeReference>
```

**Comment by aktasalifurkan** [comment]
Thank you for your response. Now with using TimeReference as "None", it works for me because I can use "SpeedAction".
