### ISSUE TITLE
Can scenarios export from Matlab be played in esmini player?

### ISSUE THREAD

**Issue by alicankahraman** [esmini/esmini#142]
Hi,
I get an error when play the scenarios(.xosc) which exported from Matlab in esmini.
Exported scenario link: (parking.xosc example)
https://ch.mathworks.com/help/driving/ref/drivingscenario.export.html#mw_bbb27b43-dd64-4f95-affc-39f501d67ff8
Errors:
segmentation fault 
and
![image](https://user-images.githubusercontent.com/79085330/128821101-f13a99fd-b968-4af1-b797-c60aef39ae17.png)

**Comment by eknabevcc** [comment]
In order to investigate we need the actual scenario files. Could you please provide those (xosc, xodr and catalogs if any)?

**Comment by alicankahraman** [comment]
Thanks for your attention

**Comment by alicankahraman** [comment]
Thank you for your concern. 
In the following repository you can find 2 example which exported from Matlab:
[https://github.com/alicankahraman/Scenarios-exported-from-MATLAB-/tree/main](url)

**Comment by eknabevcc** [comment]
Thanks for providing the scenario files. 
I can confirm the issue. There was a bug in esmini up to version 2.11.2 which couldn't handle multiple route waypoints on the same road. That bug is fixed (commit 9707583d76135a365181ba62b4bf270efa4d5c44) from release 2.11.3. 

And at least your scenario starts with esmini version >= 2.11.3. So my advice is to grab the latest esmini version from [here](https://github.com/esmini/esmini/releases). 

But since the scenario looks a bit strange I think there are other issues. Perhaps the parking maneuver is described in terms of route waypoints in a way not supported in esmini. For me trajectory is a better tool for detailed maneuvering. Routes (and waypoints) are typically for high level routing, e.g. find a path from A to B in a complex road network - to find or define how to turn in intersections. But this is just my thinking, and not related to the initial issue :)

**Comment by eknabevcc** [comment]
Closing inactive issue. Please re-open for further questions.

**Comment by eknabevcc** [comment]
Interesting. I found [this page](https://ww2.mathworks.cn/help/driving/ref/roadrunner.hdmap.staticobjecttype.html) mentioning the Eucalyptus_Sm01 in the context of using static objects. It seems that the original Roadrunner catalog model are in the fbx format. 

I would first check whether Roadrunner embed static objects into the main model (2.osgb).  As a second approach, I'd try to localize the files and convert them to osgb for use with esmini. 

Here is some info regarding converting fbx to osgb:
[esmini User guide - OpenSceneGraph and 3D models](https://esmini.github.io/#_openscenegraph_and_3d_models)
