### ISSUE TITLE
To define  `MiscObject` as `Catalog`  is not supported. 

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#146]
I tried to define `MiscObject` as `Catalog` , but it occurred error.

in the current implementation, To define  `MiscObject` as `Catalog`  is not supported. 

https://github.com/esmini/esmini/blob/f978f3a8ad050172d78df82198db6f3b2916be16/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/ScenarioReader.cpp#L960

( I saw a bit of the source code, so, if my understanding may be wrong, I'm sorry.)

In OSC description, I think this can do. Do you have any plans to support ?

https://releases.asam.net/OpenSCENARIO/1.0.0/ASAM_OpenSCENARIO_BS-1-2_User-Guide_V1-0-0.html#_re_use_mechanisms

3.4.2. Catalogs

> There are eight different kinds of elements that can be outsourced to a Catalog. All kinds of objects can be defined within Catalogs, i.e. Vehicle, Pedestrian, and MiscObject, as well as their respective Controllers.

**Comment by eknabevcc** [comment]
Thanks for reporting this gap. It should be fixed in commit 26752eafa915b081d5ff6409f0ce4871f3d7c204 and release [v2.13.0](https://github.com/esmini/esmini/releases/tag/v2.13.0).

However we haven't tested it, so it would be great if you could test and report back any issues - which we then will fix.

**Comment by bleach31** [comment]
Thank you for the quick response.

The test of using `MiscObject` from another catalog file has been successfully done as expected
