### ISSUE TITLE
Event without startTrigger causes a forced exit

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#147]
https://www.asam.net/static_downloads/modelDocumentation/content/Event.html

> Actions are executed as soon as the start trigger fires. This point in time represents the start of the event. If this optional field is missing, the event starts as soon as the start trigger of the enclosing act starts.

For example, if I remove the StartTrigger (L76-L93) in `Event` (name = Lane change action)  from [this scenario](https://github.com/esmini/esmini/blob/master/resources/xosc/lane_change_simple.xosc)

I expect that vehicle starts lane change immediately after the start of the scenario.

In reality, however, Esmini is forced exit.

Is this a mistake in the my interpretation of the OSC or is it  just unsupported problem?

**Comment by eknabevcc** [comment]
Good finding. esmini assumed at least an empty Trigger, `<StartTrigger/>`, but as you correctly state for events the StartTrigger is optional and hence can be omitted completely.
It's now fixed in commit eca86c07397b7cfea64285e0d35a6405e6351ebb and release [v2.13.0](https://github.com/esmini/esmini/releases/tag/v2.13.0).

Please report back if it works as expected or not.

**Comment by bleach31** [comment]
It worked as expected.
Thank you for the quick response!
