### ISSUE TITLE
Test identifiers of scenario files

### ISSUE THREAD

**Issue by fatihmms** [esmini/esmini#148]
Hello again,

I need to add some constant values of vehicles such as width, length or final speed to csv files. Is there any way to get them in Esmini? I looked at the code but I could not see for that. 

Thank you very much.

**Comment by eknabevcc** [comment]
I think I understand your need. You'd like to add some single values/constants to the log header AFTER the scenario has executed.
I don't see any easy way of doing this since the log is created up front and populated along the execution of the scenario.
A solution idea would be to log such data separately (maybe just a one shot writing to a separate file before closing the scenario). And then, as a post processing step, merge the that data into the csv logfile using a Python script or similar.

Anyway, how to fetch the dimensions of an object I can show:
obj->boundingbox_.dimensions_.length_
obj->boundingbox_.dimensions_.width_

Let's use the [CSV_Log->LogVehicleData](https://github.com/esmini/esmini/blob/191c736285ca203fa5c19558442f84aec5aba03f/EnvironmentSimulator/Modules/PlayerBase/playerbase.cpp#L943). It could be extended as: 
`CSV_Log->LogVehicleData(isendline, scenarioEngine->getSimulationTime(), name_,
	obj->id_, obj->speed_, obj->wheel_angle_, obj->wheel_rot_, obj->boundingbox_.dimensions_.width_, 
	pos.GetX(), pos.GetY(), pos.GetZ(), pos.GetAccX(), pos.GetAccY(), pos.GetAccZ(),
	pos.GetS(), pos.GetT(), pos.GetH(), pos.GetHRate(), pos.GetHRelative(), pos.GetHRelativeDrivingDirection(),
	pos.GetP(), pos.GetCurvature());`

But of course, then you would get the constant dimensions on every log entry, which is a bit waste.
(and you would need to update the CSV_Logger class accordingly...)

**Comment by eknabevcc** [comment]
This commit can be used as "template" how to add custom values to csv log file: https://github.com/esmini/esmini/commit/e7d51a252f12270ab55197030ea5ec554a97ae5d

Closing issue.
