### ISSUE TITLE
issues with custom 3d vehicle models

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#154]
Hi,

I'm trying to import a custom vehicle model and having some issues:

**1. in esmini, the colors look wrong**
I assume the lighting is different in esmini. In osgviewer the model looks as it does in Blender.

Could it be related to this log message?
> Failed to locate shadow model shadow_face.osgb based on vehicle model filename sportscar_mod.osgb - continue without

**2. wheels do not turn**
I created separate wheel nodes as described in your post (https://github.com/esmini/esmini/issues/63#issuecomment-742273326). 
The esminilog of older releases said sth. about Wheel nodes not found. In the newest build (2.13.3) there is no message in the log anymore.
Is there more requirements than just the node names to make the wheels turn correctly? For example defining wheel attributes in .xosc vehicle definition?

**My workflow is:**
- Blender -> export as .obj
- osgconv -> convert to .osgb
- test it in esmini

Screenshots:
![image](https://user-images.githubusercontent.com/30345042/132488360-eeef7740-e9dd-48f3-8082-6cb6a6b1d546.png)

![image](https://user-images.githubusercontent.com/30345042/132488637-59265ecd-5781-4431-a0ca-ab429f1c3653.png)

Hope you can help.

Best regards
Simon

**Comment by eknabevcc** [comment]
I usually get problems with material and lighting properties both with .obj, .fbx and .dae. One explanation why it may look OK in osgviewer is that the ambient level is 0 (I think), hence polygons facing away from single light-source (which seems to follow camera viewing point) gets really dark. See example below:
![image](https://user-images.githubusercontent.com/29146839/132509908-d25eb850-d40b-4245-823f-24999bffefb5.png)
So in esmini we added some ambient contribution to the materials, to mimic normal background daylight. (could be achieved by setting up more light sources, but we try to keep it simple).

The log message regarding shadow_face.osgb indicates that file is missing. No big issue, but the face is used to fake shadow on ground under car. You can try to put a copy of that file in model folder. Or add --path to the esmini/resources/models folder.
You can see the difference in your last image where the nice car lacks the fake shadow while the red box car has it.

Back to the colors. When exporting **OBJ**, I get the following typical material definition:
```
newmtl Material
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.142857 0.185714 0.757143
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
```
As you see the ambient color is max 1.0. Looks bad in esmini, like this:
![image](https://user-images.githubusercontent.com/29146839/132575837-3e965fa2-9353-4832-a19c-d056ea86c86c.png)
Copying the diffuse color to ambient, like this:
```
newmtl Material
Ns 323.999994
Ka 0.142857 0.185714 0.757143
Kd 0.142857 0.185714 0.757143
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
```
looks better, like this:
![image](https://user-images.githubusercontent.com/29146839/132576205-7b07b939-dd25-4cb3-8834-86888ec33640.png)

Another problem with with .obj is the lack of hierarchy support (see "About" section here: https://andrewnoske.com/wiki/OBJ_file_format). This limitation flattens the model so that wheel nodes are not children of the main car node. Plus objects are renamed in the export process, so that wheel_rr may become wheel_rr_Cube.001.
All this can of course be fixed. But I think fbx and dae are better choices anyway. So lets move on.

**FBX** is a stable 3D format maintained by Autodesk. There are a few details to care about. 
At export I use following settings:
![fbx-settings](https://user-images.githubusercontent.com/29146839/132577008-2634b350-d5a2-43f6-883a-fb7674e8813e.png)
Then for conversion to osgb I use the following options:
`osgconv car.fbx car.osgb -o 90-1,0,0 --use-world-frame`

Still I have one issue with fbx export/conversion: Colors gets too dark. Converting to osg (OSG ascii), like this:
`osgconv car.fbx car.osg -o 90-1,0,0 --use-world-frame`
reviles following material settings:
```
            Material {
              name "Material"
              ColorMode OFF
              ambientColor 0 0 0 1
              diffuseColor 0.142857 0.185714 0.757143 1
              specularColor 0.0357143 0.0464286 0.189286 1
              emissionColor 0 0 0 1
              shininess 66.175
            } 
```
You see ambient has 0 color contribution. 
osg could be patched and converted into osgb, but that is a bit cumbersome so let's move on.

**DAE** I find the most stable format of them all. I always get the correct transformations, normals and smoothing. And the file format is based on XML format which makes it really easy to manipulate using Python scripting.
So this is the process I ended up using the most:
1. Export model in Blender with following settings:
![image](https://user-images.githubusercontent.com/29146839/132577806-6400bdfe-6542-4e4c-9c64-fa64bec7739c.png)
2. Patch the material using Python script. I added one here: [scripts/fix_dae_materials.py](https://github.com/esmini/esmini/blob/master/scripts/fix_dae_materials.py) as example.
3. Then convert with osgconv.
Like this:
```
c:\tmp\esmini\scripts\fix_dae_materials.py car.dae
osgconv car_fixed.dae car.osgb
```
The following Blender model:
![car2](https://user-images.githubusercontent.com/29146839/132579344-fec05eb5-7c30-4775-bcdf-b896d32da1d9.png)
looks like this in esmini:
![image](https://user-images.githubusercontent.com/29146839/132581276-b60b8066-caca-4824-9d65-28aec5cb0897.png)
Not perfect, but better. And the script can be tuned for own preferences.

And by the way, the wheels works perfect with both fbx and dea. So if you have a model hierarchy like this:
![image](https://user-images.githubusercontent.com/29146839/132579737-5b5276fc-87ff-4307-9ee7-587585bb33e1.png)

Finally, before exporting I usually select all nodes by right clicking on top node and choose "Select Hierarchy"
![image](https://user-images.githubusercontent.com/29146839/132579895-312bb271-902d-4cfa-98fd-cb2c8cec526f.png)
I don't know if that's necessary, but at some point it helped so I do it by habit.

The car you have looks awesome! I hope you will manage to get it into esmini somehow and somewhat OK. And if .obj is needed or desired for some reason, we might find solution for the wheel nodes.

Please let us know how it goes. Especially if you find some good tricks.

**Comment by sterres** [comment]
Thanks a lot for that very detailed information.

I could not find an up to date doe/collada plugin for osgconv. Did you compile it yourself?

The FBX (via osg to osgb) workflow is working and the wheels are turning now.

I will try a bit more next week and let you know the results.

**Comment by esmini** [comment]
If you're on Windows I think it's straight forward. Just make sure to pick the large 3rd party package from here:
https://download.osgvisual.org/3rdParty_VS2017_v141_x64_V11_full.7z
(compare table of contents between small and large package on same page)

And build according to guidelines here:
https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md#build-osg-applications-including-osgconv-and-osgviewer

On Linux I haven't tried all way, but you can build dae/collada as follows:
```
sudo apt-get install libboost-all-dev
git clone https://github.com/rdiankov/collada-dom.git
cd collada-dom
git checkout v.2.5.0
mkdir build
cd build
cmake ..
make -j
```
Libraries should appear in folder dom, install by:
`sudo make install`

Then you should be able to build OSG as:
```
make -j16
make install
```
and run like:
```
cd ..
cd install/bin
export LD_LIBRARY_PATH=../lib:../lib/osgPlugins-3.6.5:../../../collada-dom/build/dom
./osgviewer path-to/your_model.dae

```

**Comment by sterres** [comment]
I chose to stay with FBX as it didn't require to compile osgconv.

In the end, the car model is only for demo/showcasing and has no impact on the simulation results - so don't want to invest too much effort on this.

Here is what I finally came up with (wheels are turning now :) )
![esmin_avl_car](https://user-images.githubusercontent.com/30345042/134911549-2eac893f-3213-47e1-9d83-988b24a260ad.PNG)

Thanks again, for your excellent support 👍

**Comment by eknabevcc** [comment]
Thanks for showing the result - looks amazing! Seems like the normals and materials works perfect, so in this case no need for DAE 👍 
A final touch before closing the issue: If you have two minutes, please try to put the 'shadow_face.osgb' file (part of the release demo packages, or complete [model package](https://dl.dropboxusercontent.com/s/5gk8bvgzqiaaoco/models.7z?dl=0)) in same directory as you car model. Hopefully esmini will pick it up and create a shadow under the car.

**Comment by sterres** [comment]
It worked exactly as you described - cool!

![esmini_shadow](https://user-images.githubusercontent.com/30345042/135040106-f7a54afe-ef8f-4c09-a085-2ba75eeaa530.PNG)

I think we can close this issue - thanks again :)

**Comment by eknabevcc** [comment]
Excellence! :)
