### ISSUE TITLE
Lateral velocity in dat or extended csv?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#156]
Hi,

I would need to see the lateral velocities of the single vehicles, one in local frame of the single vehicle (its real lateral velocity) and one in global coordinate frame or in coordinate frame of ego vehicle (in my case at least regarding y-axis its the same except of an offset that plays no role for velocities, because I'm on straight road).

One additional question here, the rate one defines for lane change is the maximal lateral velocity for the lane change, but this velocity belongs to the coordinate frame of the lane, right?

**Comment by eknabevcc** [comment]
Hi. 
First. We now added velocity to csv_logger (--csv_logger <filename>) in commit e7d51a252f12270ab55197030ea5ec554a97ae5d (on master, but not released yet).

Maybe you wanted to extend .dat file. But we strive to keep that file format minimal (however users can of course extend it as desired for own use cases).

Actually velocity and acceleration in esmini is derived from delta movement, like velX = (Xnew-Xold) / deltaTime. And accX = (velXNew - velXOld) / deltaTime. This is because esmini motion is simple kinematics and not based on accelerations. So from the .dat file content you should be able to calculate Vel and Acc.

And now regarding coordinate system. The Pos, Vel and Acc are all in the global frame. Vel and Acc could be logged in local coordinate system, and we have such need as well. But we decided to skip it and instead calculate them from global Vel and Acc using the orientation heading of the vehicle. It's quite a simple transformation. You can find such calculations [here](https://github.com/esmini/esmini/blob/e7d51a252f12270ab55197030ea5ec554a97ae5d/EnvironmentSimulator/Modules/CommonMini/CommonMini.cpp#L354). This in line with ambition to keep log files small.

This is what we currently can provide. Hopefully you can extend logging on your side for your needs. If you do some modification that you'd like to include in esmini master branch, please let us know and we can discuss.

And yes, the lateral rate for LaneChange should be relative lane, or more precise perpendicular to road reference line.

**Comment by tmIdiada** [comment]
Could you publish a release soon? Is the function Global2LocalCoordinates available in playerbase.cpp, would the follwoing command work there:
Global2LocalCoordinates(pos.GetVelX(), pos.GetVelY(), 0, 0, pos.GetH(), vx_loc, vy_loc)

**Comment by eknabevcc** [comment]
Great news! Good work, that you managed to implement this functionality 👍 

Anyway FYI: The commit adding velocity to csv log is included in release [v2.13.5](https://github.com/esmini/esmini/releases/tag/v2.13.5).
