### ISSUE TITLE
Clothoide xsd changed

### ISSUE THREAD

**Issue by johannesWen** [esmini/esmini#176]
I just noticed, that the xsd schema of the Clothoide class changed in xosc V1.1. The "curvatureDot" attribute is deprecated and replaced by "curvaturePrime". So also the unit of the curvature rate changed.

https://www.asam.net/static_downloads/modelDocumentation/content/Clothoid.html

**Comment by eknabevcc** [comment]
From 2.14.0 (about a month ago) esmini do support both curvatureDot and curvaturePrime. 
What issue did you encounter? Or "hopefully" you're just using an old version...

Regarding the unit. Since curvature is stated in unit 1/m (m referring to radius) I think it makes sense to curvature change rate in 1/m^2. I think the old 1/s referred to that radius is changing as you move along the clothoid. Anyway, to my understanding nothing has in how to interpret the values and calculate the curve. What do you think?
