### ISSUE TITLE
Data to debug

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#179]
Hi,

the cut-in should start at 1.01sec (normally already after 1sec, but due to the gap one should expect 1.01sec). But it starts at 1.02sec, I think the reason is the absolutely non-constant velocity of ego, that should be constant.

Can you check this?

Calculated with newest release:
[test.zip](https://github.com/esmini/esmini/files/7388741/test.zip)

Kind regards,

Thaddäus

**Comment by eknabevcc** [comment]
At simTime == 1.01 the relative distance is calculated as 0.0025556
at simTime == 1.02 the relative distance is calculated as 0.0
Your condition is relative distance <= 1e-06, i.e. 0.000001
So it looks correct that the event triggers at 1.02.

BTW, at timeStep 1.01 the positions are:
Ego: x = 10.5530, y = -8.90000
CutInVehicle: x =15.255555, y = -13.000000
diff is 4,702555 (they have the same geometry and refpoints, so length 4.7 as ref point distance will represent freespace == 0)
And at timeStep 1.02:
Ego: x = 10.6087500 y = ...
CutInVehicle: x =15.2833332, y = ...
corresponding diff is 4,6745832
So also looking at these numbers the distance becomes < 0 at not until 1.02

So, yes, distance calculations looking OK I agree that probably it is the actual positions that are not what you expect. I see that you define timestamps in the trajectory polyline vertices. Perhaps that's resulting in some speed deviation. A suggestions might be to ignore timestamps and use the speed set by SpeedAction instead. Simplest way to ignore timestamps is:
```
<TimeReference>
    <None/>
</TimeReference>
```
I then get the trigger at exactly 1.01. You can try this mod, laneChange is now step and no timeref in trajectory:
[CutIn00001_esminiPP-no-timeref.zip](https://github.com/esmini/esmini/files/7449585/CutIn00001_esminiPP-no-timeref.zip)

Finally, the speed in esmini is only considering longitudinal dimension. So during a lanechange the actual speed would include contribution from the lateral motion as well, and hence be slightly higher than set by SpeedAction. Maybe this is the root cause of the deviation?

**Comment by tmIdiada** [comment]
Sorry completely forgot about the defined trajectory input coming from another simulation software. OK so the error are the time/position values of the defined trajectory. Many thanks for the support.
