### ISSUE TITLE
LaneOffsetAction reverts to "step" dynamics if there is no longitudinal speed

### ISSUE THREAD

**Issue by antoniobruto** [esmini/esmini#180]
When using the lane offset action with a pedestrian, the offset transition is applied as a step change (instantaneous) even when sinusoidal acceleration dynamics are used. I did provided a low (<0.5) maxLateralAcc for the LaneOffsetActionDynamics.

**Comment by eknabevcc** [comment]
Yes, this is a bit tricky. I understand your approach and expectations. However, in esmini the lateral actions LaneChange and LaneOffset assumes longitudinal motion as well. It's like a trajectory being calculated, and if the entity reduces speed to 0 during the lane change it should also come to a stop, not sliding sideways.

Anyway, I have two alternative suggestions:
1. Set a low dummy speed. Instead of
`<AbsoluteTargetSpeed value="0"/>`
set
`<AbsoluteTargetSpeed value="0.01"/>`
2. use a trajectory instead.

See attached two examples.
[cross-road-examples.zip](https://github.com/esmini/esmini/files/7451321/cross-road-examples.zip)

**Comment by antoniobruto** [comment]
Thanks Emil. I guess this would have to do.
