### ISSUE TITLE
Road manager library crashes with xodr (paramPoly3 and junctions)

### ISSUE THREAD

**Issue by mpfist-no** [esmini/esmini#192]
Hello!

I am trying to initialize the esminiRMLib.dll using the C# wrapper (version 2.17.4) with the attached xodr ([JunctionESMINI.zip](https://github.com/esmini/esmini/files/7602800/JunctionESMINI.zip)). However, the program crashes in the Init-call without throwing an exception.
Opening the file with the odrviewer.exe results in "stof argument out of range".

Could you please look into this?

Thank you!

**Comment by eknabevcc** [comment]
Thanks for report. Yes, you stumbled on a bug, floating numbers in the OpenDRIVE file was converted to float (32 bit precision) instead of the correct double type (64 bit). It should now be fixed by commit 3393bdfd90cf7aca0a67d94511865260870a6cb3. 

It will be part of next release. Let us know if you need a release immediately.

Regarding the root cause: I wondered what numbers where causing this exception. In your OpenDRIVE file I found extreme t-values for some objects. For example:
Object "permanentDelineator" at `t = "-1.1974918543775567e+128"`
which is -1.2 x 10^128 meters which is an incredible distance :) one lap around earth is about 4e+7 meters. Nonetheless, I'm glad you found the flaw.

**Comment by mpfist-no** [comment]
You are right, -1.2 x 10^128 meters is definitely not what I intended to have in my OpenDRIVE file. Thank you for looking into this. I need to investigate this further, as well.

When are you planning to release the next time? I would be very happy to have this fix available within the next week, if this is possible. :-)

**Comment by eknabevcc** [comment]
Included in release [2.17.5](https://github.com/esmini/esmini/releases/tag/v2.17.5)

**Comment by mpfist-no** [comment]
Thank you very much for your help!
