### ISSUE TITLE
Trouble with large slope

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#197]
I have experimented with elevation and built a track with large slope:
[example.zip](https://github.com/esmini/esmini/files/7723458/example.zip)
However, it seems esmini somehow gets stuck with this on the slopes. @eknabevcc can you confirm that this is a bug or otherwise tell me if I did something wrong?

**Comment by johschmitz** [comment]
I have also noted when I press O the plotted OpenDRIVE seems to be a bit off:
![image](https://user-images.githubusercontent.com/771979/146281459-a6ac831f-6974-4152-a6aa-53c5725c9ce8.png)

**Comment by eknabevcc** [comment]
Oops, that was ugly performance from esmini. Thanks a lot for reporting this bug! Incredibly the pitch has been wrongly calculated for long time as the slope instead of arctan of the slope. 

Now it's fixed (commit 7379a83f4afa8216437706435d25296848ce3a33), and a few other tessellation related issues (d2795f379755d29a51b0ca1d09a16858ec3357ba and 0561c7df002ee7a4c31cdcc0a57ca3e393ebc50f) that your challenging example reviled. 

It's being merged on master. And will be part of next release.

https://user-images.githubusercontent.com/29146839/146443742-d21740e6-a848-41ef-a811-2e91e57f0053.mp4

BTW: I replaced WorldPosition with LanePosition to attach vehicles to the road perfectly. (WP will set default value=0 for all orientation values not explicitly specified, so e.g. pitch will be zero and not aligned with any road pitch. While LanePosition assumes that alignment with road orientation is desired. But this is another story...). 
[bdsc_export_LP.xosc.txt](https://github.com/esmini/esmini/files/7730225/bdsc_export_LP.xosc.txt)

https://user-images.githubusercontent.com/29146839/146443811-17d037b0-a866-4c78-b315-7a52f03b4df2.mp4

Video shows improved tessellation, taking roll and pitch change rates into consideration.

**Comment by johschmitz** [comment]
Great! I am gonna try out the new release.
I have one question though, maybe you know @eknabevcc: I always wonder what happens/is supposed to happen to the dashed/broken lane markings when the road has a strong slope. Since they are somehow defined in terms of plan view (2D), are they supposed to become shorter in 3D on the slope (projection)? Or do we have to apply some kind of correction function to account for that effect based on the elevation polynomials? Would you know where to find the equation for that?

**Comment by eknabe** [comment]
Good point. I actually don't know how to deal with roadmarks, if compensating for slope or not. I would guess that they are defined in terms of road s- and t dimensions, and hence actually independent of slope (elevationProfile). The good thing is though that usually the slope is modest, not like in you roller-coaster example :), which makes the error probably neglectable.

Anyway, I stumbled on the same issue when updating code for tessellation. Not sure if it's the best or correct way, but this is the factor that will adjust the resolution of polygons for slope:

![image](https://user-images.githubusercontent.com/44489094/146758913-c6835ead-c8f0-4c9d-bff7-8ee70a490c70.png)

The idea is to find the factor of how longer the sloped (k is given) distance (z) is compared to projected on ground (x, s in osc/odr), and then invert it for denser tessellation. Here's the equation:
https://www.wolframalpha.com/input/?i=x%2Fz+where+z%3Dsqrt%28x%5E2%2By%5E2%29%2Cy%3Dk*x

**Comment by eknabe** [comment]
A whiteboard would be 👍 
This is how it works for tessellation: The slope is simply the derivative of the polynomial, i.e. slope = dz/ds. It's then used to scale the step-length. So you're right, it's a bit of simplification since during the step forward the slope might change. But for road surface the change is not expected to be too crazy, so I think this method is perfectly OK for both triangulation and roadmarks.

**Comment by eknabe** [comment]
Just to clarify: The tessellation is first of all dependent on the second derivative, i.e. the rate of which the road surface bend vertically (similar as for horizontal bending). The Z-slope is just an additional factor to compensate for step-length which is always in the s-dimension. 

A whiteboard would be 👍 
This is how it works for tessellation: The slope is simply the derivative of the polynomial, i.e. slope = dz/ds. It's then used to scale the step-length. So you're right, it's a bit of simplification since during the step forward the slope might change. But for road surface the change is not expected to be too crazy, so I think this method is perfectly OK for both triangulation and roadmarks.

Finally regarding propagating error. When it comes to tessellation it doesn't matter, after all the goal is just to find a reasonable resolution. And I think it's the same for roadmarks for many use cases. I mean the error for a roadmark length would probably be in mm range. But it depends on the use case of course.

BTW, when I revisited this issue I found an error in the equation image (k^2-1 instead of correct k^2+1) - it's fixed now.
