### ISSUE TITLE
Is it possible to pause the simulation?

### ISSUE THREAD

**Issue by mschneider1711** [esmini/esmini#209]

**Comment by eknabevcc** [comment]
Now it is :)

Included in release [2.19.2.](https://github.com/esmini/esmini/releases/tag/v2.19.2)
space: toggle pause/play 
return: step (forward)

Thanks for the "push". Please test and report if it works as expected.

**Comment by mschneider1711** [comment]
It works just fine. Thank you for the addition :)

**Comment by mschneider1711** [comment]
Maybe you could also add this information to the help menu, which is shown when pressing "h" on the keyboard 👍

**Comment by eknabevcc** [comment]
Actually, esmini help is on "H" (shift - h), only OSG stuff is shown on "h". I know it's a bit strange, but it's a compromise since we want to keep OSG default help shortcut. Anyway, the "H" esmini help was updated for the release.

Then we also have the [readme.txt](https://github.com/esmini/esmini/blob/master/docs/readme.txt). Unfortunately, because of a mistake from my side, it was not updated correctly for the release. But now I is.
