### ISSUE TITLE
Overriding TrajectroyAction will cause a spiked error in the velocity and acceleration.

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#216]
Overriding by another TrajectroyAction while using a TrajectroyAction will cause a spike in velocity/acceleration.
I'm using self-build version at 63340df

For example, this is a scenario where a clothoid TrajectroyAction overrides a straight TrajectroyAction.

[trajectory_or.xosc.txt](https://github.com/esmini/esmini/files/7923540/trajectory_or.xosc.txt)
* The vehicle is moving at 5 m/s by SpeedAction at init 
* Both trajectories have a TimeReference of None.
* At the t=2(The x-axis of the graph = 200.), an override occurs.

![image](https://user-images.githubusercontent.com/5919566/150740285-4f89931d-9b9e-465f-9808-045470509cd1.png)
![image](https://user-images.githubusercontent.com/5919566/150740292-14b69212-5fe7-4211-9113-60250387ec80.png)

[trajectory_or.csv](https://github.com/esmini/esmini/files/7923542/trajectory_or.csv)

**Comment by eknabevcc** [comment]
Very good finding. If the manuevers/events/actions were in the same act there would be no spike. The explanation is that acts were evaluated and stepped one by one. So an event in act1 would step even if it was to be cancelled by a conflicting event in act2. Now we changed so that the whole story will be evaluated before being stepped. That way a cancelled event will never be stepped the very same timestep.

The fix (commit f97c8fe7f40ded26d086454f7a1cbc02abbc9962) is merged on master and will be included in next release.

Now your scenario looks like this, for me:
![image](https://user-images.githubusercontent.com/29146839/150940329-95a46688-b05f-4d57-adb8-e1fc115c03a3.png)

Please test and report if you get same result or not.

Thanks again for good report with clear description and a scenario making it easy to reproduce.

**Comment by bleach31** [comment]
I confirmed the fix in v2.20.3.
Thank you for your prompt response. 🙇 🙇 🙇
