### ISSUE TITLE
Actions with conditions that are met at the same time do not make conflict

### ISSUE THREAD

**Issue by bleach31** [esmini/esmini#218]
I will explain with concrete examples

[severe_timing.xosc.txt](https://github.com/esmini/esmini/files/7926312/severe_timing.xosc.txt)

There are three actions in this scenario

* Act1Maneuver1Event1Action1
　* t=1 Start acceleration
　* t=3 Reaches 2.778m/s
* Act1Maneuver1Event2Action1
　* Act1Maneuver1Event1Action1 == endTransition Start deceleration
　* Reaches -5.556m/s after 3 seconds
* Act2Maneuver1Event1Action1
   * 1.98 seconds after Act1Maneuver1Event1Action1 reaches runningStatus, Start acceleration
   * Reaches 8.3333m/s after 2 seconds

This scenario is designed so that the start of Act1Maneuver1Event2Action1 and Act2Maneuver1Event1Action1 are executed only one step apart.

Then, run in fixed steps of 0.01 as follows
```
"../bin/esmini" --window 60 60 1024 576 --osc severe_timing.xosc --headless --fixed_timestep 0.01 --csv_logger "severe_timing.csv"
```

[log.txt](https://github.com/esmini/esmini/files/7926317/log.txt)
[severe_timing.csv](https://github.com/esmini/esmini/files/7926318/severe_timing.csv)

This is a diagram of the log.txt file.

Act2Maneuver1Event1Action1 should be overwritten by Act1Maneuver1Event2Action1, but there is no conflict message.

![image](https://user-images.githubusercontent.com/5919566/150803105-79422609-0f2d-4a99-adc8-24ef4dc64f14.png)

This is a plot of the CSV.First, Act2Maneuver1Event1Action1 is enabled and takes 2 seconds to 8.3333m/s.After it is finished, the action switches to Act1Maneuver1Event2Action1. Act1Maneuver1Event2Action1 takes 1 second to reach -5.556m/s.

![image](https://user-images.githubusercontent.com/5919566/150802532-c25a3cda-4892-45a3-b44f-957b4f458790.png)

**Comment by eknabevcc** [comment]
This is strange, but maybe not.
You run a version (63340df62b3c52df270197eda45930a93116af44) from Jan 23 which is prior to the magic fix of f97c8fe7f40ded26d086454f7a1cbc02abbc9962 (Jan 25) addressing your issue #216.

So before diffing further, could you try the same scenario in latest version , at least >= 2.20.3? Maybe the root cause is something else, but just to narrow "search space".

**Comment by DNMotoShiba** [comment]
Thank you for your comment.
Sorry for reporting on an old version.
I re-test at 2.20.4.

The logs look a bit different now.
[log_2.20.4.txt](https://github.com/esmini/esmini/files/7982887/log_2.20.4.txt)
this is diagram making from log file.

Act1Maneuver1Event1Action1 is conflicted, but Act2Maneuver1Event1Action1 is not, as before.

![image](https://user-images.githubusercontent.com/23490530/152077285-ec5df974-34ce-4134-a42d-d522d75bc5f6.png)

Plotting the speed in CSV, Act2Maneuver1Event1Action1(Reaches 8.3333m/s) is not actually conflicted.

![image](https://user-images.githubusercontent.com/23490530/152077404-b62f9e1c-36e9-47a0-b496-9d8489e7e58e.png)

**Comment by eknabevcc** [comment]
Thanks for your attention to details and clear report again. This is another corner case which I'd like to solve.
I found one potential root cause, resulting in one frame delay when evaluating for conflicting actions.
Commit 24bcac483148cb26136e53198306391ed88398eb fix that. It's merged on master and will be included in next release.

For me it now looks like this:
![image](https://user-images.githubusercontent.com/29146839/152192438-6a053964-411b-4a85-bc66-03111ac58d0f.png)

I'm not 100% sure if this is expected and/or correct. So please test on your side and report your finding.

**Comment by DNMotoShiba** [comment]
Thank you so much.
I used 2.20.5 to check.
It works perfectly!

**Comment by bleach31** [comment]
Thank you so much.
I used 2.20.5 to check.
It works perfectly!
