### ISSUE TITLE
Trajectory following heading issue

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#226]
After adding the sequence of initial actions you recommended in another issue in order to go from world to road coordinates and follow the current lane, now the trajectory following does not work properly anymore (see example)

[example.zip](https://github.com/esmini/esmini/files/8010284/example.zip)

I wonder if that is an esmini bug or probably intentional and I will have to add some extra actions?

**Comment by johschmitz** [comment]
At the moment I just don't get why it was working before and now it doesn't work anymore/works differently, guess I'll have to revert back to some old versions and compare and then follow up on this discussion.

**Comment by eknabevcc** [comment]
As already stated above, the behavior is the expected. Since you make use of the absolute position also orientation is well defined regardless of explicitly stated or not (default is zero if not specified) - see link to standard in my last comment.

It may very well be that esmini behaved differently in some old version. In this specific case I think the explanation is found in the specification of WorldPosition. In OpenSCENARIO version 1.0 there was no statement of default value in case of missing values. That was added in version 1.1. 

So to conclude, if you need to work with world positions, then simply specify desired heading as well. Or check the provided example (in last comment) where we outline a potential approach using relative WorldCoordinates - handing over heading calculation to esmini. (But I suggest to go for relative road/lane coordinates or fully specified WorldCoordinates).

**Comment by johschmitz** [comment]
I tried it out with an old version of my tool and the behavior of esmini seems to have changed indeed. Esmini used to follow the trajectory with the vehicle heading always exactly following the trajectory heading which does not seem to be the case anymore. If world positions are used in a trajectory should the heading not be extracted from the heading resulting between two trajectory points? I tried it using the NURBS trajectories and there it still works even though I also just specify x, y and z and it would be quite impossible to calculate the tangent values at arbitrary points so this does not appear to be consistent to me.
I appreciate the possibility to additionally specify the heading for Polyline trajectories to override the default behavior but the default behavior should still be pointing into the tangent direction of the trajectory as it was before.

**Comment by johschmitz** [comment]
Here is the example with Polyline and NURBS:
[example.zip](https://github.com/esmini/esmini/files/8055724/example.zip)

**Comment by eknabevcc** [comment]
Sorry if I'm not clear. The WorldPosition do set the heading, regardless if specified or not. Please see v1.1 of the standard (link above). So if you specify vertices with WorldPosition the heading is bound to be set as well. And this is a good thing, because it makes it possible to explicitly set the heading at key points. I really don't see a big issue here because it's really simple for a user to calculate the tangent for a polyline. 

It's true that Nurbs behaves differently. The reason being, as you're touching upon, that it's hard to specify a correct tangent/heading for the control points. So in my book it is the Nurbs case that is deviating from expectation (for fairly good reason).

I don't think it's a good idea to ignore the heading when polyline is specified with world positions (remember that heading = 0 if omitted). For the simple reason that the user might want to explicitly set it.

To me the simplest way out for you is to simply specify the heading as well in the WorldPosition. Or provide a concrete suggestion how to modify behavior in esmini without deviating further from the standard. 

Other than that, it's not much I can do, hence I suggest closing the issue.

(it could be that the standard could improve on this end, but that's another topic I think)

**Comment by johschmitz** [comment]
Alright then, good that we talked this through. I now have the full picture again and agree this is an acceptable behavior/default. So I will do the calculations on my end and add the headings in order to fix this. I guess this can be closed then.

**Comment by johschmitz** [comment]
So I have one last question regarding this after fixing it.
I was trying to add an additional action after the follow trajectory action to make the car turn back into the direction of the road:
```
# After trajectory following get pitch and roll from road
init.add_init_action(car_name,
    xosc.TeleportAction(
        xosc.RelativeRoadPosition(0, 0, car_name,
            xosc.Orientation(p=0, r=0, reference=xosc.ReferenceContext.relative))))
# Center on closest lane
init.add_init_action(car_name,
    xosc.RelativeLaneChangeAction(0, car_name,
        xosc.TransitionDynamics(xosc.DynamicsShapes.cubic,
                                xosc.DynamicsDimension.rate, 2.0)))
```
But it seems to not work as I would have imagined. Is that not possible?

See example
[example.zip](https://github.com/esmini/esmini/files/8056448/example.zip)

**Comment by eknabevcc** [comment]
Yes, you're thinking is correct. Just that the FollowTrajectory action and aligning Teleport action need to be in a separate events, so that the Teleport can be trigged after the follow trajectory event is done. Currently all actions are specified in the Init section which will launch them all at once.

See the modified scenario (bdsc_export-mod.xosc.txt) in my first answer above. It puts the FollowTrajectory and Teleport in separate Storyboard events. It also shows how you can specify relative WorldPositions with omitted Orientation and hence have esmini calculating the heading - even though I think your latest scenario is a good approach, you having full control of the heading 👍

**Comment by johschmitz** [comment]
Alright I am going to add more sophisticated maneuver groups and acts later.
Meanwhile I am still a bit confused. Is esmini interpolating between the specified angles of the polyline trajectory? It looks quite strange to me. I thought I would be specifying the heading for the next section of the polyline but that does not seem to be the case?

**Comment by johschmitz** [comment]
I guess interpolation of the angles is okay but it needs to be done from the middle of the segment to the middle of the next segment? Or maybe I have to change my angles accordingly so that when the vehicle is on top of one of the points it does not point into the direction of the next point? But then for a zigzag pattern I think the heading would not change at all? So maybe I need to specify more samples? Kind of not violate the Nyquist theorem? Is there any documentation around this how this is supposed to work? Or maybe we could videochat a bit about this topic if you are interested..

**Comment by eknabevcc** [comment]
There are a few examples making use of trajectories. For example:
https://github.com/esmini/esmini/blob/master/resources/xosc/pedestrian.xosc
https://github.com/esmini/esmini/blob/master/resources/xosc/trajectory-test.xosc

This is how esmini will treat polylines:
- If heading is specified in the vertices: Heading will interpolated between vertices. Simply to smoothen the motion.
- If heading is not specified (like relative positions lacking Orientation element): Constant heading will be calculated for each segment. However it will be interpolated close to the vertices to avoid discontinuities.

For sure there will be use cases that would prefer different behavior. But the above has simply been useful for needs and use cases so far. 

After all, polyline is not the recommended shape type to describe vehicle motions. For curved motions you typically need to add many short segments, in which case the interpolation will be a good feature by the way. Nurbs is typically a better choice for fewer control points.

**Comment by johschmitz** [comment]
Alright, I get that the solution to this problem is to specify the angle in each point based on the average of the angles of the segments located before and after it. 

What I don't get is why I can not use the world position and get the behavior you describe in point 2. What is the use case for always setting all headings to 0 when not specified? You say it now has to be like this to follow the standard but does it ever make sense? If I really want the angles to be constant 0 that is quite easy to set them to 0. How can I emulate that simple trajectory following behavior now, where it exactly follow the line in a tangential manner in each point? Did it simply become impossible to do that with world positions? In my opinion the old esmini behavior was just more useful and I see nothing gained through the change. I hope at least someone gained some advantage through it..

**Comment by johschmitz** [comment]
So it does work for me for heading only :+1:  but I can't seem to get it working with heading and pitch. The pitch seems to somehow influence the heading which I don't see how that can be possible.
Here are two examples for comparison:
[example.zip](https://github.com/esmini/esmini/files/8074751/example.zip)

**Comment by eknabevcc** [comment]
First: Pitch and roll is not handled by trajectories so they should be 0 or just leaved out. Instead pitch and roll will be aligned to the road.

Then regarding use cases. Sometimes it's easier to just show than trying to explain. Here follows a few examples:

1. One common (the most common according to my experience) use case is to approximate a recorded trajectory. Typically data consist of sample points (x, y or lat, long). The most simple way to convert such data to OpenSCENARIO for use in simulation is to generate a PolyLine trajectory. Typically the data is dense. And for PolyLine some degree of density is desired to get decent smoothness. Without heading interpolation it may look something like:

https://user-images.githubusercontent.com/29146839/154308454-fe8d6fc8-6fcc-4023-af47-77a0e75d4a6c.mp4

[run1.xosc.txt](https://github.com/esmini/esmini/files/8081605/run1.xosc.txt)

adding simple heading interpolation we get not only improved numerical continuity but also smoother looks:

https://user-images.githubusercontent.com/29146839/154311454-b5dd4232-f69b-4437-afcf-31bcdade9428.mp4

[run2.xosc.txt](https://github.com/esmini/esmini/files/8081620/run2.xosc.txt)

2. If data is sparse (for some unlucky reason), you can use relative positions and leaving out Orientation altogether. esmini will follow the straight parts but add some interpolated heading to smoothen the corners:

https://user-images.githubusercontent.com/29146839/154311840-a2434a1b-dbfe-4166-864e-2f3e95d82e02.mp4

[run3.xosc.txt](https://github.com/esmini/esmini/files/8081644/run3.xosc.txt)

3. Better approach is to try making use of nurbs. Here is same 12 points as previous example but used as control points for a nurbs of order 4:

https://user-images.githubusercontent.com/29146839/154316701-02bb818b-25a0-4a4c-a8f2-3e42a3d8c666.mp4

[run4.xosc.txt](https://github.com/esmini/esmini/files/8081703/run4.xosc.txt)

Compared to first two runs we get perfectly smooth motion in spite having only 12 points compared to 80 in first two runs (in real case you'd often need denser for plines). The curve do not interpolate the control points (since order > 2). So there is some extra work remaining if interpolation is needed. For other use cases, like interactively drawing a trajectory I think Nurbs can be excellent.

But the nice thing with nurbs is the flexibility. Here's one example where we take down order to 2. And now it's very similar to a polyline. (the cool thing is that a nurbs can vary the characteristics of interpolation shape at each control point/segment with weights and knots.)

https://user-images.githubusercontent.com/29146839/154317605-a7f9b7b4-9e84-44a2-b72d-1930ae180148.mp4

[run5.xosc.txt](https://github.com/esmini/esmini/files/8081722/run5.xosc.txt)

4. And then of course we have the clothoid trajectories, ehich are very useful because a clothoid can be either of:
  - spiral
  - arc
  - line

here's an example of lane change trajectory combining two arcs (clothoids) with a straight line (clothoid) in between.

https://user-images.githubusercontent.com/29146839/154316365-6ed07bab-759e-43b9-a7a6-3c158f0bf5ee.mp4

https://github.com/esmini/esmini/blob/master/resources/xosc/lane-change_clothoid_based_trajectory.xosc

**Comment by johschmitz** [comment]
Alright so I am going to leave out the pitch.

Very nice examples! I wonder why don't you create a YouTube video explaining lots of different examples like these? That would be awesome!

**Comment by eknabevcc** [comment]
Yes, that's a good idea. Also to push some kind of written user guide (which is even more prioritized I think). The user guide could refer to or include some video clips...
Only lack of time stands in between :) 

Closing issue for now.

**Comment by eknabevcc** [comment]
For reference:

1. User guide embryo available: https://esmini.github.io/

2. From v2.24.0, [FollowTrajectoryAction](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/FollowTrajectoryAction.html) with [followingMode](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/FollowingMode.html) `follow` will calculate and interpolate heading in case heading is not explicitly set (in a way the `follow` mode gives some flexibility which we took advantage of here). I think this could fit your use case. See [for v2.24.0 release notes](https://github.com/esmini/esmini/blob/master/release_notes.md#2022-07-06-version-2240).
