### ISSUE TITLE
Lane offset not taken into account

### ISSUE THREAD

**Issue by hbanzhaf** [esmini/esmini#234]
I attached a simple OpenDRIVE map that includes a lane offset.
Placing a vehicle, e.g., at
```                           
<RoadPosition roadId="68" s="8.500184411391103" t="0.0">
    <Orientation h="0.0" p="0" r="0" type="relative"/>
</RoadPosition>
```                           
leads to the following result:
![bug](https://user-images.githubusercontent.com/9086412/153761029-12e3b44a-6878-4d9a-a4d9-e22cbe0b7585.png)

However, the OpenDRIVE viewer says that this road position lies at the location of red cross in the following image (see text on the bottom):
![odr_viewer](https://user-images.githubusercontent.com/9086412/153761258-d4049a86-9195-4496-aab9-a6daf9592f4f.png)

So it seems that esmini is not correctly taking into account lane offsets. What do you think?

[example_map.zip](https://github.com/esmini/esmini/files/8055955/example_map.zip)

**Comment by eknabevcc** [comment]
esmini is taking laneOffset into account in all calculations. But I think it is interpreted differently as you have correctly noticed.

In odr viewer it seems that it "only" moves the reference line. While in esmini the reference line AND all other lanes are moved accordingly.

In the simplified example below you see a vehicle at s=3, t=0 and laneOffset = 1.2. The actual y coordinate becomes 1.2, indicating that the lanes is moved according to the laneOffset (otherwise t=0 would result in y=0). 
![image](https://user-images.githubusercontent.com/29146839/154140514-6cc4f014-a2f5-4c12-9b66-694e6c4a8100.png)
[example_map2.xodr.txt](https://github.com/esmini/esmini/files/8074317/example_map2.xodr.txt)

So far I don't think we had any issues as result of this difference. If/when that happens we might need to adjust. Until then I don't think we will prioritize any change. Meanwhile, if you or someone else really need it, you could try implement the change and create a pull request that we'll consider. 

For curiosity, what problem have you experienced as a result of this difference? Of course, one could be that scenarios will differ between simulators. In that case what simulator tool did you compare with?

**Comment by hbanzhaf** [comment]
Hi Emil,
Thanks for your quick reply. To my mind, the [ASAM standard](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-05e95dfd-ce05-40c8-af93-d065229e6968) says that the lane offset only shifts the center line but leaves the reference line at the place where it is defined in the `<planView>` of the OpenDRIVE map. I think the OpenDRIVE viewer implements this convention while esmini deviates from it.
Other simulator tools: e.g. VIRES VTD.

**Comment by eknabevcc** [comment]
Yes, I agree that shifting the centerline alone is the correct interpretation as you say.

I'm quite sure that we'll come to a point where we'll need to fix it. Until then it's hard for us to prioritize that effort since I assume it will be more than just a few hour of implementation. Unfortunately. 

Since we don't have a time plan for this fix we'll need to consider this a deviation or limitation in esmini. 

I close the issue for now. We can re-open if we or someone else starts implementation.

**Comment by everal33** [comment]
Hello. I just wanted to acknowledge the same effect as mentioned by  @hbanzhaf : I noticed a discrepancy between esmini and the OpenDRIVE standard when it comes to the shift of lanes by setting a lane offset and the reference line for the s,t-coordinate system
In my case, I noticed the discrepancy when placing objects on a road segment shifted with lane offset.

@eknabevcc 
Surely, I do not expect that my additional inquiry creates the critical mass to re-open this issue. But I thought it is worthwhile to let you know for your consideration.
