### ISSUE TITLE
Headless esmini gets "stuck"

### ISSUE THREAD

**Issue by cfschaller** [esmini/esmini#235]
Hi Emil,

wanting to verify that issues #212 and #229 are fixed, I ran into this one. 
We are unable to test the new release in our environment (headless esmini), because esmini regularly gets completely stuck - typically on the first SE_StepDT after a new SE_Init. I've narrowed this down to commit a1a6b6c5bf08d1c50aedfd6e43dbfe5f140ea421 by using local builds.

For reference, the workflow is once again very simple (and not using any ghosts):
- SE_Init (..., 1,0,0,0)
- loop with SE_StepDT and SE_GetObjectState for SE_GetNumberOfObjects
- SE_Close() 

Do you need any further information? 
If necessary, I can also try to look into this further myself.

Thanks again for all your efforts,
Christoph

**Comment by eknabevcc** [comment]
Thanks for info!
Would it be possible to test again with latest master? 
Commit 2056010a579c9387785e6fa652179313d86f782e fix one issue unfortunately introduced in latest release. Probably it's not related to the issue you found, but just to narrow down investigation it would be good to know.

By the way, two questions:
1. Does the freeze happen always or sometimes?
2. If sometimes, Are the runs identical, i.e. do you run with fixed (same) dt every step and run?

**Comment by cfschaller** [comment]
Hi Emil,
I justed tested with the latest master - as you assumed, the issue is still present.
Answering your questions:
1. The freeze does happen "sometimes" - it does not have to be after the first SE_Init, but might as well the third or fifth. However, it is always the first SE_StepDT after a new SE_Init that gets "stuck" and never returns.
2. Yes, we always use the same fixed dt of 0.01 .

**Comment by eknabevcc** [comment]
First two follow up questions: 
1. Does it ever get stuck on first run, or is it always at second SE_Init or later? 
2. OSI involved?

Then: I added a simple code example that I run trying to reproduce the issue. But it never get stuck for me (Windows 10 and virtual Ubuntu 20.04). It would be great if you could run it and check whether it get stuck on your side. And we can progress from there (e.g. modifying the code until it get stuck on your side, and I can try to reproduce it).

It's in branch [issue_235](https://github.com/esmini/esmini/tree/issue_235) and is found in folder:
[EnvironmentSimulator/code-examples/issue_235](https://github.com/esmini/esmini/tree/issue_235/EnvironmentSimulator/code-examples/issue_235)

Simplest is probably to checkout the branch and build it all. And then put yourself in code-examples-bin folder, and run:
`./issue_235`

**Comment by eknabevcc** [comment]
There is a new release: [v2.20.7](https://github.com/esmini/esmini/releases/tag/v2.20.7)

It includes some minor code fixes, e.g. adjusting a few comparison operations. It's a real long shot, but the freeze could potentially be related to comparison going "wrong" due to floating point precision.

Also it introduces a new clear strategy how to identify object for all query functions in the esmini lib API. Previously it was a mix of object_id and index. Now all functions expect object_id as parameter. See [release notes](https://github.com/esmini/esmini/blob/master/release_notes.md) for some more info.

I think it would be interesting if you could quickly test this version. Let's say it's 5% chance...

**Comment by cfschaller** [comment]
Hi Emil,

I finally found the time to look into this one again with enough time to conduct several tests.
First off, no luck with the new release v2.20.7  - it does not fix the issue.

However, I have now narrowed the issue down and found the decisive difference between our setups. We actually use SE_InitWithString instead of SE_Init (sorry! I never thought that would make a difference.).

If now in your example one
- adds SE_AddPath("../resources/xodr") 
- and replaces SE_Init("../resources/xosc/cut-in.xosc", 1, 0, 0, 0) by SE_InitWithString(contents of cut-in.xosc, 1, 0, 0, 0)

I can reproduce the issue 100% of the time.

Can you please check whether you can reproduce the issue now?

Thanks,
Christoph

**Comment by eknabevcc** [comment]
Yes! Many thanks for persistence and finding the key input for the issue to happen. Finally we could reproduce and quickly find the bug.

The root cause was in the recently introduced modes of ghost operation. For the case of xml string input the mode wasn't initialized. 

Now we aligned all initialization and made a common init method to avoid similar flaws in future (commit a07796ab577dab14ce3b5a34ff85027748e2eaf6)

Please test master or new release [v2.20.8](https://github.com/esmini/esmini/releases/tag/v2.20.8).

BTW: I added a code-example for initializing with XML string: [code-examples/init_with_string](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/init_with_string)

**Comment by cfschaller** [comment]
Amazing! The new release works like a charm. :)

Thanks for all your support!
