### ISSUE TITLE
ManeuverGroup  maximumExecutionCount

### ISSUE THREAD

**Issue by hee0624** [esmini/esmini#269]
hi~ when I try ManeuverGroup  maximumExecutionCount is 5, but not work。 The maneuvergroup's state is standby ,when act trigger is true and maneuvergroup run one time. thx~

**Comment by eknabevcc** [comment]
Indeed, you're right. This was a flaw or at least a limitation in esmini.
It should now be fixed by commit ee0d79eda8468fb31bfeae6149275272e340628a.
And included in release [2.22.1](https://github.com/esmini/esmini/releases/tag/v2.22.1).

Please test and report if it works as expected or not.

**Comment by hee0624** [comment]
thx~,it works.

**Comment by qqkkwan** [comment]
Hi,
   I set ManeuverGroup maximumExecutionCount 5，but not working ,am i wrong?
  Esmini Version:  v2.26.1
  Test file: cut-in.xosc
  Operation: set ManeuverGroup maximumExecutionCount="5" and run .\bin\esmini.exe --window 60 60 1600 800 --osc .\resources\xosc\cut-in.xosc
  Result: Esmini run on time as same as i set maximumExecutionCount="1"

**Comment by eknabevcc** [comment]
I understand your expectation, that the complete scenario should be restarted and run over again.

But, at least according to esmini interpretation, the maximumExecutionCount only controls how many times the maneuverGroup can be triggered (as part of an act, which actually has the trigger). 

Further, there is no automatic reset or re-initialization of entities when a maneuverGroup is re-executed. Just allowing for the nested maneuvers (and events, actions...) to be triggered and executed again.

To demonstrate an example I modified the original [lane_change_simple.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/lane_change_simple.xosc) so that the complete maneuverGroup is executed three times. Note that the maneuverGroup includes a teleportAction that takes the car back to start position after reaching end-of-road.

Here's the modified scenario:
[lane_change_simple-mod.xosc.txt](https://github.com/esmini/esmini/files/9484230/lane_change_simple-mod.xosc.txt)

To speed up a but you can run as: 
`./bin/esmini --window 60 60 800 400 --fixed_timestep 0.1 --osc ./resources/xosc/lane_change_simple-mod.xosc`

Does it makes sense, or do you have another understanding? Perhaps you've seen a different behavior in another simulation tool?

**Comment by qqkkwan** [comment]
I get it.，thank you !
