### ISSUE TITLE
The delay time in condition is not correct  when use API to run esmini.

### ISSUE THREAD

**Issue by jurriya** [esmini/esmini#270]
The delay time in condition is not correct  when use API(SE_StepDT) to run the esmini.
But the issue is only happened when the fixed_timestep = 0.005s.
When  fixed_timestep = 0.001s ,the issue will not happen. 
Could you help to see is this an issue or another problem. Very thanks. 

![image](https://user-images.githubusercontent.com/53253020/162946585-83eeff34-1c7f-41b1-a9e1-b202970758d0.png)

[demo-for-esmini-test.zip](https://github.com/esmini/esmini/files/8472300/demo-for-esmini-test.zip)

**Comment by eknabevcc** [comment]
Very good finding! Thanks for detailed report with files for reproduction of the issue.

The problem is related to floating point precision. Internally esmini is using double (64 bit) while for esminiLib interface we use float (32 bit). It could be discussed whether to change that to double as well, there are some pro and cons.

Anyway, esmini is applying a tolerance for most comparison operations. By increasing that tolerance I think we can avoid the problem. Such fix is done by commit 70231eeef49d43138e07ae4c41a366f6addeeae7.

It's included in release [2.22.1](https://github.com/esmini/esmini/releases/tag/v2.22.1).

Please test and report if the behavior is improved or not.

**Comment by jurriya** [comment]
The issue have been solved by release [2.22.1] . Thank you again.
