### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by Violin9906** [esmini/esmini#285]
I'm trying to build a simulator based on ESMINI for Reinforcement Learning. But when I run it for thousands times, it run out of all my memory. I wrote a little program to show this issue:
```c++
#include <iostream>
#include <fstream>
#include "esminiLib.hpp"

using namespace std;

int main() {
    std::ifstream t("../resources/xosc/cut-in.xosc");
    std::string str((std::istreambuf_iterator<char>(t)), std::istreambuf_iterator<char>());
    SE_InitWithString(str.c_str(), 0, 1, 0, 0);
    while (time--) {
        SE_StepDT(0.01f);
    }
    SE_Close();
}
```

when I check it with Valgrind, it reports a lot of memory leaks. For your reference, you can find the output here:
[Valgrind output](https://gist.github.com/Violin9906/91dfcf8e07db2ef5799c888359d0c4d5)

The esminiLib is compile form commit 9951aa6172e72a4939cb40acd5dd5bfda4ee955f, which is the latest when I report this issue.

**Comment by eknabevcc** [comment]
For our understanding, how do you use the lib: Do you re-run esmini in the same program session, like below?
``` c++
for (int i=0; i<1000; i++)
{
   SE_Init(...);
   for (int j=0; j < 1000; j++)
   {
      SE_StepDT(0.05);
   }
   SE_Close();
}

```
or is it one single esmini run per program run?

In the first case the DLL/shared library will not be reloaded between each run (which basically is supported as well - but yes, with a side effect of memory leaks).

**Comment by eknabevcc** [comment]
I see from the valgrind output that OSG is involved and that the memory leak is related to OSG. 
A recommendation for batch testing is to exclude visualization (OSG) from the actual scenario runs. That will increase test throughput tremendously as the rendering is by far the most costly part of a simulation step. You can choose to record .dat files for later review/visualization of the test runs.
As a side effect, memory leak will be greatly reduced.

Example:
`./bin/esmini --osc scenario.xosc --headless --fixed_timestep 0.05 --record sim.dat`
Note: Make sure to specify timestep in order to speed up execution. Otherwise it will align to "real-time" anyway, i.e. a 20 seconds scenario will take 20 seconds. 

`./bin/replayer --window 60 60 800 400 --file sim.dat --res_path ./resources`

See more on how to play .dat files in [User guide - 4.4. Replay scenario](https://esmini.github.io/#_replay_scenario)

Do you think this approach can work for your use case?

Thanks for valgrind tip. Of course, we'll look into the memory leak and try to gradually improve.
