### ISSUE TITLE
how to new a xosc file?

### ISSUE THREAD

**Issue by tinalazy** [esmini/esmini#30]
HI , I'm a new here! May I ask how can I create a new xosc file by myself?
I have some log such as ego position , opendrive map , speed etc.
But how can I change it to xosc format?
Is it created by hands?

**Comment by eknabevcc** [comment]
Unfortunately esmini does not provide any authoring tools. Most of the example scenarios are actually written "by hand". 
But I can recommend to check out this Python based tool: https://github.com/pyoscx/pyoscx
which makes it possible to write scenarios in a more high level script, and then generate the actual OpenSCENARIO xml file. 
Otherwise, I know that [VIRES ](https://vires.mscsoftware.com/)has a commercial solution (graphical scenario editor). And hopefully there will be open source editors for OpenSCENARIO in the future.

**Comment by tinalazy** [comment]
thanks very much!
