### ISSUE TITLE
how to use esminiLib to set timestep in python?

### ISSUE THREAD

**Issue by qqkkwan** [esmini/esmini#306]
Hello,
     I use python esminiLib  to run esmini，i add this code `se.SE_StepDT(ctypes.c_float(0.02))` but not working，how to solve it?

**Comment by eknabevcc** [comment]
Can't reproduce. Modifying [Hello-World_coding-example/esmini-player.py](https://github.com/esmini/esmini/blob/master/Hello-World_coding-example/esmini-player.py), both these works:

`se.SE_StepDT(ctypes.c_float(0.02))`
`se.SE_StepDT(ctypes.c_float(float(0.02)))`

What is the error message, if any?

**Comment by qqkkwan** [comment]
Hi，
   
[test_timestep.txt](https://github.com/esmini/esmini/files/9137470/test_timestep.txt)

 please take a look at my code , the printed time interval is not always 0.02s
![image](https://user-images.githubusercontent.com/82800669/179664926-4718e5b3-2cff-45d1-bc52-42deb72d83f7.png)

**Comment by eknabevcc** [comment]
Ah, I'm not at a computer for testing.  But at first glance I think I found the issue:

There are two step functions, as you already noticed: `SE_Step()` and `SE_StepDT(float)`. The first one will choose timestep according to actual system time passed since last call, resulting in realtime/interactive rate. The StepDT is simply to set explicit timestep, typically resulting in framerate slower or faster than "real time". 

To further clarify: The SE_StepDT is not for specifying a timestep to be used by SE_Step().

My suggestion is that you use the SE_StepDT variant in the while-loop. Actually, you can skip the first step (after init), since the SE_Init() will make a zero-time step anyway - to establish init state (positions and speed) of the scenario. 

Please try that. I also attach modified code, but please be aware I couldn't test it myself.

[test_timestep-mod.txt](https://github.com/esmini/esmini/files/9138052/test_timestep-mod.txt)

**Comment by qqkkwan** [comment]
Thank you, it works !
