### ISSUE TITLE
install osg downloading err

### ISSUE THREAD

**Issue by lipengliang456** [esmini/esmini#316]
Hi There,
after git clone &&mkdir build&&cmake ..
-- downloading osg.7z ...
CMake Error at EnvironmentSimulator/CMakeLists.txt:516 (message):
  FAILED to download osg.7z (Status: 7;"Couldn't connect to server")
Call Stack (most recent call first):
  EnvironmentSimulator/CMakeLists.txt:534 (download_and_extract)

-- Configuring incomplete, errors occurred!

and I have change the cmakelists: set ( FILE_STORAGE "github" )

elseif (LINUX)
        set ( OSG_PACKAGE_URL https://github.com/esmini/resources/raw/main/libs/OpenSceneGraph_linux.7z )
        set ( OSI_PACKAGE_URL https://github.com/esmini/resources/raw/main/libs/osi_linux.7z )
and I didn't find the 7z package.
how to fix this?

**Comment by lipengliang456** [comment]
i had fix it:
Download OSG and copy it to esmini after build:
cd ~
git clone https://github.com/openscenegraph/OpenSceneGraph.git
cd OpenSceneGraph
cmake ..
make       #this make take a  long time.
sudo make install
copy the file in the build floder to esmini/externals/OpenSceneGraph/linux.

**Comment by eknabevcc** [comment]
Oh. I don't know the reason why the download failed. There has been a case where dropbox banned downloads for 24h due to overload... 

But you should be able to download the links manually, e.g:
https://github.com/esmini/resources/raw/main/libs/OpenSceneGraph_linux.7z
or:
https://dl.dropboxusercontent.com/s/3dlev34kj94lir5/OpenSceneGraph_linux.7z?dl=1

and unpack under esmini/externals/OpenSceneGraph

Anyway: It is also possible to build the OpenSceneGraph (OSG) libs yourself, as you already managed. However, some special build configuration is needed for esmini. Main thing is to build for static linkage. My recommendation is to utilize a build script provided by esmini, you find it here:
https://github.com/esmini/esmini/blob/master/scripts/generate_osi_libs.sh

**Comment by eknabevcc** [comment]
Posted the wrong link to the OSG build script. Here's the correct one:
https://github.com/esmini/esmini/blob/master/scripts/generate_osg_libs.sh
