### ISSUE TITLE
two road in one xodr file

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#326]
OSI enters an endless loop

[bin.zip](https://github.com/esmini/esmini/files/9671554/bin.zip)
![image](https://user-images.githubusercontent.com/114643211/192952595-9ec3dc35-d049-40ae-8c14-8ec022826d2e.png)

**Comment by QLwin** [comment]
same issue.  because two roads not been connected

**Comment by eknabevcc** [comment]
I think the root cause is missing road IDs. 
Please test this modified one (added road IDs): [333-mod.xodr.txt](https://github.com/esmini/esmini/files/9672360/333-mod.xodr.txt)

But I will nonetheless check why it get stuck in endless loop with the original file.

**Comment by csawp** [comment]
thank you

**Comment by eknabevcc** [comment]
Thanks for reporting this issue.

The problem in esmini was that empty or missing road IDs was interpreted as 0. That's OK with only one road, but with multiple roads they all got the same ID (=0).

We've now fixed so that in case of missing IDs esmini will: 1. Warn the user by console/log message, but also 2 Generate IDs automatically.

Fixed by commit a517bea8590469882c0e030b149c22caaac0890e. Will be included in next release.
