### ISSUE TITLE
There are several small problems

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#346]
![image](https://user-images.githubusercontent.com/114643211/200284619-71f509cb-1134-4fdc-bda4-a5edcc86f054.png)
When the GetNumberOfLaneSections function is 0, the FOR loop should be judged by the following IF
The second problem is that the returned value of BOOL is not very safe
![image](https://user-images.githubusercontent.com/114643211/200286711-2c559718-39e4-4098-9fe2-7255dd5b316d.png)
The third problem seems to be a memory leak

**Comment by csawp** [comment]
![image](https://user-images.githubusercontent.com/114643211/200287212-8fc0d8fd-7510-47ad-81c8-b57ab2c74cc9.png)
The second problem is that the returned value of BOOL is not very safe

Supplementary pictures

**Comment by eknabevcc** [comment]
Thanks for findings.

I agree with 2:nd and 3:rd findings. You're welcome to provide a pull request fixing those. Or we can look into it when possible.

The 1:st I'm not sure about. 
The idea is that the "if" scope should only be executed when a valid lane section was found (in the loop). So in case of zero lane sections I think it's find to skip it. 
Maybe I miss something here, could you elaborate about the issue you see?

**Comment by eknabevcc** [comment]
Wow, now I see the issue:
`i < GetNumberOfLaneSections() - 1`
When both `i` and number of lane sections is 0 it says:
`0 < -1`
but since i is an unsigned integer it might be that -1 is interpreted as a large positive integer. The guard fails and the lane_section_[0] cause a crash since there is no first item in the array.

BUT: I wonder how you end up in that case, with zero lane sections. Because, even when OpenDRIVE file is, for some strange reason, missing a lane section roadmanager will add one for the reference lane... But it might be that you use roadmanager in some other way. Regardless the bug should be fixed of course. 
Very good catch - thank you!

Anyway, the three bugs should now be fixed by commit 4a8f75cd697a505c0be0d8743431be9a42a224fa.

Please test and let us know if the issue is gone or not.

**Comment by csawp** [comment]
I will try to dynamically modify the road information halfway to solve the problem, and change int i=0 to a signed variable

**Comment by csawp** [comment]
![image](https://user-images.githubusercontent.com/114643211/200453376-0eb1317c-a8d8-4074-8cb5-0bee0e665cb4.png)
Shouldn't it be the position release in Figure 1

**Comment by eknabevcc** [comment]
I think the above (delete laneChangeAction_) is correct. The object is created in ControllerFollowRoute::CreateLaneChange(int lane), and should be deleted when done.

Regarding the first three fixes, did they work as expected with your use case?

**Comment by csawp** [comment]
No problem, just close the problem
