### ISSUE TITLE
Static_objects within OSI GroundTruth message

### ISSUE THREAD

**Issue by xlimes** [esmini/esmini#350]
Hi,

I would like to develop some ego vehicle control functions and use the UDPDriverController concept to do it.
I am trying to obtain all of the ground truth data. As an example/template I am using testUDPDriver-print-osi-info.py. 
Currently, I can read only moving_object data. 
How I can achieve other data such as static_object? I have some objects within the openDRIVE.

That's an example of what I can read:
![image](https://user-images.githubusercontent.com/91853287/201189268-a1de47bc-aed6-4d4a-bc02-b7de8e5616d1.png)

**Comment by eknabevcc** [comment]
Good question. The example has now been updated, clearly separating static and dynamic data.
The scenario now use a road [(crest-curve.xodr)](https://github.com/esmini/esmini/blob/master/resources/xodr/crest-curve.xodr) with some stationary objects that is printed (some info only, not all) by the script as well.

NOTE: Make sure to start the script first, before esmini, because static data is just transmitted the first frame.

The output should include something like:

```
OSI message timestamp: 0.00 seconds
4 lanes
  [0] id 0 type: 3
    centerline:
    x: 0.00 y: 28.20
    x: 50.00 y: 28.20
...
```

```
8 stationary objects
  [0] id 0 type 9
    pos.x 203.51 pos.y -25.66 rot.h -0.10
  [1] id 1 type 1
    pos.x 191.35 pos.y -0.83 rot.h 1.30
  [2] id 2 type 3
    pos.x 238.37 pos.y -39.68 rot.h 0.00
...
```

**Comment by Chodowi2021** [comment]
Okay, perfect. 
I've got the same results now.
Many thanks for your help.

**Comment by eknabevcc** [comment]
Good to hear. Closing the issue for now.
