### ISSUE TITLE
Is there anyway to get the acceleration of the car?

### ISSUE THREAD

**Issue by OYhhh2** [esmini/esmini#358]
Hello!
I want to get the acceleration state of the vehicle in my Project. but i don't found it in the API, the SE_ScenarioObjectState only have speed, so is there anyway to get the acceleration of the car through API?

**Comment by eknabevcc** [comment]
Unfortunately there is no function to retrieve the acceleration of an object. However you could find it in the OSI data.
Here's an example code showing how it can be done:
https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/osi-groundtruth
(also part of the [User guide tutorial section](https://esmini.github.io/#_osi_groundtruth))

Of course, it is possible to add more Get* functions for acceleration. But we try to keep API limited, instead use OSI for detailed info.

Would that work for your use case? Otherwise we could add a GetAcceleration function of course. The best would be if you could provide by pull request.

**Comment by OYhhh2** [comment]
Thanks !  currently the way i use to get the acceleration is delta_velocity / delta_time,  It would be nice if you can add a function in future version
