### ISSUE TITLE
some API functions doesn't work

### ISSUE THREAD

**Issue by OYhhh2** [esmini/esmini#361]
I am trying to use some API functions and I used SE_ReportObjectAcc function to change the states of ego. but It does not work. Also, I also tested SE_ReportObjectVel, SE_ReportObjectAngularVel, these functions also can't change the ego's states. 

The code i used is python

**Comment by eknabevcc** [comment]
This is a bit tricky and definitely not obvious:
The purpose of the `SE_ReportObjectAcc()` is not to affect the motion of an object, just to override the otherwise calculated acceleration. 

The typical use case is as follows:
There is an external Ego vehicle simulation, for example driving simulator or vehicle under test (including driver model, vehicle dynamics and potential AD/ADAS functions). The state of this external vehicle is reported to esmini, typically with `SE_ReportObjectPos()`. 
For the OSI stream esmini will calculate velocity based on the delta x and y movement. And acceleration is similarly calculated based on delta velocity over time. 

Now, it might be that the calculated acceleration is not perfectly matching the internal acceleration of the external vehicle simulator. We had a case where the OSI acceleration needed to represent the actual acceleration and not the esmini calculated one. 

That's when we introduced this `SE_ReportObjectAcc()`, like a way to tell esmini what acceleration should be reported on OSI, overriding the calculated one for OSI log.

Except for any external vehicle, all objects are updated based on OpenSCENARIO actions. So if you need to control the acceleration (and motion) of a vehicle you could make use of the ExternalController and SimpleVehicle model (create with `SE_SimpleVehicleCreate()`) See this example:
[EnvironmentSimulator/code-examples/test-driver](https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples/test-driver)

**Comment by OYhhh2** [comment]
Thanks for your patient explanation, The work we are doing is to use the a reinforce learning way to control the ego in python environment, i want to control the speed given an acceleration, as your explanation,  the SE_ReportObjectAcc() is not to affect the motion of an object, so the function i use now is SE_ReportObjectSpeed in a discrete method.
for example: `SE_ReportObjectSpeed(ctypes.c_int(se.SE_GetId(0)), ctypes.c_float(obj_state.speed + a*dt))`, it can change the ego's speed.

**Comment by eknabevcc** [comment]
Thanks for info! Ah, yes you're right. The `SE_ReportObjectSpeed()` DO have effect on the speed (while the *acc and *vel do not). 

So, actually, what you're doing is probably the best solution for updating a scenario vehicle based on externally calculated speed (regardless how it is calculated, e.g. based on acceleration or some recorded data...).

Does it work as expected for your use case, or you still see some issue?
