### ISSUE TITLE
Use mandatory argument for commandline tool file input instead of optional

### ISSUE THREAD

**Issue by johschmitz** [esmini/esmini#365]
For the commandline tools like esmini, odrviewer, etc. please consider somehting like

`odrviewer track.xodr`

instead of 

`odrviewer --odr track.xodr`

This is more common with commandline tools that consume a mandatory input file as you have to specify the file in any case and then it is easier to type and also one less thing to forget.
I see that this might be not so nice to change due to some integration issues but at least consider it since it would be much more clean. Have a look at some other tools for comparison. I can understand if you label this as "Won't fix" but then we at least have it documented that it can't be changed soon. If not for esmini itself, maybe it can at least be changed for the odrviewer though, which is frequently used with a single argument on the commandline since this would save people a lot of typing work.

**Comment by eknabevcc** [comment]
I totally agree that it would be better with compulsory argument for the .xosc file. But there is a (more or less good) reason for not.

esmini is making use of the OpenSceneGraph Viewer class for visualization of the scenario. This class is configured via command line arguments. Further, the format of those arguments do not really follow a strict pattern. Some options has first a keyword, e.g."--window", followed by a set of space separated parameters (window position and size in this case). Hence it's not trivial for esmini to identify what arguments is keywords or actual parameter, i.e. to identify the esmini compulsory argument. 

The solution has been to specify the set of esmini arguments and options with keyword and potential parameters. When all those has ben extracted from the total list of arguments the rest is simply handed over to OpenSceneGraph. 

It's probably possible to find a smart solution, but the hard way would be to identify all supported OSG arguments as well within esmini. But that solution I don't like (1. undesired dependency and 2. boring, low prio work to implement). 

It comes down to that it's basically not a prioritized thing. esmini is mostly used as library or via scripting. An advice is to create a wrapper script (which I do myself sometimes), where you can add any default arguments and also allow for just specify .xosc file. 

All this said, if someone can provide a good solution (pull request) we will of course consider it. 

But good that you reported the issue. So that it's documented anyway. 
I close the issue for now.
