### ISSUE TITLE
Dynamic library problem

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#382]
Hello! ESMINI is currently a static library. Can you add a dynamic library version

**Comment by eknabevcc** [comment]
esmini is a dynamic/shared library. Although it contains statically linked content (libraries). If all libraries were dynamically linked it would be roughly 1 GB of libraries needed to be available at runtime. One nice advantage with static linking is that the linker removes unused code, just including functions that are being used by esmini.

For all dependencies to be dynamically linked, all 3rd party libraries (osg, osi...) would need to be rebuilt. Also all those files (libs) would need to be present for executing esmini. This is of course possible, so if you really need it, you could potentially try yourself.

Could you elaborate on motivation, what is the use case you have that current library doesn't fit?

**Comment by csawp** [comment]
I put it in the UE5 engine. When multiple DLLs load GetOpenDrive, the returned object is not the same object. I can only change the link library myself

**Comment by csawp** [comment]
![image](https://user-images.githubusercontent.com/114643211/216258831-d0568bfa-121c-47ff-bb58-76123b80d878.png)
The parameter is bool and the value is double

**Comment by eknabevcc** [comment]
Ah, I see. You're integrating with UE5. That's actually really interesting. Something I'd thought of for some time, but never got the time to try. 

I see, as alternative approach to integrating the shared library you tried to import esmini source code. Perhaps type collisions could be solved by encapsulating esmini in an own unique namespace. But I'd put my bets and efforts on trying to solve the shared library approach.

I don't understand the "multiple DLLs". Is it that multiple instances of esmini is loaded and active simultaneously? Or do you maybe use esminiLib.dll in parallel with esminiRMLib.dll - which should be possible (see [example](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/rm-se/rm-se.cpp)), but this is not a common use case so it's not tested thoroughly.

Can you elaborate, further explain "I put it in the UE5 engine. When multiple DLLs load GetOpenDrive, the returned object is not the same object. I can only change the link library myself"?

**Comment by brifsttar** [comment]
I've had the issue for [my plugin](https://github.com/brifsttar/OpenDRIVE), which is why I use a [custom DLL](https://github.com/brifsttar/esmini/tree/roadmanager) instead of the static one.

Basically, it boils down to the singleton inside RoadManager: it's different for each DLL that uses the static lib. And since each plugin in UE is a DLL, it can become quite messy if you have multiple plugins interacting with the OpenDRIVE network.

At first my workaround was to load the `xodr` file on each plugin, so that at least they all share the same data, even if it's not actually the same object in memory. But that was obviously very ugly, which is why I moved to make RoadManager into a DLL, so that there's only one singleton, and every other plugin is using the same.

I've also thought about removing the singleton inside RoadManager, but that would be way too much work, and in the end building dynamically was much easier.

**Comment by csawp** [comment]
Thank you for your reply! I have solved the above problems. The solution is to manually copy the code into the UE5 engine. I can only modify the names of ENUM and macro conflicts. It can already work normally

**Comment by eknabevcc** [comment]
Excellent! Thanks @brifsttar for support!
I close this now. We can re-open if further issues arise.
