### ISSUE TITLE
Coordinate system 

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#385]
Hello,

I design open scenario using AVL scenario tool, 

1st version: all vehicles are located using "RoadPosition", intended scenario is car4 should be approaching to ego, but it is going opposite direction.

2nd version: same code. I changed "RoadPosition" to "WorldPosition" for car4.

I'm not sure location is same, but I guess I pointed similar location using AVL scenario design tool.

It played as I intended in the esmini.

Two version are also same simulation result in AVL tool, but different behavior in the esmini play.

Am I missing something? or I find a bug?

Do you have any recommendation for my scenario design using esmini ?

Regards
```

<                 <RoadPosition roadId="1" s="236.5723114013672" t="2.0126430988311768">
<                   <Orientation h="0.0" p="0.0" r="0.0" type="relative"/>
<                 </RoadPosition>
---
[resources.zip](https://github.com/esmini/esmini/files/10574245/resources.zip)

>                 <WorldPosition x="230.973" y="1.724" z="0.0" h="3.141592653589793" p="0.0" r="0.0"/>
```

**Comment by victor0777** [comment]
[resources.zip](https://github.com/esmini/esmini/files/10574258/resources.zip)

**Comment by eknabevcc** [comment]
Ah, you found a tricky thing. In esmini the interpretation of relative orientation differ between RoadPosition and LanePosition.

For lane position it will be according to driving direction (of the lane), but for road position it will be according to s and t of the road. For good and bad. We simply found this to be the best compromise solution offering most flexibility for users.

See more info in old issue here: https://github.com/esmini/esmini/issues/228#issuecomment-1039267914

So, in your specific use case I'd recommend to use LanePosition instead of RoadPosition. See modified scenario:
[20171115_SEQ_S_F_N_1_0_1_7_1_esmini-mod.xosc.txt](https://github.com/esmini/esmini/files/10739828/20171115_SEQ_S_F_N_1_0_1_7_1_esmini-mod.xosc.txt)

**Comment by victor0777** [comment]
Thanks for your comment.
