### ISSUE TITLE
Yaw (wrong pose) issue when entities are Teleported

### ISSUE THREAD

**Issue by Iqbalparvi** [esmini/esmini#386]
Hello esmini team.Thank you for providing an amazing and  very user-friendly simulation environment.
We are experimenting with esmini using an open scenario.
When Teleport Action is used to place the obstacles (stationery cars) in the surrounding.
`e.g :
<TeleportAction>
              <Position>
                <WorldPosition h="-29.0482" p="0" r="0" x="$Car_1_PositionX" y="$Car_1_PositionY" z="$Car_1_PositionZ"/>
              </Position>
            </TeleportAction>
`
The esmini teleported all entities at the required location but with the wrong yaw. This caused the entities (stationery cars) to be placed in very different directions in the esmini closed-loop simulation window.
It seems that the teleported Actions are always set to 0 with esmini.
The behavior is shown in the below figure.
![image](https://user-images.githubusercontent.com/47267894/216728806-7aa9ace7-5a6e-4aa7-857a-9bb29b99f867.png)
Could you please investigate whether it is a bug/shortcoming with esmini or if something is missing?
More information will be supplied if required.
Best Regards.

**Comment by eknabevcc** [comment]
Before investigating further: 
Can it be a unit issue? OpenSCENARIO (and esmini) handles angles in radians (which is the SI unit for angles). The range is (0, 2*pi) = (0, 6.28...), i.e. full circle. But values outside this range should also be accepted.

Can you try this: 
`<TeleportAction> <Position> <WorldPosition h="${-29.0482 * 3.14159 / 180}" p="0" r="0" x="$Car_1_PositionX" y="$Car_1_PositionY" z="$Car_1_PositionZ"/> </Position> </TeleportAction>`

**Comment by Iqbalparvi** [comment]
Thank you.
Yes, you are right.
1. Although the OSC window confuses the user, however, the suggestion is helpful to correct the Yaw angle (in radians) of the teleported entities on esmini.
2. The suggestion also motivates us to re-exploring the base simulator environment (scenario design phase) and seems that the limitation (unit issue) exists on that platform.

It is also very interesting and helpful to explore Open SCENARIO in terms of the integration and portability of the tools.
Best regards.

**Comment by eknabevcc** [comment]
Yes, it's a bit confusing. Users are, in general, probably more comfortable with degrees instead of radians for angles. But yes, I agree with you that it's good to solve at tool-level, so the user works in degrees but the XML is saved with radians 👍

By the way, a tip might be to toggle between information text modes with 'i' key (or add launch argument: `--info_text 3' for both). Then you can see angles for entities, although still in radians it might be useful.

I also agree that it's great to discuss interpretation of OpenSCENARIO, the goal is to harmonize as much as possible, having the same understanding among users and tools. 👍

I'm closing the issue. Please add any future questions and we can re-open.
