### ISSUE TITLE
Waypoint  / AssignRouteAction doesnt work in newer versions of esmini

### ISSUE THREAD

**Issue by pjk19942** [esmini/esmini#395]
Hi,

I used esmini version 2.1.1 where waypoints, assingRouteAction etc used to assign routes to a vehicle and make it follow a particular route on junctions and crossroads. When migrating to newer esminis (ex 2.28.0) , its observed that they do not follow the waypoints anymore. I am including the xosc and xodr. 
Library used: scenariogeneration.

If you have any examples with py scripts, that would be of great help!
[esmini_wp.zip](https://github.com/esmini/esmini/files/10771639/esmini_wp.zip)

**Comment by eknabevcc** [comment]
I checked the scenario. The trigger condition for car_1 first route is never becoming true, the point being too far away. When subject reaches that point the car_1 is already passed the entry to intersection.

Please check and try this modified scenario:
[TestDummyEvent-mod.xosc.txt](https://github.com/esmini/esmini/files/10773575/TestDummyEvent-mod.xosc.txt)

(I also removed the teleport to non existing road, I think the DeleteAction, which nowadays being supported by esmini, is doing the job alone)

I don't know why the scenario run in an very old esmini version (remember that without the route being triggered in time, the car_1 might take the intended way anyway, since choice is random). Let's first see if we found the problem, else we will investigate further.

**Comment by pjk19942** [comment]
Hello, 

Thank you for you quick reply! 

Here are my comments:
1) So i modified my file to have a quicker (earlier ) trigger, for the subject vehicle, from the file, it seems that you changed the lanedistance trigger to -1, 1,150.0  (l,r,s). When i run it , it seems fine but when i run it for like 5-10 times, it sometimes takes the right(which its supposed to) and sometimes just continues going infront. Kindly check the video. 
2) To make sure the vehicles are following the right path everytime, i loop it multiple times and view the event to make sure waypoints are working and as you can see it did not do anything, this was an exact replica of the xosc you sent.
3) Yes DeleteAction was better to teleport the actors, while using older esmini since this function wasn't present i had used a workaround so depending on the version the recipient has the cars teleport eitherway.

As you can see, the waypoints did not work (both the cars are expected to take the right turn). I have also put time triggers but that doesnt give me a good repeatability test. Ill be happy to share more examples. 

https://user-images.githubusercontent.com/125699572/219931496-34ee0325-10c0-4232-b7b2-6917cb4fcfec.mp4

**Comment by eknabevcc** [comment]
Indeed you found a bug. An unfortunate side effect of the distance check condition messing up the route following mechanism. 

It should be fixed by commit 7df5a1c1a253e70a757115600e27948befad81c5, merged on master.

Can you compile yourself to test the fix, or do you need a release?

Thanks for reporting this bug, appreciated!

**Comment by pjk19942** [comment]
Is it possible for you to share a release?

**Comment by eknabevcc** [comment]
[v2.29.3](https://github.com/esmini/esmini/releases/tag/v2.29.3) available.

Ok, interesting. Maybe there are further issues. At least we solved one obvious bug. Please test and report how it behaves.

**Comment by eknabevcc** [comment]
Thanks for the feedback. Really good that we found and fixed this bug thanks to your report!
