### ISSUE TITLE
SetTrackPos

### ISSUE THREAD

**Issue by csawp** [esmini/esmini#396]
There are such problems on the inside and outside of the curve
![image](https://user-images.githubusercontent.com/114643211/220000120-d33d887a-88fa-4d9e-9f5e-950e41d5e432.png)
If the required parameters are the start position and end position and interval through the function, the coordinates, GetP, GetR, GetH will be obtained

**Comment by eknabevcc** [comment]
Can you clarify what is the issue (I suspect the gap between barrier objects, but I'm not sure)? 

And please provide an example OpenDRIVE/OpenSCENARIO files highlighting the problem.

**Comment by csawp** [comment]
I calculate the coordinates every 4 meters, and there are obvious gaps on the outside of the curve

**Comment by eknabevcc** [comment]
Do you use functions in esminiLib or esminiRMLib, or internal RoadManager methods? 
Can you provide example code and OpenDRIVE for our reproduction and understanding? (I can imaging many root causes, like elevationProfile, super elevation or some lane offset...)

**Comment by csawp** [comment]
![image](https://user-images.githubusercontent.com/114643211/220032171-4a418549-09fc-4adb-8a18-308d8ef4a3f5.png)
At present, I use the SetTrackPos function to calculate. I estimate that the length of the edge line is required to calculate

**Comment by eknabevcc** [comment]
Thanks for code snippet. I understand better now.

I'm not sure, maybe you're already taking into consideration the arc length depends on curvature. I.e. a delta-s step along reference line might be longer or shorter distance at lane borders, depending on curvature and t-offset. Like illustrated roughly in the image below:

![img](https://user-images.githubusercontent.com/29146839/220036851-3008a160-1e0a-454f-b51e-8577515eaf92.jpg)

If you think this could be the root cause, there an internal function that adjusts delta-s based on current t-value. Perhaps it can give some ideas for solution:
https://github.com/esmini/esmini/blob/7df5a1c1a253e70a757115600e27948befad81c5/EnvironmentSimulator/Modules/RoadManager/RoadManager.cpp#L7850

I think the actual calculation is this:
`ds *= 1.0 / (1.0 - curvature * offset);`

By the way, the generated 3D model looks great! Can you tell about the project/product?

**Comment by csawp** [comment]
Our project develops an editor to generate models based on road and terrain data, and automatically generate bridges, slopes, tunnels, guardrails, and other models that can finally be edited for the road. The surrounding models will also change with the terrain

Now I can get the point of your edge rendering line and generate the point I need according to the length of the rendering line, so I want to ask if you have a better method

**Comment by eknabevcc** [comment]
Since the arc-length will depend on curvature and offset (along t-axis) my suggestion is to either:
- keep constant s-steps and adjust the loft-length of your geometries (increase or decrease length from 4 meters), or
- adjust the s-value steps and keep constant geometry size

I think it's up to the use case which method is preferred.

**Comment by csawp** [comment]
It should be the WHILE cycle several times

**Comment by eknabevcc** [comment]
Make sure `pos` always has the correct t-value before calling DistanceToDS(). Maybe first time (first iteration) it is not set?

Suggestion: Add after line 187, something like:
`pos.SetTrackPos(track_id:roadID, s:start_K, SIGN(laneID) * (lane->GetOuterOffset(s:startK, lane_id:laneID) + offset_t));`

**Comment by csawp** [comment]
I have tested this. It seems that it is not caused by this. It seems that the length of the curve is too long. It should be more than the original cycle

**Comment by csawp** [comment]
I will find out the reason myself. I will reply to you after solving the problem. Thank you for the function you provided

**Comment by csawp** [comment]
The problem has been solved. The reason is that the DistanceToDS parameter is the step ratio returned by the step value. What I passed is that the actual K value is wrong. Then the cycle times are two times different. The first time GetCurvature() GetT() is not initialized,

double step_ K = pos.DistanceToDS(SMALL_MESH_LEN);

Solved

I want to ask the difference between the three functions of SetTrackPos SetLaneBoundaryPos SetLanePos

**Comment by eknabevcc** [comment]
Good news, glad you found a solution!

`SetLanePos(int track_id, int lane_id, double s, double offset, ...)`
set position on the lane center. Useful for "driving along the road"
offset will adjust left or right in both cases

`SetLaneBoundaryPos(int track_id, int lane_id, double s, double offset, ...)`
set position on the lane boundary (outer edge of the lane). Useful e.g. when creating road marks.

`SetTrackPos(int track_id, double s, double t, ...)`
set position at some offset (t-value) from reference line, disregarding lanes

**Comment by csawp** [comment]
There are gaps occasionally, and the curvature changes suddenly and the step length is also relatively long

**Comment by csawp** [comment]
![image](https://user-images.githubusercontent.com/114643211/220238831-d8098e4f-354a-4003-bb39-2989438f78f0.png)
I have referred to your picture for this case

**Comment by eknabevcc** [comment]
Code looks good.

And yes, if the curvature changes rapidly it will result in gaps (outer lanes) or overlaps (inner lanes). For most cases, along country roads or highways the curvature/radius will not change significantly over a few meters though. So the method should be good for use cases such as railings and similar.

For cases where you need to follow also sharp curves you could also adjust the length of the lofted objects. For example, a fence segment of 4 meter length might be too long for a sidewalk in an intersection. The idea: The sharper curvature, the shorter step length (and shorter objects).

Further, you could also check the curvature change rate (compare GetCurvature() results) and adjust each ds step length accordingly, e.g. if the curvature increases then add some corresponding factor to the ds. It will not be perfect, but better.

**Comment by csawp** [comment]
OK, thank you for your reply. I basically understand
