### ISSUE TITLE
Exception handling in the API

### ISSUE THREAD

**Issue by ClemensLinnhoff** [esmini/esmini#397]
What would happen, if an exception occurs in the scenario engine during an API call?
Is there any exception handling? What would the output of the API call be?

E.g. I call `SE_Step();`. How would I know, if this was executed correctly?

**Comment by eknabevcc** [comment]
We try to use classic error handling with return codes instead of exception handling.

For example, to check if the scenario was loaded and initialized correctly you can check return code as:

``` c++
if (SE_Init("cut-in.xosc", 0, 1, 0, 0) != 0)
{
	printf("Failed to initialize the scenario\n");
	return -1;
}
```

That said, the error checking is limited. For example, the SE_Step() will return error (-1) only if the player is not available, i.e. something is terribly wrong. One reason is that it can be argued what is a successful step or not.

It is an ambition to catch and handle errors that otherwise would lead to a crash. So we encourage to report an issue if you encounter a crash. 

For other errors esmini try to be forgiving, i.e. will try to continue even if some potential problem has been identified, e.g. missing attribute or road ID. 

For unexpected errors or behaviors in the scenario, check the log file. It might give a hint on what's wrong.
