### ISSUE TITLE
Licensing options

### ISSUE THREAD

**Issue by ofarar** [esmini/esmini#40]
There is a document created by you about SyncronizeAction including formulas. We want to use same SyncronizeAction approach in our commercial project. What are licensing options, does it allow us to use it in our project under which circumstances? Licensing looks a bit complicated so that I wanted create a ticket.

**Comment by eknabevcc** [comment]
Yes, I guess it's this description you're referring to: [esmini - Synchronize speed calculation](https://docs.google.com/document/d/1dEBUWlJVLUz6Rp9Ol1l90iG0LfNtcsgLyJ0kDdwgPzA/edit?usp=sharing)

Legally I guess that if you’re just getting inspired from esmini implementation or related documentation there is no obligations from your side. But to make it totally OK to use whatever you want from the project, and to make it simple, let's consider the description to be part of the esmini project and hence under the same license terms.  We selected the MPL 2.0 since it was comparably simple and it covers exactly our intentions – to spread OpenSCENARIO and stimulate crowd development while being permissive. 

To elaborate a little: It shall be easy and legally safe to use ideas or actual code from esmini. It should be no problem to distribute software including (parts of) esmini. There are only a few requirements: 1. It should be apparent somehow that esmini is used (purpose to spread OpenSCENARIO and the existence of esmini). 2. The esmini license should be provided. 3. Access to esmini origin should be provided (e.g. via link to esmini GitHub repo) and 4. Any modifications to esmini parts (of the distributed software) should be made public, e.g. offered back to esmini repo via pull request. 

So, to conclude, it is PERFECTLY OK to in include esmini (ideas and code) in a commercial product as long as the terms are fulfilled. A suggestion, to solve first 3 requirements, would be to include two files: esmini_license.txt (renamed copy of https://github.com/esmini/esmini/blob/master/LICENSE) and esmini_link.txt (just including a URL to https://github.com/esmini/esmini). 

Regarding feeding back modifications: Note that MPL 2.0 license only requires modifications to esmini code to be published, it does NOT affect the rest of the software product being distributed. This is a really good aspect of MPL 2.0.

I’m just glad to hear that you find the ideas about synchronize implementation potentially useful. I have a feeling that there are room for improvements and simplifications. So if you find any, please let us know! :)

Sorry, this text become much longer that I expected... I don't want to make it appear complicated. What do you think?

**Comment by ofarar** [comment]
Yes, thank you for the detailed answer. It is clear for us how to use it.

**Comment by eknabevcc** [comment]
Sounds good! Just one additional thought: It can make sense to mention, e.g. in the link-file, how or to what extent esmini is used. I mean, if esmini is used only in a very limited way it can make sense not to give esmini more credit than deserved :) - e.g. for parts you developed yourselves but overlapping functionality provided by esmini, hence could wrongly be assumed to be esmini...

**Comment by eknabevcc** [comment]
Close this now. I hope that you were not discouraged from using/getting inspiration from esmini. In that case I would appreciate feedback so we can adjust how we describe the license terms to make it as simple as possible to use esmini.
