### ISSUE TITLE
Static link to esminiLib

### ISSUE THREAD

**Issue by ClemensLinnhoff** [esmini/esmini#414]
Is it possible to link statically against esminiLib?
I have the problem, that the new [esmini OSMP FMU](https://github.com/esmini/esmini/tree/dev/OSMP_FMU) works fine, when it is built on the same system where it is later applied. But the beauty of an FMU is, that it is transferable between systems. So esminiLib would need to be statically linked into the FMU.

The problem came up, when I tried to run the esmini FMU in a Github action. You can see the problem [here](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/4531148979/jobs/7981122660).
Before I try to figure this out myself, maybe you can give me some pointers.

This might be related to #382.

**Comment by ClemensLinnhoff** [comment]
I circumvented this for now by copying the linked libesminiLib.so into the co-simulation environment. You can see the successful application of esmini together with a sensor model in a co-simulation using OpenMCx in [this](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/4535292843/jobs/7990684934) pipeline.

But in the long term, the library should be statically linked to be more universally and easily applicable.

**Comment by eknabevcc** [comment]
Nice! Seems like a reasonable solution 👍

But I also think for some use cases static linking is preferred. Instead of creating a static super-lib (including all needed libs), I added a static variant of just the esminiLib API, which then can be linked together with needed esmini modules.

Further I tried to tweak the OSMP FMU cmake recipe with an option for a static linking like that.

I'd appreciate if you could have a look and try the branch:
https://github.com/esmini/esmini/tree/feature/add_link_option

I also added brief info to the [OSMP_FMU/README.md](https://github.com/esmini/esmini/blob/feature/add_link_option/OSMP_FMU/README.md) regarding static/dynamic linking.

I tested building quickly, it seems to work on both Windows and Linux at least. But I've no clue whether the result works! :)

So I thought keeping it in a branch until you tested it. If you say OK I can merge it to dev.

**Comment by ClemensLinnhoff** [comment]
I can build your solution on my local linux machine. But building the FMU in the GitHub pipeline does not work. For some reason the OSI headers are not found: https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/4561978771/jobs/8048590888

Do you have any idea, why?

**Comment by ClemensLinnhoff** [comment]
Oh, you were right. It works now, thank you!
So we can merge into dev!

**Comment by eknabevcc** [comment]
Done
