### ISSUE TITLE
Controllers must have a config file

### ISSUE THREAD

**Issue by arauschert** [esmini/esmini#43]
When loading a scenario, where a controller is defined for an entity without a file reference, esmini throws an error:
ScenarioReader.cpp / 894 / scenarioengine::ScenarioReader::parseEntities(): Failed to load SUMO config file , also tried ././

and as a consequence:
ScenarioReader.cpp / 1785 / scenarioengine::ScenarioReader::FindObjectByName(): Failed to find object Ego
main.cpp / 298 / main(): Failed to find object Ego

I checked the source code and compared it with the scenario. In the controller catalog I don´t define a filepath for the controller property. So in ScenarioReader::ParseEntities() the pointer ctrl != 0, but ctrl->config_filepath_ is "". This leads to the error log above and return -1; and the entity is not parsed completely.

The question now is: "What is the correct way to use controllers? Do they always need a config file?"

The User Guide says:
"The Controller element contains Properties, which can be used to specify Controller behavior either directly or by a File reference"

And in the UML model the "Properties" of a controller are mandatory, but within the "Property" and "File" are both optional.

So I assume it´s not mandatory to pass a config file for a controller. Users may not need to pass configurations to the controller or pass them in a different way (e.g. via the test case).

Is it possible to make the Scenario Reader only check for a config file, if ctrl->config_filepath_ != ""?

**Comment by eknabevcc** [comment]
You're absolutely right (as usual). Thanks for pointing out the issue! So far we've only used SUMO controller so we haven't stumbled on this issue until now. 

The code has been modified so that any controller is registered (by name) and no file ref required. Only controllers named "sumo_configuration" are parsed, and then the config file is expected. Please check [release 1.7.10](https://github.com/esmini/esmini/releases/latest) (or later), hopefully it works better. 

I think this is one step towards the nice strategy discussed in [issue 22](https://github.com/esmini/esmini/issues/22).

**Comment by arauschert** [comment]
Thanks for the quick update. I tried 1.7.10. The parsing doesn´t abort anymore, but unfortunately still the entity cannot be found:
ScenarioReader.cpp / 863 / scenarioengine::ScenarioReader::parseEntities(): START!!! Parsing traffic controller from reference
ScenarioReader.cpp / 580 / scenarioengine::ScenarioReader::parseOSCObjectController(): Parsing Controller ALKSController
ScenarioReader.cpp / 866 / scenarioengine::ScenarioReader::parseEntities(): Parsing traffic controller from reference: ALKSController
ScenarioReader.cpp / 951 / scenarioengine::ScenarioReader::parseEntities(): Controller "ALKSController" registered, but is not recognized by esmini
...
ScenarioReader.cpp / 1804 / scenarioengine::ScenarioReader::FindObjectByName(): Failed to find object Ego

I assume that entities_->addObject(obj); or something similar isn´t executed when a controller is assigned to the entity and that´s why the entity cannot be found later.

**Comment by eknabevcc** [comment]
Ah, that's true. My bad. It would be really quick to just fix that very issue, to keep the entity. That of course should be the default way with controllers. Only SUMO is special since SUMO take control over spawning the vehicle(s). 

But with that quick fix esmini will only continue "business-as-usual". Still there would be no mechanism inside esmini executing the controller. What is you use case? E.g. disable internal scenario control of the entity and rely on state being reported via DLL API? I'm thinking that if I understand the use-case maybe we can take another step forward...

**Comment by arauschert** [comment]
Hi! Yes, that´s exactly the intended use-case. As mentioned in the OSC User Guide, controllers can be used for "Specifying that a vehicle should be controlled by the system under test". Like esmini can recognize controllers with name "sumo_configuration", other environment simulators could recognize controllers with other names. The mechanism inside the environment simulator to activate the external controller would most probably be not standardized. At least this is out of scope for OSC.

One more thing (but this could be also put in a new issue): When a controller is activated for a domain (lateral/longitudinal), then the default controller for this domain should be deactivated. For a smooth handover probably it´s better to deactivate the default controller only, when the first position update is received from the external controller.

**Comment by eknabevcc** [comment]
Ok, great. Then I understand perfectly. Now I think it's the perfect time to (try to) refactor the esmini control attribute (external, internal, hybrid) into the concept of controller. Meanwhile, few days, please let me know if the quick fix would help you. Otherwise I save it for next release whenever that will be.

**Comment by arauschert** [comment]
Yes, the quick fix would already help me to get the scenarios running again.

**Comment by eknabevcc** [comment]
v1.7.11 should be on its way 👍

**Comment by arauschert** [comment]
Thanks a lot! Scenarios are executable again. I´ll close the issue.
