### ISSUE TITLE
Exporting lane_id in csv_logger

### ISSUE THREAD

**Issue by bkrztrk** [esmini/esmini#434]
Hello everyone,

Would it be possible to incorporate both lane_id and bounding box data into the csv_logger?

**Comment by eknabevcc** [comment]
Unfortunately the csv_logger is not configurable so that you can log whatever attributes you want. But yes, it can be extended to also log lane_id and bounding box data. It requires some coding, similar to this commit: e7d51a252f12270ab55197030ea5ec554a97ae5d

Would you like to try implement it? In that case you can then make a pull request targeting dev branch. ([see here](https://esmini.github.io/#_branch_strategy)). Otherwise, let us know and we'll do it when possible.

For clarification, I assume it's the following attributes you need:
lane_id, bb_x, bb_y, bb_z, bb_width, bb_length, bb_height
maybe also lane_offset?

**Comment by bkrztrk** [comment]
Thank you for adding this option in new release!
