### ISSUE TITLE
How to get x and y when I know the s and t in a road

### ISSUE THREAD

**Issue by OYhhh2** [esmini/esmini#437]
I am using the API and write some code to generate vehicle trajectories. howere, it is difficult to handle the curve road when using the cartesian coordinate( x, y ).  So, is there any way or function to transform the ( s, t ) to ( x, y ). which means that, for example,  input the s, t in a road, and i can get the x, y

**Comment by eknabevcc** [comment]
esmini will always resolve all position types whenever a position is set. So for example, if you set a world position the closest road position will be calculated, i.e. road id, s, t, lane id, lane offset. And if you set lane position, x, y, z, heading will be calculated.

If you're just using esmini for positioning objects in a road network, then you're maybe using the esminiRMLib (roadmanager only). Then you can see this example: [rm-basic.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/rm-basic/rm-basic.cpp) how you can set position in one format (e.g. world position) and fetch it in another format (e.g. lane id and offset). 

If you're using esminiLib (including scenario engine) then you can see updated example: [hello_world/hw4_external_ego_control.cpp](https://github.com/esmini/esmini/blob/dev/EnvironmentSimulator/code-examples/hello_world/hw4_external_ego_control.cpp) 
(on dev branch so far, will be merged to master by next release)

But in that example it's demonstrated how to set x, y-coordinates, and how you can retrieve resulting road coordinates. You need the other way around, which is equally simple. Try modify the above example as follows:

```c++
#include "esminiLib.hpp"
#include <stdio.h>

int main(int argc, char* argv[])
{
    const char* filename = argc > 1 ? argv[1] : "../resources/xosc/cut-in_external.xosc";
    SE_ScenarioObjectState state;

    if (SE_Init(filename, 0, 1, 0, 0) != 0)
    {
        return -1;
    }

    for (int i = 0; i < 500 && SE_GetQuitFlag() != 1; i++)
    {
        SE_ReportObjectRoadPos(SE_GetId(0), 0.0f, 0, -4, 0.2f, float(i));

        SE_Step();

        // fetch position in terms of world coordinates
        SE_GetObjectState(SE_GetId(0), &state);
        printf("x: %.3f y: %.3f z: %.3f\n", state.x, state.y, state.z);
    }

    SE_Close();

    return 0;
}

```

I hope you can progress with this info. Let us know if not.

**Comment by OYhhh2** [comment]
Thanks for your information，and i have a question about the  esminiRMLib, the RM_PositionData dont't have t , but the RM_RoadLaneInfo have the t, what's the relationship about the t in SE_ScenarioObjectState in esminiLib?

**Comment by eknabevcc** [comment]
`t` is the lateral distance from road center. `laneOffset` is the lateral distance from center of the lane, which id is given by `laneId`.
It's the same `t` as in SE_ScenarioObjectState. 

In OpenSCENARIO you can specify position in multiple ways. One options is: [LanePosition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/LanePosition.html) in terms of `roadId`, `s`,  `laneId`, and `laneOffset`. Another is [RoadPosition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/RoadPosition.html) in terms of just `roadId`, `s`, and `t`.

Every time a position of any type is set in esmini, the other ones are calculated as well. So for example, if you specify a [WorldPosition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/WorldPosition.html) in terms of `x` and `y`, you can then fetch `roadId`, `laneId`, `s` and so on.

I hope this answers your question. Otherwise let me know in more detail what is your objective and we'll try to support.

**Comment by OYhhh2** [comment]
Thanks for your guidance, It solved my problem well
