### ISSUE TITLE
LHT roads in odrviewer

### ISSUE THREAD

**Issue by iskragasparic** [esmini/esmini#441]
I ran an odrviewer for multiple left-hand traffic roads (including the example from the repository: /resources/xodr/e6mini-lht.xodr).
However, all the vehicles are driving in reverse. Is this expected?

Thanks!

**Comment by eknabevcc** [comment]
No, it's not intentional. Actually this bug, that you found, has been around since [Dec 30 2021](https://github.com/esmini/esmini/commit/8f9b1396cb49605fd7547a9b00c26393be680a70). Thanks a lot for reporting it!

Should be fixed by commit [c32823](https://github.com/esmini/esmini/commit/c328230dd47d1ec59519f96a4034cafeea646e1d) on dev branch. It will be merged to master by next release.

**Comment by eknabevcc** [comment]
Included in release [v2.31.7](https://github.com/esmini/esmini/releases/tag/v2.31.7).

Please test and report back how it works for your road network.

**Comment by iskragasparic** [comment]
Hello, I tested the update on 5-6 examples and I did not find any issues so far.
Thanks a lot!

**Comment by eknabevcc** [comment]
Great, thanks for report and testing. Closing the issue.
