### ISSUE TITLE
How to visualize the trajectory of ego

### ISSUE THREAD

**Issue by ChengWang2018** [esmini/esmini#452]
Dear esmini developers,

Thanks for the excellent esmini simulator! 

I would like to ask how to visualize the path that the ego has driven and also the trajectory that ego plans to go in the GUI? 
Thanks a lot!

This will make the simulation nicer.

Best reagards
Cheng

**Comment by eknabevcc** [comment]
You can visualize the already driven trajectory by adding launch argument ``--trail_mode 1``. Mode 2 will drop dots along the trail at fixed frequency, and mode 3 will show both trajectory and dots. You can also toggle between the various modes with "j" key. See [command reference](https://esmini.github.io/#_command_reference) for all launch commands.

However, visualizing future trajectory is in general not possible in esmini. Only for ongoing FollowTrajectory actions the planned trajectory is visualized (like in this example scenario: [trajectory-test.xosc](https://github.com/esmini/esmini/blob/master/resources/xosc/trajectory-test.xosc)). The reason is simply that future is not always known. A scenario might include vehicles externally controlled vehicles, and those vehicles might be used for relative conditions and actions (e.g. for keeping distance or speed). Condition can also be triggered from external processes by use of [variables](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4908&token=ae9d9b44ab9257e817072a653b5d5e98ee0babf8#_variables) and [VariableCondition](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/VariableCondition.html).

But there might be a solution: You can record a scenario in esmini and then replay it with all trajectories visible in replayer.
Try this:
`./bin/esmini --headless --fixed_timestep 0.05 --record sim.dat --osc ./resources/xosc/cut-in.xosc;./bin/replayer --window 60 60 800 400 --res_path ./resources --file sim.dat`
Find more info in [User guide - Replay scenario](https://esmini.github.io/#_replay_scenario).

I hope these suggestions are good enough for your use case.

**Comment by ChengWang2018** [comment]
Thanks very much!

However, I am controlling vehicles in the simulator and using the example in ad_hoc_traffic.py to start the simulator. So it is impossible for me to use the launch argument? is there any SE_SET... command to visualize the past trajectory?

regarding the planned trajectory (yes, i am doing trajectory planning for controlling one vehicle), my planner outputs the optimal trajectory. In this way, it there any intutive way to visualize the optimal trajectory? I think modifying the .xosc file in the runtime will not work.

Thanks a lot!
Best Regards
Cheng

**Comment by ChengWang2018** [comment]
Thanks a lot! The answers are very helpful!
