### ISSUE TITLE
OpenDriveViewer fails to load example ODR file

### ISSUE THREAD

**Issue by BrianHoltPP** [esmini/esmini#47]
System: Ubuntu 18.04
Followed the build instructions [here](https://github.com/esmini/esmini/blob/master/docs/BuildInstructions.md).

From the top level directory, I ran the following command `$ ./build/EnvironmentSimulator/OpenDriveViewer/OpenDriveViewer -odr ./resources/xodr/jolengatan.xodr`.

My expectation would be that the ODR viewer should be able to load and visualise the ODR file. Instead, there is an error message:

```
esmini GIT REV: 46de6c5
esmini GIT TAG: v1.7.13
esmini GIT BRANCH: tags/v1.7.13^0
esmini BUILD VERSION: N/A - client build
density: 1.00
global speed factor: 1.00
osi_features: off
Failed to load ODR
```

**Comment by eknabevcc** [comment]
Definitely it should work for you. Please have a look at the examples provided in the run/OpenDriveViewer folder, e.g. run_e6mini.bat. They will probably not run on Linux, but you can see the options you have in terms of arguments. You can also run "OpenDriveViewer" (with no arguments) it should show Usage info.
**I think the issue might be -odr. Try --odr.**
I hope that helps. Otherwise please let me know and I will investigate to catch the problem.

**Comment by BrianHoltPP** [comment]
> **I think the issue might be -odr. Try --odr.**

Thanks for your reply. This was it. My fault for not paying more attention to the options screen.
