### ISSUE TITLE
DLL usage in Python

### ISSUE THREAD

**Issue by kancanaraa** [esmini/esmini#488]
Hi, 

I have two question about esminiLib.dll usage in python.

1st question: can we define          
  ```
 if (SE_Env::Inst().GetDatFilePath().empty())
            {
                datFilename = FileNameWithoutExtOf(oscFilename) + ".dat";
            }

``` 
this in python?

esminiLib.cpp:
```
SE_DLL_API int SE_Init(const char *oscFilename, int disable_ctrls, int use_viewer, int threads, int record)
    {
#ifndef _USE_OSG
        if (use_viewer)
        {
            LOG("use_viewer flag set, but no viewer available (compiled without -D _USE_OSG");
        }
#endif
        resetScenario();

        AddArgument("esmini(lib)");  // name of application
        AddArgument("--osc");
        AddArgument(oscFilename, false);

        if (record)
        {
            AddArgument("--record");
            std::string datFilename;
            if (SE_Env::Inst().GetDatFilePath().empty())
            {
                datFilename = FileNameWithoutExtOf(oscFilename) + ".dat";
            }
            else
            {
                datFilename = SE_Env::Inst().GetDatFilePath();
            }
            AddArgument(datFilename.c_str(), false);
        }

        AddCommonArguments(disable_ctrls, use_viewer, threads, record);
```

2nd question: Can we directly export csv instead of saving dat file?
```
            dll_name = "esminiLib.dll"
            esmini_bin_dll = os.path.join(esmini_bin, dll_name)
            se = ctypes.CDLL(esmini_bin_dll)
```

**Comment by eknabevcc** [comment]
### 1. Specify dat filename from Python
I hope I understood the question right as how to specify .dat filename 
Try this code:
``` Python
import ctypes
from sys import platform

if platform == "linux" or platform == "linux2":
    se = ctypes.CDLL("../bin/libesminiLib.so")
elif platform == "darwin":
    se = ctypes.CDLL("../bin/libesminiLib.dylib")
elif platform == "win32":
    se = ctypes.CDLL("../bin/esminiLib.dll")
else:
    print("Unsupported platform: {}".format(platform))
    quit()

se.SE_StepDT.argtypes = [ctypes.c_float]

se.SE_SetDatFilePath(b"kalle.dat")

se.SE_Init(b"../resources/xosc/cut-in.xosc", 0, 1, 0, 1)

while se.SE_GetQuitFlag() == 0:
    se.SE_StepDT(0.05)
```

It will first specify the dat filename, in this case "kalle.dat". It has to be done before calling SE_Init(). Also note that last argument need to be 1 in order to activate dat recording.

### 2. Export csv directly
There are two different ways to create csv files in esmini. 
1. From dat recording, via dat2csv.py script. It can be done only after dat file has been created.
2. using `--csv_logger <filename>` launch argument. It will create a different, more elaborate, csv file including more information than the dat converted csv file. Try:
`./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc --csv_logger kalle.csv`
There is no API call for activating this csv_logger, but it can be solved by initializing esmini with argument list. See examples in User guide:
 [Initialize esmini by flexible argument list](https://esmini.github.io/#_initialize_esmini_by_flexible_argument_list) 
 [Forward command line arguments](https://esmini.github.io/#_forward_command_line_arguments).

**Comment by kancanaraa** [comment]
That works for me. Thanks a lot!

**Comment by ufukbolat1** [comment]
Hi,
Assuming the .xosc file does not have any stop trigger so it means the simulation will run forever. Is it possible to add some "time" limitation with using this proposed approch? (lets say 15 seconds etc.)
