### ISSUE TITLE
osi3::TrafficCommand output in OSMP FMU

### ISSUE THREAD

**Issue by ClemensLinnhoff** [esmini/esmini#499]
OSMP Traffic Participant models are able to optionally receive [osi3::TrafficCommand](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/gen/structosi3_1_1TrafficCommand.html) data next to the standard osi3::SensorView, according to the [OSMP model type specification](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/sensor-model/spec/model_types.html).

The TrafficCommand message contains actions, that align with the OpenSCENARIO definitions, e.g. speed actions or lane change actions. The idea is, that a scenario player reads these actions from an OpenSCENARIO file and passes them along to a traffic participant model.

I would like to implement this functionality in the OSMP FMU, in fact I already started, see #498.
I implemented the OSMP parameters and a minimal working example with a hardcoded traffic action after 20 s simulation time. It works well together with the [traffic participant model template from OpenMSL](https://github.com/openMSL/sl-2-0-traffic-participant-model-repository-template).

The next step is to get the actual traffic actions from esmini/OpenSCENARIO. Could you give me some guidance, on how to access the actions via the esmini API from within the OSMP FMU? Does this interface exist in the current API? Or does it make sense to write an SE_GetOSITrafficUpdate() function? Is there a way to prevent the corresponding vehicle in esmini from executing the action and leave it to the external traffic participant model? Or does this not matter, because the traffic participant model will override the object state anyways?

**Comment by ClemensLinnhoff** [comment]
I added an example scenario to a [test case of the traffic participant model](https://github.com/openMSL/sl-2-0-traffic-participant-model-repository-template/blob/3-trafficcommand-and-trafficcommandupdate/test/integration/003_integration_test_traffic_command/control_scenario.xosc). After 10 s, there is a speed action, which should be the output of the TrafficCommand message.

**Comment by ClemensLinnhoff** [comment]
@eknabe any thoughts on this feature?

**Comment by MandolinMicke** [comment]
If they are part of OSI, shouldn't those be added to the OSI Reporter?

**Comment by ClemensLinnhoff** [comment]
> If they are part of OSI, shouldn't those be added to the OSI Reporter?

Well they belong to OSI, but they contain OpenSCENARIO actions. And I think to OSI Reporter only reports and cannot take any feedback, right?

**Comment by MandolinMicke** [comment]
I was reacting to this 

> The next step is to get the actual traffic actions from esmini/OpenSCENARIO

Which I interpred as esmini sends the action as OSI with "SE_GetOSITrafficUpdate"?

**Comment by MandolinMicke** [comment]
Is the idea to get the osi::TrafficCommand for one object, or all objects at the same time?

**Comment by ClemensLinnhoff** [comment]
This is only relevant for the ego vehicle for now. The idea is to get the command from the OpenSCANERIO for the ego vehicle and have an external vehicle dynamics model calculate the position and orientation of the ego vehicle for every time step based on the TrafficCommand input.

**Comment by MandolinMicke** [comment]
Hmm, ok, so techincally you just want the active action at any time step. Sounds very much like how the OSIReporter works right now (which is good)

Me and Emil had a short discussion about it yesterday, and he was gonna dig into some small things for it.

**Comment by eknabevcc** [comment]
Branch [feature/osi_traffic_cmd](https://github.com/esmini/esmini/tree/feature/osi_traffic_cmd) includes a proof of concept implementation, including a few things to get started. 

- each action will now have a unique ID 
- each time an action is triggered, it is also propagated for OSI report (but action will reuse ID for any re-runs - as for now)
- actions are then reported with a and eventually reported as a TrafficCommand. 
- only three actions implemented in this POC serving as examples
- recent storyboard refactorization supports the push-approach instead of trying to poll for started actions (where atomic actions, starting and stopping in the same timestep, could be missed)

I was not totally sure how to deal with decoding of the TrafficCmd message. See my best effort in code example: [code-examples/osi-traffic_command](https://github.com/esmini/esmini/tree/feature/osi_traffic_cmd/EnvironmentSimulator/code-examples/osi-traffic_command)

If you build this branch of esmini yourself, the example should end up in `esmini/code-examples-bin/osi-traffic_command`

Please have a look. If the approach seems OK we'll merge to dev branch.

**Comment by ClemensLinnhoff** [comment]
Awesome, this is exactly, what I need @eknabevcc. Thank you very much! I took the liberty and merged [feature/osi_traffic_cmd](https://github.com/esmini/esmini/tree/feature/osi_traffic_cmd) into a new branch [feature/osi_traffic_cmd_OSMP](Persival-GmbH:feature/osi_traffic_cmd_OSMP) so I can add the OSMP stuff to support TrafficCommand output. I already created a [PR](https://github.com/esmini/esmini/pull/528) to merge into dev.

I also used the branch for an integration test of the [traffic participant model template](https://github.com/openMSL/sl-2-0-traffic-participant-model-repository-template) in OpenMSL in a closed-loop simulation. The [output of the traffic participant model in the co-simulation](https://github.com/openMSL/sl-2-0-traffic-participant-model-repository-template/actions/runs/7729598273/job/21073299626#step:16:385) shows, that it received the traffic command from esmini. I also tested locally, that it can act on the action and control / overwrite the ego vehicle position with the TrafficUpdate feedback to esmini.

**Comment by ClemensLinnhoff** [comment]
In OSI there is also the option to do this the other way around, so send a TrafficCommandUpdate from a model to esmini. esmini can then perform the received actions, that are not predefined in the OpenSCENARIO file. But I would merge this as is for now and then tackle this other possibility later.

**Comment by eknabevcc** [comment]
True, I also saw this feature that the external traffic simulator can communicate updates back to esmini. Maybe this is to support a use case where traffic commands are actually performed by an external simulator... So far esmini is only reporting what's going on inside.

But, yes, I agree. Let's get this first baby step done before moving forward. 👍

**Comment by ClemensLinnhoff** [comment]
@eknabevcc I have a couple of follow up questions just as a clarification:

1) You wrote:
> each time an action is triggered, it is also propagated for OSI report (but action will reuse ID for any re-runs - as for now)

What do you mean by re-runs? Starting a scenario again after it finished? Then I think reusing the same IDs is actually the expected behavior, right?

2) You wrote 
> recent storyboard refactorization supports the push-approach instead of trying to poll for started actions

What do you mean by push-approach? By calling the SE_UpdateOSITrafficCommand function we are actually polling, right?

**Comment by eknabevcc** [comment]
> @eknabevcc I have a couple of follow up questions just as a clarification:
> 
> 1. You wrote:
> 
> > each time an action is triggered, it is also propagated for OSI report (but action will reuse ID for any re-runs - as for now)
> 
> What do you mean by re-runs? Starting a scenario again after it finished? Then I think reusing the same IDs is actually the expected behavior, right?

Yes, that's the idea. And I also think it makes sense. But could be changed in future if we see a need.

> 2. You wrote
> 
> > recent storyboard refactorization supports the push-approach instead of trying to poll for started actions
> 
> What do you mean by push-approach? By calling the SE_UpdateOSITrafficCommand function we are actually polling, right?

I understand the terminology is not perfect. I'll try to describe: The initial idea from our side was to first run the storyboard step, and afterwards poll the storyboard for any started or running action. However, in edge cases an action could already be done - like a teleport which is done in one step. So it moves from standby to finished via running in the same timestep. That's why we went for the approach to push events to a list which the OSI reported then can consume. That way nothing is missed.

Note that the implementation was done quickly as a prototype/poc. If you see some unexpected behavior it could be some flaw in the implementation. Please report any such observations.

**Comment by ClemensLinnhoff** [comment]
That makes sense (both). Thank you for the clarification!
