### ISSUE TITLE
object type (ped/veh) from SE_GetObjectState in esminiLib

### ISSUE THREAD

**Issue by tlever** [esmini/esmini#50]
Hi, 
Great to see esmini continue to extend in capability. I'm investigating the use of recent addition of Pedestrian OpenSCENARIO support using the esminiLib library and am not able to find a way to differentiate between pedestrian and vehicle actors when querying SE_GetObjectState.
The use case is actors in a 3rd party simulation tool being moved by esminiLib position updates and the ego vehicle in the 3rd party simulation tool providing input to the esminiLib via SE_ReportObjectPos. Without comprehension of the OpenSCENARIO the 3rd party simulation tool has is unable to tell which actors are pedestrians and which are vehicles.
I will continue to investigate this issue and report any useful findings but just wondered if there are any suggestions or if this functionality is on a development roadmap at all?

Thanks for all the work that goes into esmini,
Tom

**Comment by tlever** [comment]
Ensuring consistent use of model_id for pedestrian and vehicle is a way to resolve this.
model_id is then available from SE_GetObjectState

**Comment by eknabevcc** [comment]
Very good point, information of object type is definitely missing. 

I thought about this over lunch :). The state structs can, and probably should, be updated. However, since they are part of the library we try to minimize changes to the interface (functions and data types). 

Interesting, I also thought about looking at the model_id. The initial purpose of this attribute is to agree, between esmini and external simulator, upon what geometric 3D model to use for an object. There is no standard, only like a contract between the scenario author (writing model_id in the Vehicle element) and the simulation tool. 

And as you found out: A possible solution is to establish a table, like 
model_id 0 is car_0 
model_id 1 is car_1
...
model_id 7 is pedestrian_0
model_id 8 is pedestrian_1
...
model_id 15 is moose_0
...

or perhaps:
model_id < 100 is of type car
100 > model_id < 200 is type pedestrian
200 > model_id < 300 is type animal

Anyway, I will bring the question of adding object_type as a separate attribute in the SE_ScenarioObjectState. It will probably make sense in the long run. Could be added in a upcoming version 2.1 or something (perhaps bundle with other interface requests). But let's keep API as is for now and try to make use of the model_id as you propose as well.

Let's keep the ticket open until we see that it works as is. 👍

**Comment by eknabevcc** [comment]
Revisiting this issue I realize that object type and category, according to the [OpenSCENARIO standard](https://www.asam.net/static_downloads/modelDocumentation/content/EntityObject.html), has been added to the [SE_ScenarioObjectState struct](https://github.com/esmini/esmini/blob/2d953a8f50da8a78ffa9f1f22ef06abbb99d9347/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L48) months ago. 
Closing the issue.

**Comment by eknabevcc** [comment]
I modified the [hw3_fetch_states.cpp](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/code-examples/hello_world/hw3_fetch_states.cpp) example. More specifically changed the printf statement into:

```c++
printf("time [%.2f] object[%d] id %d pos[%.2f, %.2f] %.2f %.2f type %d category %d\n",
       static_cast<double>(state.timestamp),
       j,
       SE_GetId(j),
       static_cast<double>(state.x),
       static_cast<double>(state.y),
       static_cast<double>(state.wheel_angle),
       static_cast<double>(state.wheel_rot),
       state.objectType,
       state.objectCategory
    );
```

Then made following adjustment in the VehicleCatalog file (line 59):
```xml
<Vehicle name="car_red" vehicleCategory="bus" model3d="../models/bus_blue.osgb">
```

Then I get output like:
```
time [0.63] object[0] id 0 pos[8.25, 68.87] -0.00 3.73 type 1 category 0
time [0.63] object[1] id 1 pos[4.59, 47.63] -0.00 1.87 type 1 category 5
```
Type 1 means `vehicle`
Category 0 means `car`
Category 5 means `bus`

So it should be populated, looks OK. 

Can you specify what esmini version you run and perhaps you can share the catalog file you're using. And finally, are you using some wrapper for esminiLib? Potentially it is out of synch - maybe structs not matching?

**Comment by eknabevcc** [comment]
@ntutangyun I see that the question was withdrawn, I hope that means that it all works for your use case as expected. Otherwise, just get back and we'll sort it out.

**Comment by eknabevcc** [comment]
Ah, I see. Thanks for info!
