### ISSUE TITLE
routing problem in my scenario

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#501]
I designed a route of car1 is as follows.

I use my design tool as scenario designer which is AVL tool, and online OpenDrive Viewer(https://odrviewer.io/)

![image](https://github.com/esmini/esmini/assets/111849721/eba5eb6f-5efd-41cb-960f-1246906eee10)

I don't know why car1 is moving straight like picture.

Please let me know what I am missing.

Thanks.

[myscenario.zip](https://github.com/esmini/esmini/files/13507691/myscenario.zip)

**Comment by eknabevcc** [comment]
I think the issue is how waypoints are specified. World Coordinates can be ambiguous where overlapping roads, e.g. in intersections. This might be the root cause of the problem.

Then I also would recommend to keep waypoints to a minimum, and let esmini find the shortest route between them.

In your case you have a lane change that moves the car from one lane to another. That should be fine, as long as the waypoints are defined in expected lanes accordingly. 

The very best is to define waypoints in terms of lane positions. But world coordinates is also fine, just that you have to be slightly more careful.

Please find attached minimalistic example. I cut down the route to just the first part, and reduced number of (world coordinate) waypoints to three. They are encircled in the image below. The two additional is added by esmini on roads between specified waypoints (intermediate waypoints).

![img](https://github.com/esmini/esmini/assets/29146839/287bd4ad-0a61-4870-86e2-9c76ebee0be4)

Hopefully this can give you idea on how to proceed with the complete route.

**Comment by victor0777** [comment]
Hi Emil,
Thanks for your response, and it helps a lot.

![image](https://github.com/esmini/esmini/assets/111849721/be51ed37-82a1-4f40-aa6c-1fe39182cbf5)

I found one more thing. I modified a scenario, but I made a mistake. The picture below is a result.

It would be nice if you play my scenario. I know what should I do.
[Scenario2_CarlaTown10_Release1_victor.zip](https://github.com/esmini/esmini/files/13722832/Scenario2_CarlaTown10_Release1_victor.zip)

**Comment by eknabevcc** [comment]
Thanks for reporting this issue and providing good examples and input!

Indeed there were a few issues related to routing. Especially when position is not actually on the route path. One such case is when the car is initialized at a position before the first waypoint. Another case was when the car deviated from the route, e.g. after going another path in an intersection, enforced by lane connectivity.

Based on this we have improved routing handling in release [v2.36.0](https://github.com/esmini/esmini/releases/tag/v2.36.0).

Hopefully it solves at least some of the problems.

**Comment by victor0777** [comment]
Hi, Emil.
It works well.
I appreciate your support.

https://lnkd.in/gh9hNy3n
