### ISSUE TITLE
Cars don't move at the specific spot.. 

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#505]
Hi,

I designed two vehicles and populate 10 vehicles for each vehicles.

initial positions of cloned vehicles are changed.

After time goes, vehicles are stopped at the specific spot.

![image](https://github.com/esmini/esmini/assets/111849721/4878300e-f810-40c9-8545-0d89a2431b20)

[car2_population.zip](https://github.com/esmini/esmini/files/13680015/car2_population.zip)

I hope this contribute to detect some bugs.

**Comment by victor0777** [comment]
It seems that it occurred due to routing problem.

I attach my new scenario, I tried to run without assigning routing then it runs well. but after assigning route, they stops.
[Scenario2_CarlaTown10_Release4_car4_acc_dec.zip](https://github.com/esmini/esmini/files/13682152/Scenario2_CarlaTown10_Release4_car4_acc_dec.zip)

so in my thought, this is a symptom due to routing problem.

**Comment by victor0777** [comment]
I tested more with many vehicles today, and it occurred again without assigning routes.

**Comment by eknabevcc** [comment]
I think the reason for cars getting stuck at road 22, at the border to the junction, is to be found in the OpenDRIVE file. 

When cars driving along road 22 in opposite direction reaches the start-point of the road, there's no valid connection. The OpenDRIVE says "go to junction 23". But in that connection table there are no incoming road 22. That's why they get stuck, nowhere to go...

Find attached modified OpenDRIVE, where I added a few missing connections. 
[Carla - Town10HD_fixed.zip](https://github.com/esmini/esmini/files/13818030/Carla.-.Town10HD_fixed.zip)

**Comment by victor0777** [comment]
Hi Emil,
Thanks for your support. it works.
