### ISSUE TITLE
driving error in test driver code

### ISSUE THREAD

**Issue by victor0777** [esmini/esmini#519]
Hi, 
I found a simptom. 
I slightly changed a test-driver.cpp, and I played my open scenario file, but it drives weirdly.

key code seems to be SE_GetRoadInfoAtDistance function.

`SE_GetRoadInfoAtDistance(0, lookahead_distance, &roadInfo, 0, true);`

![image](https://github.com/esmini/esmini/assets/111849721/f38403e6-d7dc-4b1c-a016-68d46aee24fa)
![image](https://github.com/esmini/esmini/assets/111849721/601d25c8-cc9e-40e5-b9d3-d80f24bd9721)
[test-driver.zip](https://github.com/esmini/esmini/files/13944607/test-driver.zip)

I attach my code, scenario and trace log.

reason is that steering depends on roadinfo.angle, and I think roadInfo.angle has an error.

**Comment by eknabevcc** [comment]
Before looking further, I want to make sure you have the correct understanding of the RoadInfo.angle. It represents the direction, from vehicle to the point ahead, relative vehicle heading. So if vehicle turns, the angle will change. 

Will that explain your findings?

Some more info can be found here: https://esmini.github.io/#_the_ghost_concept

BTW: A typical use case is to use that angle as input to the steering control, typically with opposite sign since we want to reduce that angle.

**Comment by victor0777** [comment]
I copy some codes from test-driver.cpp. it is original code.

In below, value of roadInfo.angle is assigned to steerAngle.

from the code, I assumed that roadInfo.angle guides steerAngle.


`// Steer towards where the point
            double steerAngle = roadInfo.angle;

            // Accelerate or decelerate towards target speed - THROTTLE_WEIGHT tunes magnitude
            double throttle = throttleWeight * (targetSpeed - static_cast<double>(vehicleState.speed));

            // Step vehicle model with driver input, but wait until time > 0
            if (SE_GetSimulationTime() > 0 && !SE_GetPauseFlag())
            {
                SE_SimpleVehicleControlAnalog(vehicleHandle, dt, throttle, steerAngle);
            }

            // Fetch updated state and report to scenario engine
            SE_SimpleVehicleGetState(vehicleHandle, &vehicleState);

            // Report updated vehicle position and heading. z, pitch and roll will be aligned to the road
            SE_ReportObjectPosXYH(0, 0, vehicleState.x, vehicleState.y, vehicleState.h);

            // The following values are not necessary to report.
            // If not reported, esmini will calculate based on motion over time
            // but for accuracy it's recommendeded to report if available.

            // wheel status (revolution and steering angles)
            SE_ReportObjectWheelStatus(0, vehicleState.wheel_rotation, vehicleState.wheel_angle);

            // speed (along vehicle longitudinal (x) axis)
            SE_ReportObjectSpeed(0, vehicleState.speed);

            // Finally, update scenario using same time step as for vehicle model
            SE_StepDT(dt);
        }
        SE_Close();
    }
    return 0;
}`

**Comment by eknabevcc** [comment]
True, I was unclear. The angle can be used to influence the steering, and if successful the magnitude of the `angle` should decrease. In other words, it's the difference between vehicle heading and angle to the target point that should be reduced. So, yes, you can use the angle directly as input to steering.

I hope you have info enough to solve the issue. Otherwise you can share the code and we can have a look and test it.

**Comment by victor0777** [comment]
Thanks for your kind explanation.
I understand your point.
