### ISSUE TITLE
openX version

### ISSUE THREAD

**Issue by yumianhuli2** [esmini/esmini#53]
Hello!
What about the version of Opendrive and openScenario?
Are they compatible with previous versions？
Thank you！

**Comment by eknabevcc** [comment]
esmini supports only OpenSCENARIO 1.0. But not all of it. Please see [osc_coverage.txt](https://github.com/esmini/esmini/blob/master/osc_coverage.txt) for current rough features coverage.
Up to version 1.4 esmini only supported 0.9.1 - and since 1.5 only 1.0. 

Regarding OpenDRIVE. We based it on OpenDRIVE 1.4. And once again, supporting a subset of the format. Unfortunately it's not documented what parts are missing. Since OpenDRIVE 1.5 and 1.6 is backward compatible our idea is to implement nice-to-have features of those versions when needed. But since it will not be full coverage it will then be a mix of 1.4 and forward.  

I hope this answer brings more clarification than confusion :)
