### ISSUE TITLE
Question: Loading a CityGML dataset

### ISSUE THREAD

**Issue by jdsika** [esmini/esmini#54]
I am tagging this repository with [CityGML files](https://github.com/savein/lod3-road-space-models) to connect some dots here.
What do you think about the idea of supporting those files of the city Ingolstadt and combining it with a set of open source scenarios like the ones from ALKS? Now even thinking one step further esmini could support the format of glTF, auto-convert the CityGML files and add the idea of material datasets with the [OpenData](https://github.com/LudwigFriedmann/OpenMaterial) extension?

**Comment by eknabevcc** [comment]
Wow. I think this sounds like a great idea. Almost a no-brainer! 👍
After quick investigation it seems like actual 3D models would be no problem. However I'm thinking about OpenDRIVE, do you know if Ingolstadt roads are available in OpenDRIVE format?
Then the glTF sound also interesting, something we should look into sooner or later anyway...
But let's check the OpenDRIVE availability first. Then I can discuss this topic with colleagues.  👍

**Comment by jdsika** [comment]
I am tagging @b-schwab here. I "thought" both would be available

**Comment by b-schwab** [comment]
Great idea @jdsika! We would highly appreciate the use of our [CityGML dataset](https://github.com/savein/lod3-road-space-models) within the esmini project. :+1:
The [libcitygml](https://github.com/jklimke/libcitygml) library could be interesting.


@eknabe Yes, we have a multitude of OpenDRIVE datasets for Ingolstadt which have been created by the company [3D Mapping Solutions GmbH](https://www.3d-mapping.de/en/our-service/ultra-hd-maps/). The LoD3 models are actually modelled complementary to the OpenDRIVE dataset:
![inspection-opendrive-lod3](https://user-images.githubusercontent.com/9211132/100391244-23fa3e80-3033-11eb-86c7-2c5a6fb3abb6.png)
The roads in this picture were converted with [rtron](https://rtron.io) from OpenDRIVE to CityGML. The LoD3 building models were [manually created](https://creating-citygml-datasets.readthedocs.io/en/latest/creation-guidelines/lod3-models-based-on-point-clouds.html) based on the same mobile laser scans as the OpenDRIVE dataset and then combined with [FME](https://www.safe.com/fme/fme-desktop/).

@LutzMorich and I are currently in discussions with 3D Mapping Solutions whether it is possible to release the relevant OpenDRIVE datasets as open data to foster such endeavors.

**Comment by jdsika** [comment]
> LutzMorich and I are currently in discussions with 3D Mapping Solutions whether it is possible to release the relevant OpenDRIVE datasets as open data to foster such endeavors.

This would be very useful! As is is already "part of the open source product" it could maybe be added to the repository? It would also be interesting to see what rtron did with OpenDrive (unknown changes/transformations/cutting of details)

**Comment by eknabevcc** [comment]
Ah, many projects and technologies involved - of most I haven't heard about before. Trying to sort it all out: OpenDRIVE data has been used in the process of generating the road geometry, but the CityGML dataset does not include OpenDRIVE or any other semantic model of the road network? So yes, one key element would be the OpenDRIVE data (not having to reverse engineer that part from CityGML),
Maybe instead of bringing CityGML to esmini, esmini could be integrated in a web service connecting it all together...? User could choose location and scenario from a presets menu. (possibly provide some support for manipulating/creating scenarios).
That could also be a way of moving focus from esmini to the data providers.
I will have a closer to the rtron.io project - as a first step I think. Then digest...
Cool idea regardless 👍

**Comment by b-schwab** [comment]
Maybe a bit of background information: [We](https://save-in.digital/en/partner/) are currently building a digital twin of the city of Ingolstadt and prepare it (inter alia) for the testing and development of automated driving functions. Therefore two worlds meet here: semantic 3D city models and automotive simulation/testing. :smile: 
Recently I held a short online presentation explaining the different datasets/methods and tools: https://www.youtube.com/watch?v=0g7ECPEmFsE 

So first, 3D Mapping Solutions surveyed the streets in Ingolstadt and created OpenDRIVE datasets.
However, the standard OpenDRIVE lacks the capability to model e.g. detailed facades of buildings.
Therefore, we modelled the missing details (without the streets) in CityGML and released it as [open data](https://github.com/savein/lod3-road-space-models).
In order to have a complete representation of the road space in CityGML, the streets and road objects like trees, traffic signs and so on are transformed from OpenDRIVE to CityGML by [rtron.io](https://rtron.io). For combining the CityGML datasets and  replacing with higher detailed models (like 3D tree models, traffic sign models) we currently use the tool [FME](https://www.safe.com/fme/fme-desktop/).

@jdsika 
> This would be very useful! As is is already "part of the open source product" it could maybe be added to the repository? It would also be interesting to see what rtron did with OpenDrive (unknown changes/transformations/cutting of details)

I absolutely agree. :+1: Moreover, it could be interesting for the standardization of OpenDRIVE in ASAM, where they want to reference external environment models (including CityGML) within OpenDRIVE.

**Comment by jdsika** [comment]
Btw a tool to convert CityGML to gLTF can be found [here](https://www.lrg.tum.de/gis/projekte/3dcitydb/)

**Comment by b-schwab** [comment]
Update regarding the OpenDRIVE dataset: 3D Mapping Solution will provide the corresponding OpenDRIVE dataset as a demo dataset on [their website](https://www.3d-mapping.de/en/customer-area/) soon.

**Comment by eknabevcc** [comment]
Or by the way, perhaps someone knows about any initiative to extract OpenDRIVE from CityGML? If the CityGML road info is based on OpenDRIVE it may be a bit silly to reverse-engineer the OpenDRIVE, but if the CityGML road data is based on other sources it could make sense.

**Comment by eknabevcc** [comment]
In lack of complete OpenDRIVE data set and/or ideas on how to extract OpenDRIVE from CityGML, I close this issue for now. It can always be re-opened later.

**Comment by b-schwab** [comment]
3D Mapping Solutions GmbH now provides the complementary OpenDRIVE dataset on their [website](https://www.3d-mapping.de/en/customer-area/) (:clap: kudos to 3D Mapping). It can be found within the demo data section (initial registration is required) and the dataset is namend *Ingolstadt Innercity City Halls*:

![Screenshot from 2021-06-18 09-53-40](https://user-images.githubusercontent.com/9211132/122527049-41b4e280-d01b-11eb-8be7-ae88729220f3.png)

@eknabevcc and @jdsika: Now we should have all the relevant models to run scenarios in the city center of Ingolstadt using esmini, right?

**Comment by esmini** [comment]
This is good news! 
I thought this case was cold. We didn't really start any work on this since key input was missing. And I haven't planned any work on this in near time. But of course, now we should look into it again, to see what efforts are required to put stuff together. Maybe summer brings some rainy days :)
I open the issue again.

**Comment by eknabevcc** [comment]
This is good news!
I thought this case was cold. We didn't really start any work on this since key input was missing. And I haven't planned any work on this in near time. But of course, now we should look into it again, to see what efforts are required to put stuff together. Maybe summer brings some rainy days :)
I open the issue again.

**Comment by jdsika** [comment]
Unfortunately there is no license on the data or am I missing the disclaimer?

**Comment by eknabevcc** [comment]
Ah, yes. And I remember I saw this before. My impression is that it's a limited area, a few blocks of OpenDRIVE data.
I think it makes more sense to put efforts in this when we have a large scale OpenDRIVE data at hand, somehow.
