### ISSUE TITLE
Inconsistent definition for ElementType and State in esminiLib.hpp

### ISSUE THREAD

**Issue by wubinwab** [esmini/esmini#541]
I find there is Inconsistent definition of ElementType and State in esminiLib.hpp compared to StoryboardElement.cpp
![image](https://github.com/esmini/esmini/assets/161703216/6e96cdba-95b7-487d-a871-b50cdda52039)
![image](https://github.com/esmini/esmini/assets/161703216/1b4c5aa3-075e-4778-bf6a-fe414347e250)

**Comment by eknabevcc** [comment]
Good finding! 

This is what happens when adding duplicate information, hard to keep in synch. As a mitigation we now removed this info, instead referring to the original source of information. I.e. the enums in corresponding esmini header file.

Not perfect solution, but outdated info is worse. 

Fixed by commit 8baa199fb3a5b49c7dfb3accf33be5a3410241f7. Included in release [v2.37.1](https://github.com/esmini/esmini/releases/tag/v2.37.1).

Thanks for report.
