### ISSUE TITLE
replayer shows the wrong entities

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#547]
Hi,

in original esmini simulation it is a bike included, in the resimulation of replayer (esmini headless with --record) it is simply a narrow car.

BR,

Thaddaeus

**Comment by eknabevcc** [comment]
replayer shows model based on model_id. Make sure the model_id in the scenarioObject matches the intended model as specified in [model_ids.txt](https://github.com/esmini/esmini/blob/dev/resources/model_ids.txt).

For example, the bicycle in [VehicleCatalog.xosc](https://github.com/esmini/esmini/blob/dev/resources/xosc/Catalogs/Vehicles/VehicleCatalog.xosc) has model_id = 9, which corresponds to cyclist.osgb.

Why store a number instead of simply the filename? It's a long story 🙂, but a nice feature is that you CAN use different models, e.g. of different fidelity, when replaying scenarios - by applying different model_id configurations.

**Comment by tmIdiada** [comment]
sorry should have searched for the issue first, for sure already existing in the issue list multiple times. Thanks

**Comment by eknabevcc** [comment]
No problem, this should be better documented. So the question is legit.

**Comment by tmIdiada** [comment]
Hi,

whenever you have too much time, maybe you could implement a check in esmini to throw a warning if the esmini osgb are used but the model ids are mismatching the corresponding ones.

BR

**Comment by eknabevcc** [comment]
Good point. Noted.

**Comment by eknabevcc** [comment]
Fixed in release [v2.37.5](https://github.com/esmini/esmini/releases/tag/v2.37.5)
