### ISSUE TITLE
why esmini is behaving different for same scenario (OpenDRIVE independent by global coordinates) for 2 different OpenDRIVE?

### ISSUE THREAD

**Issue by tmIdiada** [esmini/esmini#574]
I have the same scenario only with global coordinates for trajectories and in principle I should need no underlying road network, but I have 2 different ones just different in number of lanes and lane types

test1:
![grafik](https://github.com/esmini/esmini/assets/78544110/6f49db3e-95e4-481b-869d-353b8ab6e9a9)
test2:
![grafik](https://github.com/esmini/esmini/assets/78544110/d28b7165-bb43-404d-be7c-faa4a75ebb3b)

[test1VStest2.zip](https://github.com/esmini/esmini/files/15487684/test1VStest2.zip)

Do you have any explanation?

BR,

TM

**Comment by eknabevcc** [comment]
It's tricky to explain. But I'll try. 

### Short answer
When entering the intersection esmini will guess what road to belong to. Once choice is made, it will stick to that road as long as the entity is within the boundaries of that road. When the trajectory action ends, esmini will move the entity along the "current" road. Which in the second case unfortunately is still the straight road in the intersection (road id 101). See image below. 

![Image](https://github.com/esmini/esmini/assets/29146839/3d10c48d-41c0-48bf-b14a-2d8b1558e024)

Unfortunately I see no simple fix for this limitation of esmini. But a quick fix is to extend the trajectory to clearly reach into road 1, leaving boundaries of connecting roads of the intersection. Like in attached [test2_mod.zip](https://github.com/esmini/esmini/files/15500121/test2_mod.zip).

### Long answer

When specifying trajectories in terms of lane coordinates it is no doubt what lane the entity is driving in, it's given. However, with world positions - such in this case - esmini will try to resolve what road and lane a given world position belongs to.

Normally it's an easy task to find out. But in intersections it's a bit trickier. The current approach is very simple, and hence limited: When entity enters an intersection it will pick one road, of potentially multiple options (prioritizing all roads connected to the road in previous step). Then the entity will stick to that road until it is clearly, by margin, closer to another road. 

The following two images illustrates the above:

![Image](https://github.com/esmini/esmini/assets/29146839/bf3a6c8a-284f-4127-aa11-de955e56590f)

esmini selected (unfortunately) road 101 (straight) instead of 100 (right) in the intersection. Once that choice was done, the entity sticks to road 101, even if the distance to lane-center of road 100 becomes smaller. 

When entity moves outside boundaries of road 101 esmini will consider 100 as well. But even now, the current road (101) have some extra weight. 

![Image](https://github.com/esmini/esmini/assets/29146839/5a839561-6ed6-4aeb-905f-7f88abb3bdce)

Eventually, when the distance to 100 is clearly, by margin, smaller than to 101 esmini will accept and snap to 100 instead.

**Comment by eknabevcc** [comment]
BTW. Of course a more elegant solution is to define a simple route for Ego. That way lane belonging is made explicit and esmini don't have to guess.

![Image](https://github.com/esmini/esmini/assets/29146839/45a26142-4ca2-4c16-b191-730d60f6ea58)

Please see updated scenario: [test2_route.zip](https://github.com/esmini/esmini/files/15500276/test2_route.zip).

Route is simply:
```xml
<Route name="EgoRoute" closed="false">
    <Waypoint routeStrategy="shortest">
        <Position>
            <LanePosition roadId="0" laneId="-1" offset="0" s="65"/>
        </Position>
    </Waypoint>
    <Waypoint routeStrategy="shortest">
        <Position>
            <LanePosition roadId="1 " laneId="1" offset="0" s="80"/>
        </Position>
    </Waypoint>
</Route>
```

**Comment by tmIdiada** [comment]
Thanks a lot for the explanation.

The best option for me is the extension of the trajectory since the road network is just a make-up, means the scenario shall work in each case, also without any road network.
