### ISSUE TITLE
How to parsing the Opendrive of “roadMark”.

### ISSUE THREAD

**Issue by funix0** [esmini/esmini#69]
I find other mark of “roadMark”.  
Is this another version of opendrive?  How to parsing and compatible ?

It not have subset of “type” and “line”.
\<roadMark sOffset="0.0000000000000000e+00" type="solid" weight="standard" color="yellow" width="1.4999999999999999e-01" laneChange="both" /> 

\<roadMark sOffset="0.0000000000000000e+00" type="broken" weight="standard" color="standard" width="1.2000000000000000e-01" laneChange="none" height="1.9999999552965164e-02" >

                          <type name="broken" width="1.2000000000000000e-01" >
                               < line length="4.0000000000000000e+00" space="8.0000000000000000e+00" tOffset="0.0000000000000000e+00" sOffset="0.0000000000000000e+00" rule="caution" width="1.2000000000000000e-01"/>
                           </type>

\</roadMark>

![roadmak1](https://user-images.githubusercontent.com/7670308/104393806-46fb9600-5580-11eb-91a0-4f7c3fb19172.png)
![roadmark33](https://user-images.githubusercontent.com/7670308/104393809-482cc300-5580-11eb-8a82-2ba399014148.png)

**Comment by funix0** [comment]
<roadMark sOffset="0.0000000000000000e+00" type="solid" weight="standard" color="yellow" width="1.4999999999999999e-01" laneChange="both" />

<roadMark sOffset="0.0000000000000000e+00" type="broken" weight="standard" color="standard" width="1.2000000000000000e-01" laneChange="none" height="1.9999999552965164e-02">
                            <type name="broken" width="1.2000000000000000e-01" >
                                <line length="4.0000000000000000e+00" space="8.0000000000000000e+00" tOffset="0.0000000000000000e+00" sOffset="0.0000000000000000e+00" rule="caution" width="1.2000000000000000e-01"/>
                            </type>
</roadMark>

**Comment by funix0** [comment]
Road marks may be further described in terms of their type. Instead of providing additional parameters
to the roadMark tag, type definitions shall be defined as children to the roadMark tag. Each type
definition must contain one or more line definitions with additional information about the lines the
road mark is composed of.
delimiters \<type>...</type>
parent\ <roadMark>

This is new in v1.5.   We now support Opendrive v1.6 ?

**Comment by eknabevcc** [comment]
Thanks for question. RoadMark element is a bit confusing, to me at least since it contains both an attribute named "type" and also an optional sub element named "type". And, as you say, the type sub element contains one or multiple line elements. 
-roadMark 
    -type (0..1)
        -line (1..*)

I interpret this as if no type sub element is provided, then the details are not that important to the user. The type attribute tells only roughly the line configuration, e.g. broken or solid. And it's up to the visualization tool to decide the actual length of lines and gaps in between. The type sub element can be specified when the user need/want to control the exact configuration of the road marking. 

I think the above is the case for v1.4 and v1.5, but I can be wrong. Do you have an other understanding? For v1.6 it might have changed, I simply don't know. 

Anyway, esmini supports (parts of) v1.4. But I can imagine that we add some features from 1.5 and perhaps 1.6 based on need.

**Comment by eknabevcc** [comment]
Did you have a chance to consider last post. I hope it answered your question. In that case we should close the issue. Otherwise, please let me know and we'll sort it out together.

**Comment by eknabevcc** [comment]
Closing issue. Question answered, most likely there is no issue. Otherwise, just re-open and we'll sort it out further.
