### ISSUE TITLE
SpeedActionDynamics sinusoidal

### ISSUE THREAD

**Issue by TKeutgens** [esmini/esmini#70]
It seems that the dynamicsShape sinusoidal is currently not supported for the SpeedActionDynamics.

<SpeedActionDynamics dynamicsShape="sinusoidal" value="Val" dynamicsDimension="rate"/>

Is it possible to add that feature?

**Comment by eknabevcc** [comment]
You're totally right. Thanks a lot for pointing out this issue. Even the [coverage table ](https://github.com/esmini/esmini/blob/master/osc_coverage.txt) was wrong.
It should now be fixed by commit [73e9969](https://github.com/esmini/esmini/commit/73e9969b37f5be1cd5a2994084df2e711f8cf9eb).
Please pull and try. It will be part of next release. Do you need a release to test?

**Comment by TKeutgens** [comment]
Thank you very much for the fix. Unfortunately I'm only working with the prebuild verison. So I would need the release for testing.

**Comment by eknabevcc** [comment]
I see. No problem. We just made a new release, v2.1.4. You find it [here](https://github.com/esmini/esmini/releases/latest).
Please test and see if it works as expected.

**Comment by eknabevcc** [comment]
FYI: Now from [release 2.3.0](https://github.com/esmini/esmini/releases/tag/v2.3.0) also cubic shape is supported.

BTW: Did you have any chance to test the sinusoidal shape for SpeedAction?
If it seems OK I think we can close the issue.

**Comment by TKeutgens** [comment]
Thanks for the update. 

During my tests, the following command works fine
<SpeedActionDynamics dynamicsShape="sinusoidal" value="$Brake_Duration" dynamicsDimension="time"/>

but when I test the cubic command, I can not spot any difference
<SpeedActionDynamics dynamicsShape="cubic" value="$Brake_Duration" dynamicsDimension="time"/>

Additionaly I have realized that the

**Comment by eknabevcc** [comment]
Thanks for testing the speed/distance dimension and reporting the bug, good finding! It should be fixed now in commit [a467a32](https://github.com/esmini/esmini/commit/a467a324459d895b33eddd1f90e265b46f37d827). Included in [release 2.3.1](https://github.com/esmini/esmini/releases/latest).

Regarding cubic vs sinusoidal. You're right, there is no obvious difference, that's why we did not rush implementing the cubic one. But there is a subtle difference, and I believe the cubic one is slightly more "natural". Please see this [function comparison](https://www.desmos.com/calculator/rkotnmct09).

And also this plot from esmini race:
![image](https://user-images.githubusercontent.com/29146839/107477348-de500b00-6b77-11eb-9587-c83c0e59a1cf.png)

Videoclip of the same scenario (red is cubic, white is sinus):

https://user-images.githubusercontent.com/29146839/107477871-d775c800-6b78-11eb-8e33-ae84e3b0329a.mp4

I agree, you can hardly see the difference...

**Comment by eknabevcc** [comment]
Did you find the bug fix OK? In that case I think we can close the issue.

**Comment by TKeutgens** [comment]
Everything seems fine now. Thanks a lot!
