### ISSUE TITLE
Need clarification for EsminiLib methods

### ISSUE THREAD

**Issue by ebadi** [esmini/esmini#76]
**Q1: [SE_StepDT](https://github.com/esmini/esmini/blob/243505cc792775694fd6e8dc10593c996d6ec8ed/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L161):**
What is the dt (time step) parameter? Is it a method for fast forwarding a simulation?

**Q2: [SE_GetNumberOfObjects](https://github.com/esmini/esmini/blob/243505cc792775694fd6e8dc10593c996d6ec8ed/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L290)**
Does the number of objects changes during the lifetime of a scenario? Does it need to be updated in each simulation step?

**Q3: [SE_GetObjectState](https://github.com/esmini/esmini/blob/243505cc792775694fd6e8dc10593c996d6ec8ed/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L298)** 
SE_GetObjectStateis used to get an object state by its index, but not all attributes can be updated using SE_Report* methods. It also seems that changes in these attributes are not permanent. Is this a limitation or am I missing sth?  It also seems that the effects of SE_Report* methods are temporary as it gets back to the previous value in the next simulation step!

**Q4: [SE_GetRoadInfoAtDistance](https://github.com/esmini/esmini/blob/243505cc792775694fd6e8dc10593c996d6ec8ed/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L330)** 
SE_GetRoadInfoAtDistance extracts road information at a specific distance, not by its id. The SE_RoadInfo struct also does not have the roadID to identify which road it is referring to. IS there a way to identify which road the ego vehicle is at?

**Q5: RoadManager**
What can be done with the handle that is returned by [SE_GetODRManager](https://github.com/esmini/esmini/blob/243505cc792775694fd6e8dc10593c996d6ec8ed/EnvironmentSimulator/Libraries/esminiLib/esminiLib.hpp#L217)? 
Can it somehow be used by methods in [esminiRMlib](https://github.com/esmini/esmini/blob/243505cc792775694fd6e8dc10593c996d6ec8ed/EnvironmentSimulator/Libraries/esminiRMLib/esminiRMLib.hpp)?
Can an odr file be visualized once it is opened with RM_Init()?

**Comment by eknabevcc** [comment]
**Q1: SE_StepDT**
There are two step functions: 
SE_DLL_API int SE_StepDT(float dt);
SE_DLL_API int SE_Step();
The first one allows the user (programmer) to specify the timestep, while the second one hands over to esmini to measure delta time sine last step. So the StepDT is good when you want a fixed timestep (typically batch testing) and Step is good when you just want an interactive/realtime use case.

If you want to review a scenario-run and also move along time-axis in a scenario I have a suggestion: First run the simulation quick without graphics, then view the result. Like this:
`.\bin\esmini --headless --fixed_timestep 0.02 --osc .\resources\xosc\cut-in.xosc --record sim.dat`

You can then view the file in replayer:
`.\bin\replayer.exe --window 60 60 800 400 --res_path .\resources --file .\sim.dat`
please try the key-shortcut commands to pause/play (space) and step (left/right arrow) the scenario (see [replayer/readme.txt](https://github.com/esmini/esmini/blob/master/EnvironmentSimulator/Applications/replayer/readme.txt)).

**Q2: SE_GetNumberOfObjects**
It will report currently instantiated objects. Typically this will be the same amount as number of Entities declared in the scenario file. All those are populated at start of the scenario. BUT, esmini allows for additional entities, e.g. the SUMO controller spawns vehicles "out of nowhere". So the answer needs to be: Yes, the number of objects CAN change during the scenario. But for "normal" scenarios the number will not change.

 **Q3: SE_GetObjectState**
Correct that the "GetState" returns more info than you can set. For example, it wouldn't make sense to report object dimensions to esmini since those are defined in the scenario file.

The topic about reported state getting overridden: Now we get into tricky stuff. Normally, the so called DefaultController will drive the vehicles along the road, keeping speed and lane offset - nicely follow any curve and crest. And any action, for example SpeedAction will be applied by the DefaultController. So if the object state is updated from outside, it may be overridden sooner or later by the DefaultController. 

So here's where the concept of controllers gets handy. The purpose is exactly this, to hand over control from DefaultController to  any other special thing, e.g. internal DriverModel or an external simulator. One example use case is a human-in-the-loop simulator where another example is a ADAS function in an external vehicle. Those states should be reported to esmini and then not touched by DefaultController. One such controller is called ExternalController. If that is assigned and activated on an object, then you will have total control with the ReportState function.

You can find some info on controller concept [here](https://github.com/esmini/esmini#esmini-controllers), which links to even further info... There is also a few example scenarios demonstrating the concept. If you think ExternalController could solve your use case I can provide a pure example of that one. Just let me know.

**SE_GetRoadInfoAtDistance**
You can use the SE_GetObjectState and provide index of Ego (typically 0). 

**Q5: RoadManager**
This is kind of a special use case. It returns a pointer/reference to the raw roadmanager::OpenDrive object. So if the receiver cast the pointer it will have access to the interface of that class. But I think it could be tricky in terms of Python wrapper. More feasible if you have a C++ environment.

As you hints, I think esminiRMLib would be a better approach. But we have no good idea yet of how to combine the two libs (esmini and esminiRM). So far we've had separated use cases, but I can see the need coming for the superset of functionality. 

And finally, no, unfortunately the RMLib does not include any visualization. Which also is a reason for exposing RM through esminiLib. But, as said - we don't have any good idea yet. Short term solution has been so far to add specific needed function into esminiLib :)

**Comment by ebadi** [comment]
Thanks for the response and the great software you have made. (I have to apologize for not mentioning it in the beginning of my first post)

Q1: SE_StepDT : I thought about recording the scenario and playing it back but when I tried it, it was as slow as playing it with the viewer.   At that time, I was not aware of `--fixed_timestep`  argument, it does the magic that I am looking for. **It is possible to record a scenario in a headless mode using shared library methods but I doubt I can use these methods for replaying a recorded scenario, right?**. In lack of these interfaces, I noticed SE_StepDT behaves strangely as some actions are not triggered. 

Q2: SE_GetNumberOfObjects: OK

Q3: SE_GetObjectState: OK, it does make sense. For some reason, I was wondering if I can move an object between lanes and roads but now I am not sure if it an interesting use case. I read about [Controllers](https://github.com/esmini/esmini/tree/master/Hello-World_coding-example) when I started but totally forgot about it and couldn't put it into context and connect the dots. Now I understand what is happening behind the scene. Thanks.

 Q4: SE_GetRoadInfoAtDistance: OK, for some reason I thought SE_GetRoadInfoAtDistance returns information about the current road that has special importance. You are right, it is possible to get the current road information by looking where the ego object is.

Q5: RoadManager: Not sure what can be done with them but **it would be great if you could expose them**. It is more tricky to interface with C++ but definitely possible (especially if we stick with the basic data types) 
Please take a look at [this short blog post ](https://www.auctoris.co.uk/2017/04/29/calling-c-classes-from-python-with-ctypes/)

**Comment by ebadi** [comment]
I quickly tried the new init function for road manager and it seems to be working without any segfault.

```
pyesmini = PyEsmini("resources/xosc/cut-in.xosc")
pyesminiRM = PyEsminiRM(pyesmini.getODRManager(), fromFile= False)
print(pyesminiRM.RM_GetNumberOfRoads())
print(pyesminiRM.RM_GetRoadLength(0))
```
results in
```
1
1464.434326171875
```

**Comment by eknabevcc** [comment]
Wow, excellent. Amazing - I wouldn't even dare to try that :)
Really good to know. Thanks for trying and sharing the info!

**Comment by eknabevcc** [comment]
Ah, now I see. You imported the shared esminiRMLib. First I thought you managed to grab the raw roadmanager::OpenDrive object via esminiLib in Python context. But nonetheless, this was very useful info, that RMLib also works with Python. Good stuff 👍

**Comment by sterres** [comment]
Can you give an example how the SE_GetODRManager() would be used in C++? 
Do I need to include some esmini header files?

My goal is to use ODRManager to create 4 positions and move the x,y position during the simulation to mock wheel contact points (return value to vehicle dynamics is z position and friction).

**Comment by eknabevcc** [comment]
Interesting use case. I added two minimalistic code examples. One for accessing OpenDrive object from esminiLib (access-odr) and one showing how to use the esminiRMLib. 

https://github.com/esmini/esmini/tree/master/EnvironmentSimulator/code-examples

It's part of the code project. So, if you build the complete project they will end up in esmini/code-examples-bin.

RMLib is somewhat different. And for your use case I think it's better. We have some plans to consolidate the functionality of the two libraries, but that's not on top of backlog.

**Comment by sterres** [comment]
Thank you - that helps a lot! 👍

**Comment by eknabevcc** [comment]
Question sorted out. Closing issue.
