### ISSUE TITLE
Traffic Swarm Action

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#79]
Is there a way to add traffic swarm action in our scenarios? Even though odrviewer can add traffic into opendrive file, I want to add traffic swarm action on my scenario.

**Comment by eknabevcc** [comment]
I totally understand, the odrviewer is too simple. I also want the swarm-traffic action. So far we didn't have enough need, motivating us to implement it - I think it's quite a complex action (at least if it should identify correct road segments for traffic population and have fairly intelligent and polite driver models). 

But we're looking into it. So it may be added eventually. But unfortunately not in near time.

**Comment by aktasalifurkan** [comment]
Thanks a lot for your quick answer I appreciate it, but it is sad that traffic feature can not be added in near time.

**Comment by eknabevcc** [comment]
I'll close the issue for now. But I promise to open it again and let you know when we have some news on this topic.

Thanks for the report. It's good to know about what use cases is of value for external users, even though we need to prioritize our own needs. Sometimes we can do small fixes to support other use cases as well.

And by the way, it is possible for external users to contribute with features they need and can implement on their own. Then we can incorporate via pull request. IF that would be the case with swarm traffic I would recommend to contact us heads-up to synchronize work, since we may have plans for implementing that as well.
