### ISSUE TITLE
Executing esmini on win10 64-Bit

### ISSUE THREAD

**Issue by Leviathan321** [esmini/esmini#80]
I have problems executing esmini from the the latest esmini-demo build, there is nothing displayed after execution in commandline, execution stops immediately.

How can I debug this? Is there some log file?

Thank you.

**Comment by eknabevcc** [comment]
Thanks for testing and reporting.

Yes, there is always a log.txt file created. It should be found in the same directory as esmini started from (working directory). 

I'm also curious about how you run it. Did you try the examples, e.g. run/esmini/run_cut-in.bat? I know there is issues with .dat-files created in a previous version of esmini and then played with a more recent version of replayer (an issue soon to be improved). 

Please run the run_cut-in.bat and drop the log.txt file here, and I will have a look immediately.

**Comment by Leviathan321** [comment]
Yes I have tried the examples, but did also not work. There is no log-file produced in the esmini-demo folders.
The only output I have is in the console:

C:\Program Files\esmini-demo\run\esmini>"../../bin/esmini" --window 60 60 1024 576  --osc ../../resources/xosc/cut-in.xosc

C:\Program Files\esmini-demo\run\esmini>

**Comment by eknabevcc** [comment]
Hm. Interesting case. I have no obvious clue. But maybe the log file can not be created (perhaps due to protected Program Files folder?). I would appreciate if you could do the following attempt:
Try to move/copy esmini-demo folder to another folder created by yourself, e.g. c:/tmp. And run the same scenario from there.

It's a long shot. But IF that works, we need to look over the log file steps. E.g. if it can't be created esmini should put a warning in console and continue anyway.

**Comment by Leviathan321** [comment]
I could solve it: I executed it with administrator rights and then it worked. In some other folder it can also be executed without admin privileges. Thank you for the quick response!

**Comment by eknabevcc** [comment]
Thanks for feeding back the result. Very good to know about this bug. We'll make some change to the logging based on this info 👍
