### ISSUE TITLE
Freespace Problem

### ISSUE THREAD

**Issue by aktasalifurkan** [esmini/esmini#87]
Hello,

While I was examining your example scenario cut-in.xosc, I wanted to change freespace to "false" in CutInAction start trigger. However, I realised that there was no change in triggering time regardless of my choice. After that, I saw the same issue in similar practice at ALKS's CrossingPedestrian.xosc as well.  Is there a way to fix it on my part, or is this still in progress?

Kind regards.

**Comment by eknabevcc** [comment]
Thanks for pointing out this defect and reminding us. It's an old sin, esmini accepting the keyword but then ignoring it...
Now it should be fixed by [commit 9f1fff7](https://github.com/esmini/esmini/commit/9f1fff750d3adddb2fce480a9df425d6870d74f0) and included in [release 2.5.0](https://github.com/esmini/esmini/releases/tag/v2.5.0).
Please test and see if it now makes a difference.

**Comment by eknabevcc** [comment]
Did you have a chance to check the scenario with updated esmini?

**Comment by aktasalifurkan** [comment]
I just tried it and it worked. Thanks a lot, continue to good work 👍

**Comment by eknabevcc** [comment]
Great news, thanks for reporting and testing this!
