### ISSUE TITLE
*.osgb file is missing, no `resources/models` path

### ISSUE THREAD

**Issue by xmyqsh** [esmini/esmini#9]
`
viewer.cpp / 722 / AddEnvironment(): Failed to read environment model ../../../resources/xosc/../models/soderleden.osgb! If file is missing, check SharePoint/SharedDocuments/models
`

No `resources/models` path

**Comment by eknabevcc** [comment]
For Windows, the demo models package should be downloaded automatically. If that failes you can find them here: [3D models used by the example scenarios](https://drive.google.com/uc?export=download&id=1RSbyFJoVahX1nGWAsdepsPsznAiNspUc).

Since the 3D models work for any platform, the info has moved from Windows build instruction to the main (generic) README. 

Thanks for input.
