### ISSUE TITLE
Failed to initialize scenario player

### ISSUE THREAD

**Issue by S1201149** [esmini/esmini#92]
![Esmini-1](https://user-images.githubusercontent.com/51198479/112092877-751fd680-8bbe-11eb-8045-d4fa7fd8aa72.PNG)
![esmini-error](https://user-images.githubusercontent.com/51198479/112092882-781ac700-8bbe-11eb-8ffe-500961286654.PNG)

Hello,
I have downloaded esmini player for windows. While running the exe file I am getting "Failed to initialize scenario player " error
Please find the attachment for error details. Kindly help me with the installation process.

Thanks in advance!!

**Comment by eknabevcc** [comment]
First, make sure you downloaded the [demo package (esmini-demo_win.zip)](https://github.com/esmini/esmini/releases/download/v2.5.2/esmini-demo_win.zip). It includes some example scenarios and road models. There is also binary packages (e.g esmini-bin_win_x64.zip), but these contains only actual executables and libraries - no scenarios.

The demo package contains everything you need, and after unzipping it no further installations steps are needed.

Now, esmini.exe is just a player. There is no default scenario. So you have to provide which scenario to play. You can test the examples provided in the `run/esmini` folder. Just double click on e.g. `run_cut-in.bat` and it should launch esmini playing the cut-in scenario.

An alternative is to launch with custom arguments from command line. From esmini root folder try:
` .\bin\esmini.exe --window 60 60 800 400 --osc .\resources\xosc\cut-in.xosc`

I hope this solves the problem and helps you get going.

**Comment by S1201149** [comment]
> First, make sure you downloaded the [demo package (esmini-demo_win.zip)](https://github.com/esmini/esmini/releases/download/v2.5.2/esmini-demo_win.zip). It includes some example scenarios and road models. There is also binary packages (e.g esmini-bin_win_x64.zip), but these contains only actual executables and libraries - no scenarios.
> 
> The demo package contains everything you need, and after unzipping it no further installations steps are needed.
> 
> Now, esmini.exe is just a player. There is no default scenario. So you have to provide which scenario to play. You can test the examples provided in the `run/esmini` folder. Just double click on e.g. `run_cut-in.bat` and it should launch esmini playing the cut-in scenario.
> 
> An alternative is to launch with custom arguments from command line. From esmini root folder try:
> ` .\bin\esmini.exe --window 60 60 800 400 --osc .\resources\xosc\cut-in.xosc`
> 
> I hope this solves the problem and helps you get going.

**Comment by S1201149** [comment]
Hello Emil Knabe,
Thanks for the response!!
I have downloaded both  demo package (esmini-demo_win.zip) and binary packages (e.g esmini-bin_win_x64.zip).
While trying to run scenarios from demo package with esmini.exe from  esmini-bin_win_x64.zip as you mentioned (.\bin\esmini.exe --window 60 60 800 400 --osc .\resources\xosc\cut-in.xosc), I am still getting the same error.
Please find the attachment for error details
![esmini-error](https://user-images.githubusercontent.com/51198479/112103900-722de180-8bd0-11eb-8e9d-edf6f22b8038.PNG)

And along with these I have few more queries
1) Is there any way to create my own scenario files(.xosc files) with esmini or it is just executes the scenarios?
2) How to create batch (.bat) files from .xosc as in esmini demo?

It would be more helpful if you could help with this.

**Comment by eknabevcc** [comment]
Sorry, my message was not clear. You should NOT use the binaries esmini-bin_win_x64.zip. Demo package alone is enough.
So, please make sure you grab the demo package. Then just:

1. unzip it
2. open a command window in esmini root folder
3. run: `.\bin\esmini.exe --window 60 60 800 400 --osc .\resources\xosc\cut-in.xosc`

Regarding scenarios: Well, esmini accepts any scenario. But they are not very simple to create. There is the https://github.com/pyoscx/scenariogeneration project that could be interesting. Otherwise I recommend to check the esmini example scenarios (located in `resources/xosc` folder), and maybe manipulate them in a text editor.

Finally regarding batch-files. Please check out the provided examples in `run/esmini` folder (in demo package). There you can find out how to make similar ones of your own.

**Comment by S1201149** [comment]
Hi,
I am able run scenarios in the esmini demo folder which is already present.
I have downloaded ### scenario generator (https://github.com/pyoscx/scenariogeneration) and used the python example scenario to run ### esmini from python script.
The python program creates .xosc and .xdr files and launch esmini player to run the scenario
Without call to esmini the script works fine. In the program I have provided the path to esmini as path where the esmini demo file resides. While running the python script I am getting ### "Failed to initialize scenario player error"
Please find the attachment for the error details and python script. 
![esmini-error](https://user-images.githubusercontent.com/51198479/112434579-c28c7700-8d69-11eb-83ea-b7862a8ef22a.PNG)

[samplscenariogeneration.txt](https://github.com/esmini/esmini/files/6202755/samplscenariogeneration.txt)

**Comment by eknabevcc** [comment]
It looks like you did everything correct. Obviously the script finds esmini, since the console shows output from esmini.exe.

Could you provide the complete console message, or attach the log.txt file (should be created by esmini in the folder from where you run the Python script). 
Then I can investigate further. I'm convinced we'll soon solve it. 

BTW: this is how it looks when I run your script:
![image](https://user-images.githubusercontent.com/29146839/112447214-5867d800-8d51-11eb-95b3-d1a15ed3ba73.png)

**Comment by eknabevcc** [comment]
If the issue still remains, we need the complete log.txt or console output in order to investigate further. 
Otherwise I suggest we close the issue.

**Comment by S1201149** [comment]
Hi,
Thanks for the reply.
I solved the issue with the python script running esmini player by placing the esmini demo folder directly in the "C drive".
I think the issue was with the folder path.
Only issue I am facing now is running .xosc files with esmini player.
I have tried the same way as suggested by you but still getting the error _"Failed to initialize scenario player"_
Please find the attached log.txt from esmini and screenshot of the issue.

Thanks in advance!!
[log.txt](https://github.com/esmini/esmini/files/6310278/log.txt)
![image](https://user-images.githubusercontent.com/51198479/114698996-5cc65600-9d3d-11eb-93c6-9f3966b6bc15.png)

**Comment by eknabevcc** [comment]
Thanks for providing detailed logs!
I think the problem is that the scenario file is not located where you point to. The ".\resources..." indicates that the resources folder should be within/under the current folder (which is "esmini-demo/bin" in your example).
So the solution I think is: Move up one level (to esmini-demo). And from there run:
`./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/cut-in.xosc`

(or from esmini-demo/bin: `../bin/esmini --window 60 60 800 400 --osc ../resources/xosc/cut-in.xosc`)

I hope this will work.

**Comment by eknabevcc** [comment]
Sorry I see now that you run from cmd. You should run:
`.\bin\esmini --window 60 60 800 400 --osc .\resources\xosc\cut-in.xosc`

(or from esmini-demo/bin: `..\bin\esmini --window 60 60 800 400 --osc ..\resources\xosc\cut-in.xosc`)

It's a mess with different platforms and consoles and slashes leaning this or other way :)

**Comment by S1201149** [comment]
One more clarification required is "How to generate .bat files"

**Comment by eknabevcc** [comment]
You mean .dat or .bat?

**Comment by S1201149** [comment]
"You mean from esmini console I need to run the .xosc files. 
Whenever I try to run esmini it is getting closed immediately. 
Esmini application is present in this path "C:\esmini-demo_win\esmini-demo\bin"

**Comment by S1201149** [comment]
> You mean .dat or .bat?

Windows batch files(.bat).Like the ones which is present under "C:\esmini-demo_win\esmini-demo\run\esmini"

**Comment by eknabevcc** [comment]
But if you run esmini as I stated [here](https://github.com/esmini/esmini/issues/92#issuecomment-819434212), then it should not close immediately.
If you want to run it simple from a batch script, my suggestion is to copy one of the existing ones in esmini/run/esmini folder - and tweak for your use case.

**Comment by S1201149** [comment]
Thank u for your immediate response @eknabevcc . It really helps in solving the issue
