### ISSUE TITLE
odrplot gives zigzag lanes

### ISSUE THREAD

**Issue by cy-goh** [esmini/esmini#93]
I'm running Ubuntu 18, and using odrplot to check out an opendrive 1.4 xodr I've gotten from a map vendor.

I ran the odrplot under bin `./odrplot ~/Downloads/gd.xodr ~/Desktop/track.csv 0.1` and then` python xodr.py ~/Desktop/track.csv ` under /EnvironmentSimulator/Applications/odrplot, the matplotlib visualization shows this:

Any idea?

![mapodr](https://user-images.githubusercontent.com/834508/112103646-04d87b80-8be5-11eb-9d88-57d58867b75f.png)
![mapodr_zoom](https://user-images.githubusercontent.com/834508/112103655-073ad580-8be5-11eb-9cf4-dcb3ba4d65a5.png)

**Comment by eknabevcc** [comment]
Thanks a lot for reporting this issue. You found a silly bug that cause precision problem for distant coordinates. 
It has now been fixed (commit [c07a249](https://github.com/esmini/esmini/commit/c07a249d54f012a07979be806a9a4183d0890632)).

I hope that you can compile yourself. Otherwise the fix will be part of next upcoming release. I can also provide a Linux executable if you want asap, let me know in that case.

This is how the difference looks for a road located at X = 1000000, Y = 1000000
Old:
![image](https://user-images.githubusercontent.com/29146839/112114909-e3fa3100-8bb8-11eb-959d-ca6fd972e77c.png)
Now:
![image](https://user-images.githubusercontent.com/29146839/112114948-ef4d5c80-8bb8-11eb-8923-f4a63d295f96.png)

**Comment by cy-goh** [comment]
What quick response! I was just about to comment saying I have also fixed this. 

Thank you!
