### ISSUE TITLE
use ExternalController without modifying the osc file

### ISSUE THREAD

**Issue by sterres** [esmini/esmini#98]
Hi,

need your help again.

I'm able to change the ego vehicle position from external using the ExternalController described in hello world example.

However, for my use-case it would be nice to just activate the external controller from ESminiLib (without having to modify every osc file first).

I could not find any method, but the object state seems to have the attribute already (int ctrl_type;).

so sth like _SE_setVehicleController(id, ctrl_type);_

Any chance to enable this without too much effort?

Best regards
Simon

**Comment by sterres** [comment]
Addition: 
Of course I tried it already with a "clean" xosc, but then it keeps snapping back to road (and heading is not synced).

**Comment by eknabevcc** [comment]
There could be an API to control similar thing that the OpenSCENARIO file specify. It's an interesting idea, and I know it's being discussed. 
But we find it very useful to try to stick with the OpenSCENARIO description, and minimize hidden stuff going on between any vehicle simulator and esmini. I mean, it's good that the dynamics of a simulation/test case is exposed in the OSC description.
But of course, we have some cheats in esmini as well, for example --disable_controllers flag... So I shouldn't rule out adding a function as you propose. But we should be careful since it might come with unexpected side effects (since it interferes with scenario dynamics...). 

However I would like you to try another approach:
- Define a parameter in the scenario file. E.g. 
`<ParameterDeclaration name="myTrigger" parameterType="boolean" value="false"/>`
- Then, define one event for activating the controller. I.e. ActivateController action on e.g. Longitudinal and Lateral domains.
- Set a trigger based on the parameter, e.g: 
```
  <ByValueCondition>
     <ParameterCondition parameterRef="myTrigger" value="true" rule="equalTo"/>
  </ByValueCondition>
```
- And one event for  disable controller, I.e. ActivateController action on NO domains (false on both).
- With a similar but inverse trigger, e.g:
```
  <ByValueCondition>
     <ParameterCondition parameterRef="myTrigger" value="false" rule="equalTo"/>
  </ByValueCondition>
```
- Finally, from the application you should now be able to control the "controller" by:
`SE_SetParameterBool("myTrigger", true);`, and
`SE_SetParameterBool("myTrigger", false);`

I think this would be an interesting approach 👍, and OpenSCENARIO-way, of doing it. It would be appreciated if you could try, and report how it goes...

Another solution would be if you could try implement the function yourself, and propose as a pull request.

**Comment by sterres** [comment]
Thanks for the detailed response.

The implementation you propose seems more useful for de-/activating external controllers during runtime.

Also, you raise a good point with the OSC standard way of doing things. But are the controller definitions part of OSC or more like vendor annotations which make the OSC files esmini specific?

However, having a big scenario catalogue, it would mean I have to batch process them to make them all work with esmini. My idea was to keep the OSC files untouched and change it via API for the closed-loop simulation environment.

I will try to implement and make a pull request once it is working and still makes sense to me :)

**Comment by eknabevcc** [comment]
Reading your initial question again I realized there might be another solution:

- Put InteractiveController in all relevant scenarios, to be ready for use.
- Then, when launching esmini (from command line or SE_Init()) you have the option to disable controllers altogether throughout the whole scenario. 

Example from command line:
`./bin/esmini --window 60 60 800 400 --osc ./resources/xosc/ltap-od.xosc --disable_controllers`
From C++/esminiLib:
`SE_Init(filename, 1, 1, 0, 0);`  (First "1" will enable viewer. Second "1" will disable controllers.)

This is a useful feature if you want to quickly preview a scenario using esmini default controller, and then in a real test hand over to your external simulator/driver/AD function...

Then regarding OSC standard way of doing things. You're totally right. OpenSCENARIO does not dictate what a controller can or should do, or how it do its things. Only the concept is defined by the standard, e.g. how the controller is specified, assigned and activated (on domains). And also there is a few use cases described for understanding and inspiration.

I hope you find a way forward that matches you need. Just get back to us if you have questions or pull requests :)

**Comment by ZhangZongshi-Catarc** [comment]
Hi,

Could you please provide me some advice about the IdealSensor? 
After i add some sensors on the object vehicle, how can i get the state of the detected entities? Such as speed, X,Y,Z values in the vehicle local coordinates and so on?
Till this moment, i can only get the No. of entities according to 'SE_FetchSensorObjectList'.
### IdealSensor

Best Regard
Zongshi

**Comment by eknabevcc** [comment]
@ZhangZongshi-Catarc: I guess the question now is handled in issue #101

So I don't answer it here again, instead we'll keep this issue focused on the activate controller question 👍

**Comment by eknabevcc** [comment]
Options explained and discussed. Closing the issue for now. Please re-open for further discussion/questions.
